feat(scale-down): Update Owner Logic
philips-labs/terraform-aws-github-runner pull request #1065
Opened 2021-08-10 19:07 UTC by mcaulifn

- Updates scale down logic to look at runner owner when evaluating which runners to terminate
- Changes tags on instance to `tag = type` and `tag = owner` instead of `tag = type` and  `value = owner`
- Isolates scale down tests

Resolves #1021

2021-08-16 20:07 UTC, mcaulifn commented
Would it be worthwhile to add a function to deal with runners that got pulled in with the environment tag but then do not have any other tags?

2021-08-18 11:49 UTC, mcaulifn commented
@npalm I am marking this ready for review. I am working on some very small code changes to deal with orphaned runners. That will solve the bug I identified and also address your concerns. I will update the PR description with that callout.

2021-08-18 15:10 UTC, mcaulifn commented
@npalm I created https://github.com/mcaulifn/terraform-aws-github-runner/pull/2 as a way to deal with legacy runners. If the approach is good, I'll merge.

2021-08-20 13:54 UTC, gertjanmaas commented
@mcaulifn did a review on https://github.com/mcaulifn/terraform-aws-github-runner/pull/2 only some small comments

If that's merged in here, it looks good to me. 

Nice work and thanks for improving this project!

2021-08-20 14:29 UTC, mcaulifn commented
@gertjanmaas @npalm I think this should be ready. I will be testing it out in our dev environment next week.

2021-08-20 14:33 UTC, npalm commented
@mcaulifn will check the PR early nexrt week as well. @gertjanmaas thanks for checking

2021-08-21 08:54 UTC, npalm requested changes

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/runners.ts
> +  Repo?: string;
For consistency can you change Repo and Org to repo an org (lowercase / camelCase)? Similar to the other interface properties

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +            ec2Runners.splice(getIndex(ec2Runners, ec2Runner), 1);
Not sure if it is safe to update the list during iteration. The splice operation is also duplicated 3 times. Should not be necessary

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +  if (!(ec2Runners.length === 0)) {
Those runners are not orphan, since the remaining list are the runners that are not exeeding the minimum booting time, see line 115. We have used this minimum time to avoid runners will be killed before they are ready and registered.

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +function filterNewRunners(ec2runners: RunnerList[]): RunnerInfo[] {
Would call this function simply filterRunners

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
```suggestion

/**
 * We are moving to a new strategy to find and remove runners, this function will ensure
 * during migration runners tagged in the old way are removed.
 */
```

2021-08-21 08:54 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +  legacyRunners.forEach((runner) => {
This will force kill any old tagged runner, and also stop any build running. It also will not de-register the runner from github. Can you add a check the runner is not active and de-register ti as well?

2021-08-23 12:53 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/runners.ts
> +  Repo?: string;
Fixed.

2021-08-23 13:14 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +            ec2Runners.splice(getIndex(ec2Runners, ec2Runner), 1);
I was able to move the splice operation to encompass all three instances.

2021-08-23 13:20 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +  if (!(ec2Runners.length === 0)) {
Good catch!

2021-08-23 13:21 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +function filterNewRunners(ec2runners: RunnerList[]): RunnerInfo[] {
Done

2021-08-23 18:38 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +  if (!(ec2Runners.length === 0)) {
This should be dealing with the correct set of orphaned runners now.

2021-08-23 18:39 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +            ec2Runners.splice(getIndex(ec2Runners, ec2Runner), 1);
After re-working some logic, I no longer needed to update the original list.

2021-08-23 18:40 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +  legacyRunners.forEach((runner) => {
The legacy list is now passed through the same logic as the new list.

2021-08-23 20:35 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
If the diffs shows it correctly, it seems orphan runners are removed if not `(runnerMinimumTimeExceeded(ec2Runner, minimumRunningTimeInMinutes))`. This will remove all runners that are NOT exceeding the minimal time. So potential still executing the user_data script. Orphan runners are all runners that not registred in github but running in aws as ec instance longer then the minimal time. 

So removal should be done if NOT `ghRunner` and minimal time exeeded. So suggest you swap if clauses on line 113 and 114. Next move the terminateOrphan to the else of the most inner if

2021-08-24 11:54 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
I don't think the diff is rendering correctly. I copied that section below and added two notes.

```typescript
      if (ghRunner) {
        if (runnerMinimumTimeExceeded(ec2Runner, minimumRunningTimeInMinutes)) {
          if (idleCounter > 0) {
            idleCounter--;
            console.debug(`Runner '${ec2Runner.instanceId}' will kept idle.`);
          } else {  //If the idle counter is not greater than 0
            await removeRunner(ec2Runner, ghRunner.id);
          }
        // implied else - If the runner min time not exceeded, continue
        }
      } else {
        console.debug(`Runner '${ec2Runner.instanceId}' is orphaned and will be removed.`);
        terminateOrphan(ec2Runner.instanceId);
      }
```

2021-08-24 18:40 UTC, mcaulifn commented
@npalm I deployed locally and I see a legacy runner and new runners being handled correctly.

2021-08-24 19:36 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
I still think the code is not correct see below the part int he PR, second part my proposal
```
      if (ghRunner) { // runner registred in github
        if (runnerMinimumTimeExceeded(ec2Runner, minimumRunningTimeInMinutes)) { // runner is not running minimum time 
          if (idleCounter > 0) {
            idleCounter--;
            console.debug(`Runner '${ec2Runner.instanceId}' will kept idle.`);
          } else {  // enough idle runners so remove
            await removeRunner(ec2Runner, ghRunner.id);
          }
        // implied else - If the runner min time not exceeded, continue
        }
      } else { // runner not registred in gihub, potential not exceedining minimal time, current code (dev) has check.
        console.debug(`Runner '${ec2Runner.instanceId}' is orphaned and will be removed.`);
        terminateOrphan(ec2Runner.instanceId);
      }
```

Proposed change, we swam the check for minimal time and ghRunner, so if the runner is not a ghRunner we can safely remove the runner still it execeeded the minimal required time to boot. 
```
    if (runnerMinimumTimeExceeded(ec2Runner, minimumRunningTimeInMinutes)) { 
      if (ghRunnr) { 
        if (idleCounter > 0) {
            idleCounter--;
            console.debug(`Runner '${ec2Runner.instanceId}' will kept idle.`);
        } else {  // enough idle runners so remove
            await removeRunner(ec2Runner, ghRunner.id);
        }
      } else { // runner not registered
          console.debug(`Runner '${ec2Runner.instanceId}' is orphaned and will be removed.`);
          terminateOrphan(ec2Runner.instanceId);
        }
      }
    }
```

2021-08-24 19:43 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
> if (runnerMinimumTimeExceeded(ec2Runner, minimumRunningTimeInMinutes)) {  // runner is **not** running minimum time 
Is the "not" intended here? I removed the `!` so it is now checking if the minimum time has been met.

2021-08-24 20:27 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
I realized I missed the comment "So potential still executing the user_data script". That shouldn't be the case as the default is 5 minutes and should be enough time to register. It might be worth calling out that this value should be the the user data execution time plus an additional allowance. In our case, with a 60 minute minimum run time, we don't want an orphaned runner hanging around for that long.

2021-08-24 20:57 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
Actually the minimum time for runners had initial 2 functions.
- ensure the runner gets enough time to boot
- the minimal time we keep the runner for re-use. Over time we would lik to move to a aystem that be default uses the runner once. But we are not here yet. 

In the past we had some times the problem a runner is not booting correct at all. This caused ec2 instances that are running but not registered to github. We called them orphan. But to avoid we clean up to early. Since boot time can be involved we only clear them after the mininum time. You are right we could differ between a minimum time and a minimum time for the user data to get executed.

2021-08-25 12:05 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
> +        terminateOrphan(ec2Runner.instanceId);
I updated the variable description to call out the necessity for this value to allow the runner enough time to boot and register.

2021-08-30 16:40 UTC, mcaulifn commented
@gertjanmaas Anything else on this one?

2021-08-31 06:52 UTC, gertjanmaas approved these changes

2021-08-31 06:53 UTC, gertjanmaas commented
Looks good to me, tested the default example and works as expected. @npalm do you want to take a look at it?

2021-08-31 12:07 UTC, npalm commented
@gertjanmaas thanks for checking, please feel free to merge

2021-08-31 12:24 UTC, merged