current value turned to default under new variable, for issue #748
philips-labs/terraform-aws-github-runner pull request #1112
Opened 2021-08-18 12:32 UTC by new23d

Proposed code changes to accommodate custom default egress rules, as discussed under issue #748.

Inspired by the GitLab runners code as mentioned under that issue.

Early feedback on these changes is most welcome!

Also, terraform-docs on my end seems to change a lot of the formatting in the README.md files. Am I missing or not doing something obvious? It adds a lot of HTML tags in each line in the tables, hyperlinking to the resources I guess. I'd have thought such formatting should already be present in the current files.

2021-08-18 14:40 UTC, npalm requested changes
Small change requested.

2021-08-18 14:40 UTC, npalm commented on modules/runners/variables.tf
> +  }))
Can you add the same defaults here as the top level variables.tf? This will help the consumers of the submodule.

2021-08-18 14:54 UTC, new23d commented on modules/runners/variables.tf
> +  }))
Done.

2021-08-19 07:54 UTC, npalm approved these changes
@new23d thanks! LGTM

2021-08-19 07:55 UTC, merged