Cleaned-up/revised the README for clarity
philips-labs/terraform-aws-github-runner pull request #1325
Opened 2021-10-22 23:52 UTC by skyzyx

* Grammar fixes for the english language.
* Use proper capitalization for official product names.
* Hyphenated the compound modifiers.
* Added some tips that would have helped me when I was setting this up.
* Added more headers so that it's less of a wall-of-text, and easier to visually skim.
* Provided some concrete examples, rather than requiring readers to guess.
* Removed a couple of decision points, and just made the decision _for_ the reader so that they don't get overwhelmed. (This is already pretty complex.)

2021-11-03 21:45 UTC, npalm commented
@skyzyx did you had the time to look on the review comments?

2021-11-05 22:14 UTC, skyzyx commented
I hadn't, but I'm looking now.

2021-11-05 22:17 UTC, skyzyx commented on README.md
> +rm -Rf /tmp/aws-github-runner
Right. This is simply ensuring that it's completely clean. If you try to `rm` a file or dir which doesn't exist, you'll get an error.

2021-11-05 22:22 UTC, skyzyx commented on README.md
> +```plain
That's fine. I left those in the example because I think that many people will end up with projects that include those (fairly common) files. But after reconsideration, I think I agree with you.

2021-11-05 22:28 UTC, skyzyx commented on README.md
> +In this example, this file lives in the filesystem at `{root}/bin/build-lambdas.sh`.
I didn't miss it. I just have an internal fork with customizations — which I'm in the processes of opening PRs for — until those changes land on your `master` branch.

But you're right. For those using the project as-is, the _pristine_ `.zip` files can be downloaded from the _Releases_ page.

2021-11-05 22:29 UTC, skyzyx commented
I believe I've addressed your feedback.

2021-11-09 08:20 UTC, npalm requested changes
@skyzyx thanks a lot, a small request for a change. And a rebased in required.

2021-11-09 08:20 UTC, npalm commented on README.md
> +> **IMPORTANT:** This is only required if you choose to compile the code from source (e.g., you have local edits in a fork). As an alternative, you may also download the _pristine_ pre-compiled `.zip
```suggestion
> **IMPORTANT:** This is only required if you choose to compile the code from source (e.g., you have local edits in a fork). As an alternative, you may also download the _pristine_ pre-compiled `.zip` files from the _Releases_ page or via the [download-lambda module](./modules/download-lambda) terraform module (requires `curl` to be installed on your machine).
```

2022-05-08 18:14 UTC, ScottGuymer commented
@skyzyx @npalm should we get this in a state to merge again?

I think the improvements here are very valuable and we should merge them.

2022-06-19 02:17 UTC, closed without merging