add option ephemeral runners
philips-labs/terraform-aws-github-runner pull request #1374
Opened 2021-11-03 21:07 UTC by npalm

2021-11-03 21:10 UTC, npalm commented
#fix 1375

2021-11-03 21:10 UTC, npalm commented
part of #1372

2021-11-19 20:13 UTC, mcaulifn commented on examples/ephemeral/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
This file should probably be excluded.

2021-11-19 20:13 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +    // TODO: how to handle the event if the max is reached in case of ephemeral runners
It would have to be unlimited if using ephemeral.

2021-11-19 20:24 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +    // TODO: how to handle the event if the max is reached in case of ephemeral runners
yepz or an retry mechanism to process events once the limit is reach. Also AWS accounts have soft and hard limits.

2021-11-19 20:25 UTC, npalm commented on examples/ephemeral/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
No, why. It is locking the versions

2021-11-19 20:27 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +    // TODO: how to handle the event if the max is reached in case of ephemeral runners
Maybe it could re-queue the message with a delay?

2021-11-19 20:28 UTC, mcaulifn commented on examples/ephemeral/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
It is the example so I was thinking it wasn't really needed.

2021-12-02 13:45 UTC, npalm commented on modules/runners/templates/user-data.sh
> +# TODO: svc.sh start replaced by run.sh and once stopped / exitted the instance terminated
First merge #1444

2021-12-02 13:46 UTC, npalm commented on modules/runners/policies/instance-ec2.json
> +      "Condition": {
Find a better condition

2021-12-10 17:20 UTC, npalm commented
@ScottGuymer Please can you have a look on the PR. Still need to update docs, but coding part should be done.

2021-12-10 17:37 UTC, ScottGuymer reviewed
Partial review with some small thing

2021-12-10 17:37 UTC, ScottGuymer commented on examples/default/main.tf
> +  delay_webhook_event   = 10
Any reason for these to change as there is a distinct example for ephemeral too. Are these breaking changes?

2021-12-10 17:37 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/lambda.ts
> +    logger.warn('Event ignored, only on record at the time can be handled, ensure the lambda batch size is set to 1.');
```suggestion
    logger.warn('Event ignored, only one record at the time can be handled, ensure the lambda batch size is set to 1.');
```

2021-12-10 17:37 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
> +    it('ephemeral runners cannot only run with workflow_job event, others should fail.', async () => {
```suggestion
    it('ephemeral runners only run with workflow_job event, others should fail.', async () => {
```

2021-12-10 17:37 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +    logger.warn(`${payload.eventType} even is not supported in combination with ephemeral runners.`);
```suggestion
    logger.warn(`${payload.eventType} event is not supported in combination with ephemeral runners.`);
```

2021-12-10 17:37 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      `The workflow_job type ${payload.eventType} is not supported in combination with ephemeral runners.` +
```suggestion
      `The event type ${payload.eventType} is not supported in combination with ephemeral runners.` +
```

2021-12-13 07:02 UTC, PatrickMennen requested changes

2021-12-13 07:02 UTC, PatrickMennen commented on modules/runners/lambdas/runners/src/lambda.ts
> +  if (event.Records.length != 1) {
!==

2021-12-13 07:02 UTC, PatrickMennen commented on modules/runners/lambdas/runners/src/lambda.ts
> +          logger.warn('Ignoring error: ', e);
`Ignoring error:  ${e}`

2021-12-13 07:02 UTC, PatrickMennen commented on modules/runners/lambdas/runners/src/scale-runners/runners.ts
> +  if (runInstancesResponse.Instances != undefined) {
!== or if (runInstances.Instances)

2021-12-13 07:02 UTC, PatrickMennen commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +  if (ephemeralEnabled && payload.eventType != 'workflow_job') {
!==

2021-12-13 07:33 UTC, gertjanmaas approved these changes
Other than the one comment, looks good :)

2021-12-13 07:33 UTC, gertjanmaas commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
> +      expectedRunnerParams.runnerServiceConfig = expectedRunnerParams.runnerServiceConfig + `  --ephemeral`;
Does this test work? seems there are 2 spaces before `--ephemeral`, which I assume should be one.

2021-12-13 08:57 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
> +      expectedRunnerParams.runnerServiceConfig = expectedRunnerParams.runnerServiceConfig + `  --ephemeral`;
It works, but should be a single space.

2021-12-14 10:42 UTC, ScottGuymer requested changes
Some small comments

In good shape, almost ready to merge.

2021-12-14 10:42 UTC, ScottGuymer commented on README.md
> +- _[Prebuilt Images](examples/prebuilt/README.md)_: Example usages of deploying runners with a custom prebuilt image.
This is now in there twice

2021-12-14 10:42 UTC, ScottGuymer commented on examples/ephemeral/README.md
> +
Some more info on how this is different to a default setup and the key settings that make it different would be useful here

2021-12-14 10:42 UTC, ScottGuymer commented on variables.tf
> +  description = "Set options to attach (optional) a dead letter queue to the build queue, the queue between the webhook and the scale up lambda. You have the following options. 1. Disable by setting,
I wonder if adding the ability to bring your own DLQ is just adding too much complexity here. Is there a need to create it outside of the module?

2021-12-14 10:42 UTC, ScottGuymer commented on variables.tf
> +  default     = 30
Is this changed for testing or a new default?

2021-12-14 10:42 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
> +        expectedRunnerParams.runnerServiceConfig + ` --labels label1,label2 --runnergroup TEST_GROUP`;
I think it might be better when working with these command to use a string array and then [join](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) then with a space. Rather than having to worry about spaces in all the strings etc.

`runnerServiceConfig` could be defined as a string array above and you can merge the arrays and join.

2021-12-14 10:42 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      const runnerArgs = `--token ${token} ${labelsArgument}${ephemeralArgument}`;
Again it might be better to work with string arrays and join here. More precise and less concerns about spacing etc.

2021-12-14 10:42 UTC, ScottGuymer commented on modules/webhook/lambdas/webhook/src/webhook/handler.test.ts
> +    it('handles check_run events with no installation id.', async () => {
What happens if it is set to a string?

2021-12-14 11:25 UTC, npalm commented on variables.tf
> +  description = "Set options to attach (optional) a dead letter queue to the build queue, the queue between the webhook and the scale up lambda. You have the following options. 1. Disable by setting,
The rational is. The whole setup is immutable. So if you would like to process for whatever reason failures and we manage the queue, an re-create will enforce also the re-creation of this queue. It also allows other configuration, attaching you own way to process / handle messages easier. But maybe we should leave it out as long we have not a "real" use case.

2021-12-14 11:26 UTC, npalm commented on variables.tf
> +  default     = 30
Changed, because I think the default is a way to high. The same time the messages is blocked as well in case of failure.

2021-12-14 11:27 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
> +        expectedRunnerParams.runnerServiceConfig + ` --labels label1,label2 --runnergroup TEST_GROUP`;
Agree, but suggest we raise a seperate issue to get the whole parsing logic refactored. OK?

2021-12-14 11:28 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      const runnerArgs = `--token ${token} ${labelsArgument}${ephemeralArgument}`;
Agree, but not all properties are valid in all situation.

2021-12-14 11:35 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      const runnerArgs = `--token ${token} ${labelsArgument}${ephemeralArgument}`;
No but you could build the string array based on the logic and then just `join` it at the end without having to worry about what space are needed where.

2021-12-14 11:38 UTC, ScottGuymer commented on variables.tf
> +  description = "Set options to attach (optional) a dead letter queue to the build queue, the queue between the webhook and the scale up lambda. You have the following options. 1. Disable by setting,
Yeah, I think we should start simple with this and only add things as the use case becomes apparent. This module is already quite complex, we should find ways that these extra use cases can be added by extension on top of the module rather than adding them into the module.

For example, we could set the DLQ as an output that could be used as needed. Someone could take that output and use it as an input to some other module that adds extra functionality to the queue.

2021-12-14 12:30 UTC, npalm commented on variables.tf
> +  description = "Set options to attach (optional) a dead letter queue to the build queue, the queue between the webhook and the scale up lambda. You have the following options. 1. Disable by setting,
Problem of the output is that the use have no control over the queue, but agree in general. So I will remove the injection of the extra queue. And remain the optional DLQ.

2021-12-14 14:19 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.test.ts
> +    it('handles check_run events with no installation id.', async () => {
Since we control the data here, and it is typed. Would suggest not to improve this part in this PR

2021-12-14 14:21 UTC, npalm commented on examples/ephemeral/README.md
> +
Added

2021-12-14 14:21 UTC, ScottGuymer commented on modules/webhook/lambdas/webhook/src/webhook/handler.test.ts
> +    it('handles check_run events with no installation id.', async () => {
ok no problem

2021-12-14 14:23 UTC, ScottGuymer commented on examples/ephemeral/README.md
> +This example is essential based on the default setup. But shows how you can use runners with the ephemeral flag enabled. Once you enable ephemeral a runner will used once, only for one job. This requ
```suggestion
This example is based on the default setup. But shows how you can use runners with the ephemeral flag enabled. Once you enable ephemeral a runner will used once, only for one job. This requires that each job needs a fresh instance. To feature should be used in combination with event `workflow_job`, see your GitHub webhook endpoint configuration. We also suggest using the feature with a pre-build AMI, to optimize the creation time of a runner.
```

2021-12-14 14:24 UTC, ScottGuymer approved these changes
All look good now. 

Do you want me to test deploying this?

2021-12-14 14:36 UTC, npalm commented
> All look good now.
> 
> Do you want me to test deploying this?

Yes would be great when you can verify. Maybe smart to try the combination with a custom AMI

2021-12-14 14:37 UTC, ScottGuymer commented
That will take me some time to get up and running.

2021-12-14 15:18 UTC, mcaulifn requested changes

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      if (ephemeral) {
I must be missing something: Why is the error only thrown if `ephemeral`?

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/policies/instance-ec2.json
> +}
Needs a new line.

2021-12-14 15:18 UTC, mcaulifn commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +  logger.debug(`sending message to SQS: ${JSON.stringify(sqsMessage)}`);
Please add `, LogFields.print()`

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/lambda.ts
> +    logger.warn('Event ignored, only one record at the time can be handled, ensure the lambda batch size is set to 1.');
Please add `, LogFields.print()`

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/lambda.ts
> +          logger.warn(`Ignoring error: ${e.message}`);
Please add `, LogFields.print()`

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/lambda.ts
> +        logger.error(e);
Please add `, LogFields.print()`

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +  logger.info(`Received ${payload.eventType} from ${payload.repositoryOwner}/${payload.repositoryName}`);
Please add `, LogFields.print()`

2021-12-14 15:18 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +    logger.warn(`${payload.eventType} event is not supported in combination with ephemeral runners.`);
Please add `, LogFields.print()`

2021-12-14 15:26 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      if (ephemeral) {
The error is caused due to an issue with scaling. Reached max number of runners, or nog spot available. Since each event for ephemeral needs a runner we throw an exception. Messages goes back to the queue and will be retried later. For non ephemeral an existing runner will be used most likely. That is the same behaviour we have right now. Does this explanation help @mcaulifn

2021-12-14 15:26 UTC, npalm commented on modules/runners/lambdas/runners/src/lambda.ts
> +          logger.warn(`Ignoring error: ${e.message}`);
Will do, merge was some hell for this PR

2021-12-14 15:28 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      const runnerArgs = `--token ${token} ${labelsArgument}${ephemeralArgument}`;
Should be covered by unit tests, created also an issue to refactor this part

2021-12-14 15:29 UTC, npalm commented on modules/runners/lambdas/runners/src/lambda.ts
> +  return new Promise((resolve, reject) => {
A async lambda should return a Promise not a callback. Will check if a try / catch is needed

2021-12-14 15:37 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/lambda.ts
> +  return new Promise((resolve, reject) => {
[This](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html) is what I was just looking at. 
> For libraries that return a promise, you can return that promise directly to the runtime.

Since `scaleUp` returns a promise, that should suffice?

2021-12-14 16:09 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/lambda.ts
> +  return new Promise((resolve, reject) => {
It should be enough as long as you have an `await` for any async calls to other functions.

If you forget to await something async you can get wierdness.

2021-12-15 12:36 UTC, ScottGuymer commented
@npalm tested the deployment of ephemeral example config. works great so far

2021-12-22 10:17 UTC, ScottGuymer approved these changes
Looks good!

2021-12-22 10:41 UTC, ScottGuymer approved these changes

2021-12-22 10:41 UTC, npalm commented
@ScottGuymer PR is ready for final review. 

Tested:

- [ ] example ephemeral runners
- [ ] example default on branch develop with migration to this branch

2021-12-22 10:45 UTC, merged