fix(logging): Add context to webhook logs
philips-labs/terraform-aws-github-runner pull request #1401
Opened 2021-11-09 16:26 UTC by mcaulifn

- Move metadata to JSON object for more structured logging
- Add additional detail to logs
- Use supportedEvents list to quickly exit if not supported

Closes #1369

2021-11-10 08:10 UTC, npalm requested changes
No time to test yet

2021-11-10 08:10 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +  if (payload[githubEvent].completed_at) {
Could you not replace the if statement by a single line like ```LogFields.fields.completed_at = payload[githubEvent]?.completed_at;```?

2021-11-10 13:24 UTC, mcaulifn commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    logger.error(LogFields.fields, `Unsupported event type.`);
Changed

2021-11-10 21:34 UTC, npalm reviewed
LGTM, will try to run a quick test tomorrow

2021-11-18 10:18 UTC, npalm submitted a review, later dismissed

2021-11-18 11:12 UTC, npalm requested changes
@mcaulifn change is in general fine to me. But would suggest to add the logfields to the end of the line. This to keep the logs also readable. See details on review comment

2021-11-18 11:12 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    logger.error(LogFields.fields, `Received event from unauthorized repository ${payload.repository.full_name}`);
I think by a small change we can keep the log much cleaner and also readable. 

So would suggest to add an function to `logger.ts`
```TypeScript
  public static print(): string {
    return ' LogFields: ' + JSON.stringify(LogFields.fields);
  }
 ```
And next add the logfiels at the end of the line, for example 

```suggestion
    logger.error(`Received event from unauthorized repository ${payload.repository.full_name}. `, LogFields.fields);
```

2021-11-18 22:24 UTC, npalm approved these changes
LGTM

2021-12-01 15:59 UTC, merged