Provide hooks for using alternate runner os
philips-labs/terraform-aws-github-runner pull request #142
Opened 2020-08-17 10:00 UTC by sjagoe

### Description of the Change

At Smartly.io, we want to use runners that largely reflect the hosted Ubuntu runners provided by Github, running on larger instances in AWS. We build internal AMIs based on similar packer configuration to https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json (and use some of the provisioning scripts from that repository).

This PR exposes the interfaces necessary to hook those custom AMIs into the terraform module, while maintaining the previous default behaviour of using Amazon linux images.

Example use:

```
module "github-runner" {
  # Using a local copy of the module
  source  = "./modules/github-runner"

  # ... All the usual configuration

  # Use custom AMI and user-data.sh template for bootstrapping
  userdata_template = "./templates/user-data.sh"
  ami_owners = ["self"]
  ami_filter = {
    name = ["myorg/github-actions-runner/ubuntu-18.04-*"]
  }

  # The device name here is required due to differences between Canonical ubuntu images and Amazon Linux
  block_device_mappings = {
    device_name = "/dev/sda1"
    # Use larger disks for more sustained IOPS
    volume_size = "500"
  }
}

```

### Alternate Designs

N/A This approach was taken to minimize the extent of changes to the terraform module

### Possible Drawbacks

### Verification Process

- The changes from this PR have been running live for at least a week
- A `terraform plan` without using the new variables outputs the expected changes to the infrastructure

### Release Notes

- feat: Expose ami-filters and user-data template file location to users to allow use of custom AMIs

2020-08-18 20:39 UTC, npalm commented
Thank you for the PR, did a quick check and have some ideas and remarks

1. Install the runner
You have to provide the user data to install the runner your self, which leads to duplication, but gives more flexibility. We could als introduce a small submodule ust to install the runner, in that case you could re-use a common part. 

2. Could you extend the example directoy with an ubuntu example? So we have a possibility to check the contribution easy.

3. There is another PR on support other AMI
Please can you also have a look at https://github.com/philips-labs/terraform-aws-github-runner/pull/83 seems the same approach. But the PR is not finished, also in that PR we miss an example

2020-08-20 12:45 UTC, sjagoe commented
> Install the runner

Yes, my custom user-data started out by butchering your template until I just had the runner setup. I'll think about a solution to that.

> Could you extend the example directoy with an ubuntu example

I completely missed that; I will create an example.

The approach in #83 does look quite similar. Maybe there are some ideas I can update this with as well.

2020-08-26 06:22 UTC, nomeelnoj commented on main.tf
> +  ami_filter        = local.ami_filters_exist ? var.ami_filter : local.runner_architecture == "arm64" ? { name = ["amzn2-ami-hvm-2*-arm64-gp2"] } : { name = ["amzn2-ami-hvm-2.*-x86_64-ebs"] }
why not combine these into 1?
```suggestion
  ami_filter        = length(var.ami_filter) > 0 ? var.ami_filter : local.runner_architecture == "arm64" ? { name = ["amzn2-ami-hvm-2*-arm64-gp2"] } : { name = ["amzn2-ami-hvm-2.*-x86_64-ebs"] }
```

2020-09-01 06:17 UTC, sjagoe commented
I haven't forgotten about this PR, I just haven't had a chance to pick it up again yet. I'll try to get it updated soon.

2020-09-14 18:54 UTC, npalm commented
@sjagoe did you already time to create an example, would like to try out the suggested change.

2020-09-14 18:58 UTC, sjagoe commented
Apologies for the delay. I'll create an example tomorrow, even if I don't get to the other changes yet

2020-09-14 19:14 UTC, npalm commented
No worries, thx for the fast response

2020-09-15 11:21 UTC, sjagoe commented
@npalm I've added a basic example; it's largely a copy of the `default` example, with a couple added segments for ubuntu usage.

I apologize upfront that I have not fully tested this example, as we deploy our runners from custom images with a lot more pre-installed (built using packer.io).

This *should* have enough to get a runner connected to github, though.

2020-09-26 04:03 UTC, rbellamy commented
To me, it looks like the `service_user` value is still going to be set to `ec2-user`?
https://github.com/philips-labs/terraform-aws-github-runner/blob/c7902c5b2a99ca0f5e5e9828234d7beaed2c94ff/modules/runners/main.tf#L82

2020-09-26 04:14 UTC, rbellamy commented
Looks like that's a variable that could be deprecated since it's used intermittently in the `user-data.sh` script.

2020-10-05 20:28 UTC, npalm commented
Looks like the user ignored for ubuntu and the service is always running as root. I will check the and test the PR this week. Sorry for the delay.

2020-10-08 19:43 UTC, npalm requested changes
Looks al good, a few suggestions. I have teste the ubuntu example as well.

2020-10-08 19:43 UTC, npalm commented on examples/ubuntu/main.tf
> +  environment = "default"
```suggestion
  environment = "ubuntu"
```

2020-10-08 19:43 UTC, npalm commented on examples/ubuntu/main.tf
> +  # runners_lambda_zip                = "lambdas-download/runners.zip"
```suggestion
  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"
```
Use downloaded lambda's as mentioned in the readme instead of locally build

2020-10-08 19:43 UTC, npalm commented on modules/runners/variables.tf
> +  description = "Alternative user-data template, replacing the default template"
```suggestion
  description = "Alternative user-data template, replacing the default template, by providiing your own user_data you have to take care of installing all required software including the action runner. Variables userdata_pre/post_instal are ignored."
```

2020-10-08 19:43 UTC, npalm commented on variables.tf
> +  description = "Alternative user-data template, replacing the default template"
```suggestion
  description = "Alternative user-data template, replacing the default template, by providiing your own user_data you have to take care of installing all required software including the action runner. Variables userdata_pre/post_instal are ignored."
```

2020-10-08 19:43 UTC, npalm commented on variables.tf
> +  description = "List of maps used to create the AMI filter for the action runner AMI."
```suggestion
  description = "List of maps used to create the AMI filter for the action runner AMI. By default amazon linux 2 is used."
```

2020-10-12 12:34 UTC, bendavies commented
@sjagoe any time to get this over the line? we'll use it!

2020-10-12 13:09 UTC, sjagoe commented
I'll follow up on the review comments this week.

2020-10-20 08:52 UTC, npalm commented
@sjagoe thx will check asap

2020-10-20 12:33 UTC, npalm approved these changes
@sjagoe thanks for all the work, all good!

2020-10-20 12:34 UTC, merged

2020-10-20 12:35 UTC, sjagoe commented
Thanks @npalm. Good to see it go in. Sorry it took so long for me to deal with it.

2020-10-20 21:25 UTC, bendavies commented
Thanks @sjagoe !
@npalm can we have a release? thanks!

2020-10-20 21:25 UTC, bendavies commented on examples/ubuntu/lambdas-download/main.tf
> +      tag  = "v0.5.0"
these should reference the latest version i guess

2020-10-20 21:26 UTC, npalm commented on examples/ubuntu/lambdas-download/main.tf
> +      tag  = "v0.5.0"
Good catch, will fix is asap or feel free to create a PR.