Default to not attching AmazonSSMManagedInstanceCore to instances
philips-labs/terraform-aws-github-runner pull request #143
Opened 2020-08-17 19:38 UTC by HenryNguyen5

2020-08-18 20:03 UTC, npalm requested changes

2020-08-18 20:03 UTC, npalm commented on README.md
> +| debug\_instances | Enable to allow access the runner instances for debugging purposes via SSM. Note that this adds additional permissions to the runner instances. | `bool` | `false` | no |
I would prefer a variable like `enable_ssm_on_runners`. Please could you rename?

2020-08-19 05:30 UTC, npalm requested changes
@HenryNguyen5 please check the build, terraform format is failing. The repo has configured https://pre-commit.com/ run terraform format on commint and update the variables in the readme.

2020-08-19 15:32 UTC, HenryNguyen5 commented
@npalm should be good now!

2020-08-19 16:59 UTC, HenryNguyen5 commented
Rebased

2020-08-24 17:39 UTC, HenryNguyen5 commented
@npalm anything I should do to push this along?

2020-08-25 06:28 UTC, npalm approved these changes

2020-08-25 06:28 UTC, npalm commented
> @npalm anything I should do to push this along?

Thank, looks all good. We will merge asap

2020-08-25 16:31 UTC, merged