Prebuilt runner image using packer
philips-labs/terraform-aws-github-runner pull request #1444
Opened 2021-11-25 13:22 UTC by ScottGuymer

When looking at using ephemeral runners it becomes clear that startup time for the agents becomes a key factor in build times.

To enable us to shorten the startup times as much as possible we should build an image that has all the dependencies and the runner installed. In this way there is much less work to do when starting the runner.

To do this I have used packer to build an image that can be used for the runners.

This requires a few changes to how the current scripting is done. We need to refactor this into two phases
- installation
- startup

Installation
This is all the work that can be done before the runner starts, so installing dependencies or configuring generic settings

Startup
These are the things that can only happen when you are booting an instance of an agent. Such as collecting the GH token to connect the runner or configuring CloudWatch.

2021-11-27 15:03 UTC, ScottGuymer commented
So a few things i have started to do here

- build the image using packer with the current amzn2 image as a base
- refactored the install script to pull the runner directly from a URL (removing the need for the s3 bucket at runtime)
- Added a `startup.sh` script to `/var/lib/cloud/scripts/per-boot/` so it will run at each boot. This does the following
    - Gets the instance meta data required (but now uses tags for some non secret info like environment)
    - Gets the GH API token from SSM
    - Optionally configures cloudwatch based on tag setting
    - configures the runner
    - starts the runner and waits for it to exit (this could be made switchable to make it a long lived runner)
    - Terminates the instance when the runner exists (mostly for ephemeral workloads)
 - Given the instance rights to read tags in IAM to be able to pass config in an simple and extensible way.
 - Added a simple CI validation job to check the format and validate

Whats left to decide/do?
- [ ] How many/where are we happy with breaking changes to create simplicity?
- [ ] Do we allow both image based and startup script based config?
- [ ] Do we build this image in CI? 
- [ ] Do we make this ami public and the default image to use instead of the on demand config?
- [ ] How do we deal with the pre_install hook? 
- [ ] Do we add the post_install hook to the startup so it can run something before the agent starts?
- [ ] Do we use user_data as a point of customisation for the image on start?
- [ ] How do we handle the arm_patch functionality, should this just be bake into arm images?

2021-12-01 10:22 UTC, ScottGuymer commented on main.tf
> +    "ghr:environment" = format("%s", var.environment)
I added this as an additional top level tag so we can start to move to namespaced tags and address issues like #1280 #1346 

We can then slowly start to move references to `Environment` over to `ghr:environment` which is less likely to cause clashes with org policies.

2021-12-01 10:23 UTC, ScottGuymer commented on modules/runners/logging.tf
> +  count = var.enable_cloudwatch_agent ? 1 : 0
This is a buigfix.

If you previously set `var.enable_cloudwatch_agent=false` and `var.enable_ssm_on_runners=true` then it caused an error on this resource.

2021-12-01 10:24 UTC, ScottGuymer commented on modules/runners/main.tf
> -      "Environment" = format("%s", var.environment)
This is already specified in the top level module and passed in here

2021-12-01 10:26 UTC, ScottGuymer commented on modules/runners/policies-runner.tf
> +      arn_ssm_parameters = jsonencode([
This now passes a list into the policy json rather than a single line. This is to enable path based access to SSM Parameters

2021-12-01 10:29 UTC, ScottGuymer commented on modules/runners/policies/instance-describe-tags-policy.json
> +{
Although `ec2:DescribeTags` is in the `instance-cloudwatch-policy.json` it is only deployed if CloudWatch is turned on.

As we access the tags in the startup to get the `ghr:environment` tag we now always need access to read the tags.

2021-12-01 10:32 UTC, ScottGuymer commented on modules/runners/policies-runner.tf
> +      arn_ssm_parameters = jsonencode([
changed this to specific values so we can split read and delete and be more specific on the delete.

2021-12-01 10:40 UTC, ScottGuymer commented on modules/runners/runner-config.tf
> +resource "aws_ssm_parameter" "runner_agent_mode" {
Added this in here in preparation for allowing ephemeral runner config

2021-12-01 10:42 UTC, ScottGuymer commented on modules/runners/variables.tf
> +    {
The pre build image now places logs here when running the startup and we want it scooped up into cloudwatch.

2021-12-01 10:42 UTC, ScottGuymer commented
@npalm this is ready for review now.

2021-12-02 12:34 UTC, npalm requested changes
@ScottGuymer great work! Some minor comments.

Did you also create instructions how to setup (an automated) AMI builder? Will test the PR asap

2021-12-02 12:34 UTC, npalm commented on .github/workflows/packer-build.yml
> +    name: Verify image
```suggestion
    name: Verify packer    
```

2021-12-02 12:34 UTC, npalm commented on images/linux-amzn2/github_agent.linux.pkr.hcl
> +  name = "githubactions-runner"
Maybe an idea to make this conigurable

2021-12-02 12:34 UTC, npalm commented on modules/runners/policies/instance-describe-tags-policy.json
> +}
I think you can apply this condition to only let the instance access its own tags:

```
            "Condition": {
                "StringEquals": {
                    "aws:ARN": "${ec2:SourceInstanceARN}"
                }
            }
```

2021-12-02 12:34 UTC, npalm commented on modules/runners/templates/install-runner.sh
> +  echo "Retrieving TOKEN from AWS API"
Seem we are not using the token here at all

2021-12-02 13:26 UTC, ScottGuymer commented on modules/runners/policies/instance-describe-tags-policy.json
> +}
Looks like the 2021 version of this is

```
"Condition": {
  "ArnEquals": {
    "aws:SourceArn": "${ec2:SourceInstanceARN}"
  }
}
```

2021-12-02 13:29 UTC, ScottGuymer commented on modules/runners/templates/install-runner.sh
> +  echo "Retrieving TOKEN from AWS API"
Its used in the curl on line 26 to get the region

2021-12-02 13:35 UTC, ScottGuymer commented on images/linux-amzn2/github_agent.linux.pkr.hcl
> +  name = "githubactions-runner"
Its not possible to make this variable. Its only used for logging and naming the instance used for building. It doesn't have a bearing on the end result image.

2021-12-02 14:44 UTC, npalm commented on modules/runners/policies/instance-describe-tags-policy.json
> +}
Just testen, the one with `aws:ARN` is working the one with `aws:SourceArn` not

2021-12-02 20:51 UTC, npalm requested changes
Tested the setup

- [ ] deploy default -> migrate to PR 1440
- [ ] uprade previous step to custom AMI failed

The instance is booting but some errors during loading, zee below

```
Configuration validation first phase succeeded
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -schematest -config /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
Configuration validation second phase succeeded
Configuration validation succeeded
Redirecting to /bin/systemctl stop amazon-cloudwatch-agent.service
Redirecting to /bin/systemctl restart amazon-cloudwatch-agent.service
Get GH Runner token from AWS SSM
Delete GH Runner token from AWS SSM

An error occurred (ParameterNotFound) when calling the DeleteParameter operation:
```

I see the launch templates still contains the userdate to install the runner.

2021-12-02 20:51 UTC, npalm commented on examples/prebuilt/main.tf
> +  ami_owners       = [var.ami_owner]
You can retrieve the account id as follow

```hcl
data "aws_caller_identity" "current" {}

# usages
ami_owner = aws_caller_identity.current.account_id
```

2021-12-02 20:51 UTC, npalm commented on examples/prebuilt/main.tf
> +  delay_webhook_event = 0
Would not suggest to set the default to 0 for the check_run event and non ephmeral runners. You simple will create too many runners.

2021-12-02 20:51 UTC, npalm commented on main.tf
> +  userdata_enabled      = var.userdata_enabled
Would it be an ideaa to set the enabled via a condition?
```
userdata_enabled = userdata_template != "" ? true : false
```

2021-12-02 20:51 UTC, npalm commented on images/linux-amzn2/github_agent.linux.pkr.hcl
> +  ami_name      = "github-runner-amzn2-${formatdate("YYYYMMDDhhmm", timestamp())}"
Maybe also use arch type in the name

2021-12-02 21:11 UTC, npalm commented
> Tested the setup
> 
> * [x]  deploy default -> migrate to PR 1440
> * [ ]  upgrade previous step to custom AMI failed (on user-data)
> 
> The instance is booting but some errors during loading, in user_data
> 
> ```
> Configuration validation first phase succeeded
> /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -schematest -config /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
> Configuration validation second phase succeeded
> Configuration validation succeeded
> Redirecting to /bin/systemctl stop amazon-cloudwatch-agent.service
> Redirecting to /bin/systemctl restart amazon-cloudwatch-agent.service
> Get GH Runner token from AWS SSM
> Delete GH Runner token from AWS SSM
> 
> An error occurred (ParameterNotFound) when calling the DeleteParameter operation:
> ```
> 
> I see the launch templates still contains the userdate to install the runner. After a few minutes all my tests jobs succeeded.

Problem seems caused by I did not disabled the userdata via
```
userdata_enabled = false
```
So would suggest also mention this explicit in the readme of the images

2021-12-02 21:26 UTC, npalm commented on modules/runners/variables.tf
> +      "log_group_name" : "runner-startup",
You should add the new log_file to the end of het list, to avoid conflicts in an upgrade

2021-12-03 08:37 UTC, ScottGuymer commented on modules/runners/policies/instance-describe-tags-policy.json
> +}
As discussed the above appears to work with some permissions and not others. @npalm tested with terminate instance permissions. 

I tested this condition with describe tags and found it to have no effect on my ability to query tags of other instances.

2021-12-03 08:38 UTC, ScottGuymer commented on modules/runners/policies/instance-describe-tags-policy.json
> +}
Verdict is to remove this for the describe tags policy as it has no effect.

2021-12-03 08:44 UTC, ScottGuymer commented on examples/prebuilt/main.tf
> +  ami_owners       = [var.ami_owner]
fixed.

2021-12-03 08:54 UTC, ScottGuymer commented on main.tf
> +  userdata_enabled      = var.userdata_enabled
I don't think this is possible without a breaking change.

Currently if this value is not set then the default userdata is used. 
If it is set then we try to load the template from the location in this value. If you specify an empty string it fails to load the file and errors
I could update the logic to distinguish between 
- null (which means use default userdata) 
- empty string (which means don't use userdata at all) 
- value (assume this is a file and try to load it)

But I'm not sure that using the difference between empty string and null as a trigger for this is clear enough..

WDYT?

2021-12-03 08:55 UTC, ScottGuymer commented on examples/prebuilt/main.tf
> +  delay_webhook_event = 0
set to 5

2021-12-03 08:57 UTC, ScottGuymer commented on images/linux-amzn2/github_agent.linux.pkr.hcl
> +  ami_name      = "github-runner-amzn2-${formatdate("YYYYMMDDhhmm", timestamp())}"
added

2021-12-03 09:03 UTC, ScottGuymer commented on modules/runners/variables.tf
> +      "log_group_name" : "runner-startup",
Done..

Not sure i like it being in both places. I think this is a TF limitation though. Will test removing and setting outer value to null.

2021-12-03 14:51 UTC, ScottGuymer commented on main.tf
> +  userdata_enabled      = var.userdata_enabled
As discussed it makes sense to keep the explicit `userdata_enabled` to turn this on and of..

In addition i have renamed it to `enabled_userdata`

2021-12-03 14:54 UTC, ScottGuymer commented on modules/runners/variables.tf
> +      "log_group_name" : "runner-startup",
Tested this and it simply passes `null` from the wrapper module into the sub-module, The submodule then uses `null` as the value and ignores the default. 

Which makes sense even if it might not be what is wanted.

It would be nice if there was some option to "default on null" or rather than just when not specified.

2021-12-03 14:55 UTC, npalm approved these changes
Tested, all good!

2021-12-03 14:56 UTC, merged