Feat/windows support
philips-labs/terraform-aws-github-runner pull request #1476
Opened 2021-12-02 13:16 UTC by ScottGuymer

Merge the code that @RichiCoder1 created for windows runners into the develop branch so it can be released.

Beyond integrating this with the current develop I have made some minor changes.

Still need to update the docs etc.

2021-12-02 16:42 UTC, ScottGuymer commented on main.tf
> -  ami_filter = length(var.ami_filter) > 0 ? var.ami_filter : local.runner_architecture == "arm64" ? { name = ["amzn2-ami-hvm-2*-arm64-gp2"] } : { name = ["amzn2-ami-hvm-2.*-x86_64-ebs"] }
This is now quite complex logic so and was duplicated in `/modules/runner/main.tf` so i have removed it from here and just kept this logic in the runner module

2021-12-02 16:54 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  default     = null
Now null so we can calculate values based on the OS later

2021-12-08 11:38 UTC, ScottGuymer commented on modules/runners/scale-down.tf
> +      MINIMUM_RUNNING_TIME_IN_MINUTES      = coalesce(var.minimum_running_time_in_minutes, local.min_runtime_defaults[var.runner_os])
The default minimum time needs to be longer for windows as it takes a lot longer to boot.

2021-12-08 11:40 UTC, ScottGuymer commented on modules/runners/templates/start-runner.sh
> +echo "Get GH Runner config from AWS SSM"
just some tidy up to make the logs consistent between win/linux

2021-12-08 12:05 UTC, ScottGuymer commented on modules/runners/templates/start-runner.ps1
> +Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name ConsentPromptBehaviorAdmin -Value 0 -Force
I'm not sure if this is strictly needed, but it already existed and I haven't tested without it,

2021-12-08 12:11 UTC, ScottGuymer commented
@npalm  @RichiCoder1 this is ready for a review now!

2021-12-08 21:10 UTC, npalm requested changes
Looks good to me, a few comments

2021-12-08 21:10 UTC, npalm commented on modules/runners/variables.tf
>    description = "The time an ec2 action runner should be running at minimum before terminated if non busy."
```suggestion
  description = "The time an ec2 action runner should be running at minimum before terminated if non busy. If not set the default is calculated based on the OS."
```

2021-12-08 21:10 UTC, npalm commented on modules/runners/templates/start-runner.ps1
> +Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name ConsentPromptBehaviorAdmin -Value 0 -Force
Suggest to make an issue and refer here to the issue

2021-12-08 21:10 UTC, npalm commented on modules/runners/variables.tf
> +  default     = null
Should we not add what more detail, for example for linux we use amazon linux

2021-12-08 21:35 UTC, npalm commented
Tested windows. Works all fine, but find another weird problem. My events got declined by the lambda with a 401. Seems that secrets in github are limited. Their own example shows an hex generated value. Can you update the examples as follow 

```hcl
resource "random_id" "random" {
  byte_length = 16
}
```

Next update ref and the output tf.

2021-12-08 21:36 UTC, npalm commented
Tesated

- [ ] linux (default)
- [ ] windows

2021-12-09 12:08 UTC, ScottGuymer commented
> Tested windows. Works all fine, but find another weird problem. My events got declined by the lambda with a 401. Seems that secrets in github are limited. Their own example shows an hex generated value. Can you update the examples as follow
> 
> ```terraform
> resource "random_id" "random" {
>   byte_length = 16
> }
> ```
> 
> Next update ref and the output tf.

This may well have been the issue i was seeing the other day. I was seeing the same 401 issues. I tainted the secret and then it worked.

2021-12-09 12:15 UTC, npalm commented
> > Tested windows. Works all fine, but find another weird problem. My events got declined by the lambda with a 401. Seems that secrets in github are limited. Their own example shows an hex generated value. Can you update the examples as follow
> > ```terraform
> > resource "random_id" "random" {
> >   byte_length = 16
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Next update ref and the output tf.
> 
> This may well have been the issue i was seeing the other day. I was seeing the same 401 issues. I tainted the secret and then it worked.

No specification, but this example I found on github https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#setting-your-secret-token

2021-12-09 12:25 UTC, ScottGuymer commented
Yeah, I can't seem to find a spec either. But all the examples show the secret converted to hex rather than just a plain string. 

Terraform doesn't seem to have a native string to hex conversion function (it does have integer to hex via `format()`). I think `random_id` with the hex output is the best we are going to get.

2021-12-09 12:29 UTC, npalm commented
> Yeah, I can't seem to find a spec either. But all the examples show the secret converted to hex rather than just a plain string.
> 
> Terraform doesn't seem to have a native string to hex conversion function (it does have integer to hex via `format()`). I think `random_id` with the hex output is the best we are going to get.

Maybe set the byte length a bit longer

2021-12-09 12:34 UTC, ScottGuymer commented on examples/windows/README.md
> +Steps for the full setup, such as creating a GitHub app can be found in the root module's [README](../../README.md). First, download the Lambda releases from GitHub. Alternatively you can build the l
I have set it to `false` to match the other examples.

2021-12-09 12:40 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  default     = null
I have added some hints on the defaults

2021-12-09 12:40 UTC, ScottGuymer commented on modules/runners/templates/start-runner.ps1
> +Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name ConsentPromptBehaviorAdmin -Value 0 -Force
done and adde dlink

2021-12-09 14:06 UTC, npalm approved these changes

2021-12-09 14:22 UTC, merged

2021-12-09 15:00 UTC, ScottGuymer commented
🎉

2021-12-09 22:02 UTC, RichiCoder1 commented
🥳