feat: creating instances via the fleet API
philips-labs/terraform-aws-github-runner pull request #1556
Opened 2021-12-23 15:06 UTC by npalm

## Description

As suggested in #1400 it is a best practice to use the fleet API for creating instances. This PR will replace the way we create instances by using the create fleet API instead of run instances. This also allows to fall back to on-demand when spot is not available.

2021-12-23 15:13 UTC, npalm commented
@ruecarlo would you have a bit of time to check the API call for create fleet? Which options should we set to cover scenarios like:
- only spot
- only on-demand
- spot prefered, on-demand as fall back

2021-12-31 09:13 UTC, npalm commented
No clue why the diff is showing the moved files as new files

```
 rename modules/runners/lambdas/runners/src/{scale-runners => aws}/runners.test.ts (99%)
 rename modules/runners/lambdas/runners/src/{scale-runners => aws}/runners.ts (98%)
 rename modules/runners/lambdas/runners/src/{scale-runners => aws}/ssm.test.ts (100%)
 rename modules/runners/lambdas/runners/src/{scale-runners => aws}/ssm.ts (100%)
 rename modules/runners/lambdas/runners/src/{scale-runners => gh-auth}/gh-auth.test.ts (98%)
 rename modules/runners/lambdas/runners/src/{scale-runners => gh-auth}/gh-auth.ts (95%)
 rename modules/runners/lambdas/runners/src/{scale-runners => }/logger.ts (100%)
 rename modules/runners/lambdas/runners/src/{scale-runners => }/modules.d.ts (100%)
```

2022-01-03 09:33 UTC, ScottGuymer requested changes
This is looking a lot neater and less complex

2022-01-03 09:33 UTC, ScottGuymer commented on README.md
> +- Spot vs on-demand. The runners using either the EC2 spot or on-demand life cycle. Runners will be created via the AWC [CreateFLeet API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Cr
```suggestion
- Spot vs on-demand. The runners using either the EC2 spot or on-demand life cycle. Runners will be created via the AWS [CreateFleet API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateFleet.html). The module (scale up lambda) will request an instance via the create fleet API in one of the subnets and matching one of the specified instance types.
```

2022-01-03 09:33 UTC, ScottGuymer commented on README.md
> +When using the top level module configure `runner_architecture = arm64` and insure the list of `instance_types` matches. When not using the top-level ensure the bot properties are set on the submodul
```suggestion
When using the top-level module configure `runner_architecture = arm64` and ensure the list of `instance_types` matches. When not using the top-level ensure the bot properties are set on the submodules. 
```

2022-01-03 09:33 UTC, ScottGuymer commented on main.tf
> -  runner_architecture  = substr(var.instance_type, 0, 2) == "a1" || substr(var.instance_type, 0, 3) == "t4g" || substr(var.instance_type, 1, 2) == "6g" ? "arm64" : "x64"
I like that we are removing the complexity here.

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/aws/runners.ts
> +      throw Error('Create flee failed, no instance created.');
```suggestion
      throw Error('Create fleet failed, no instance created.');
```

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/aws/runners.ts
> +      throw new ScaleError('Failed to create instance, create fleet failed.');
So this will toss it back on the queue to be retried?

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/gh-auth/gh-auth.ts
> +  return auth(appAuthOptions);
I'm guessing the promise returned here is now awaited by the caller?

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/scale-up.tf
> +      INSTANCE_TARGET_CAPACITY_TYPE        = var.instance_targeet_capacity_type
```suggestion
      INSTANCE_TARGET_CAPACITY_TYPE        = var.instance_target_capacity_type
```

This will likely cause issues elsewhere.

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/variables.tf
> +variable "instance_targeet_capacity_type" {
```suggestion
variable "instance_target_capacity_type" {
```

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/variables.tf
> +    condition = anytrue([
You can simplify this validation like this 

```
  validation {
    condition     = contains(["lowest-price", "diversified", "etc"], var.instance_allocation_strategy)
    error_message = "The instance allocation strategy does not match the allowed values."
  }
```

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/variables.tf
> +    error_message = "The instance allocation strategy does not matched the allowed values."
```suggestion
    error_message = "The instance allocation strategy does not match the allowed values."
```

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  description = "Max price price for spot intances per hour. This variable will be passed to the create fleet as max spot price for the fleet."
What happens with the default `null`? is no max specified then?

2022-01-03 09:33 UTC, ScottGuymer commented on variables.tf
> +    condition = anytrue([
Same as above this can be simplified with `contains`

2022-01-03 09:33 UTC, ScottGuymer commented on variables.tf
> +  description = "Default lifecyle used runner instances, can be either `spot` or `on-demand`."
```suggestion
  description = "Default lifecycle used for runner instances, can be either `spot` or `on-demand`."
```

2022-01-03 09:33 UTC, ScottGuymer commented on variables.tf
> +    condition = anytrue([
This can be simplified with `contains`

2022-01-03 09:33 UTC, ScottGuymer commented on variables.tf
>    description = "List of instance types for the action runner. Defaults are based on runner_os (amzn2 for linux and Windows Server Core for win)."
I dont think the description here makes sense. Maybe a previous copy paste issue..

2022-01-03 09:33 UTC, ScottGuymer commented on variables.tf
> +    condition = anytrue([
This can be simplified with `contains`

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/variables.tf
> +    condition = anytrue([
This can be simplified with `contains`

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +      await createRunners(
This is so much simpler 🎉

2022-01-03 09:33 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +  if (payload.eventType === 'workflow_job') {
The `workflow_job` string is used a few times. Maybe extract it out into a const so that it is safer to use.

There are other strings here that could have the same treatment like `Org` and `check_run`

2022-01-03 12:35 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +  if (payload.eventType === 'workflow_job') {
Correct, but is used as a kind of enum. In type script it is called literal string types see https://www.typescriptlang.org/docs/handbook/literal-types.html

2022-01-03 12:46 UTC, npalm commented on modules/runners/variables.tf
> +  description = "Max price price for spot intances per hour. This variable will be passed to the create fleet as max spot price for the fleet."
Good catch, it works but it is unclear how null is handled. AWS docs https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotOptionsRequest.html does not give any details on the validtiy of the string. Will do some checks, and or make it stricter.

2022-01-03 12:49 UTC, ScottGuymer commented on modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> +  if (payload.eventType === 'workflow_job') {
ah ok cool

2022-01-03 13:06 UTC, npalm commented on modules/runners/lambdas/runners/src/aws/runners.ts
> +      throw new ScaleError('Failed to create instance, create fleet failed.');
Yes for ephemeral rnners only

2022-01-04 15:01 UTC, npalm commented
The PR is ready for review, however there are 2 topics we could got some extra help.

1. When sending a create fleet request with type instant. We handling a [list of specific errors](https://github.com/philips-labs/terraform-aws-github-runner/blob/51a0070e82a3d1989f856e04bff8963d5addc5f1/modules/runners/lambdas/runners/src/aws/runners.ts#L164).  For the errors in this list we think it make sense to retry later, since the casue is a rate limit, or limit in general. Are we missing errors, or are there errors that should not trigger a retry?
2. With te create fleet api we create typically 1 instance, either spot or on-emand. But we are wondering how we can ensure we got an instant if there is no spot capacity?

2022-01-05 08:37 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  description = "Max price price for spot intances per hour. This variable will be passed to the create fleet as max spot price for the fleet."
Did you uncover anything on how this is handled?

2022-01-05 08:37 UTC, ScottGuymer approved these changes
LGTM :shipit:

2022-01-05 15:56 UTC, merged