Update arm-runner-patch.tpl
philips-labs/terraform-aws-github-runner pull request #1624
Opened 2022-01-13 23:51 UTC by ndench

The runtimeconfig.json files seem to have changed on the latest Amazon Linux AMI.
When running the user data scripts, the patch of these files fails which causes initialization of the runner instance to fail.

I've run with the following patch template and the arm instance is now booting and seems to be accepting jobs. However they are not running and hang indefinitely. I'm unsure if there are any flow on changes required here?

My jobs all look like this:
![image](https://user-images.githubusercontent.com/2062388/149278521-e07214c9-a5fa-4f07-9c5d-e31c970912ca.png)

Closes: #1620

2022-01-14 09:55 UTC, ScottGuymer commented
I think we should move this patching into an example where we show how to do this by injecting a pre install hook into the user data.

2022-01-14 13:17 UTC, npalm commented
@ndench The short snippet of the log you added shows the created instance got connected and the agent have received the job. In the AWS webconsole you access the instance (once ssm configuration variable of module is enabled). Next you could check log files like `/var/log/user_data/` or the agent logs in the `_diag` folder of the runner.

2022-01-15 04:31 UTC, ndench commented
I've noticed the `runtimeconfig.json` files seem to be changing frequently which keeps breaking the patch. Turns out all we need to do is install `libicu60` which wasn't present in the repository when arm64 support was originally added. I've updated this PR to just install that package.

Additionally, as you can see from [this commit](https://github.com/philips-labs/terraform-aws-github-runner/pull/1624/commits/639c46e15b37935264842a360d55a1d1d8ad0051) I tested removing the arm patch entirely as has been suggested. I can then install the package using the existing `userdata_pre_install` variable:

```
  userdata_pre_install = <<EOF
sudo yum -y install libicu60
EOF
```

I'm happy to add that commit back in, and update the README to specify users need to install that package. However I prefer that the module handle installing that. It makes it much simpler from a users point of view. Plus it's not a flaky anymore when the config files change.

Let me know which approach is preferred.

2022-01-15 09:08 UTC, npalm commented
@ndench Thanks a lot for improving the support for ARM. Would you have a bit of time to add an example for ARM? It will help other a lot that would use the module with ARM support!

2022-01-16 02:23 UTC, ndench commented
No problem @npalm, I updated the README and added an example for arm64 instances.

2022-01-17 08:55 UTC, brainlock commented
We're also using this for the occasional ARM runner, and just ran into the same problem. If it helps, I tested this PR, works great. Thank you @ndench!

2022-01-17 16:36 UTC, ScottGuymer commented on modules/runners/templates/arm-runner-patch.tpl
> +sudo yum -y install libicu60
If this is all that is now needed maybe we can just add it as a conditional statement in the user-data.sh file rather than having to include this file.

2022-01-17 17:04 UTC, npalm commented on modules/runners/templates/arm-runner-patch.tpl
> +sudo yum -y install libicu60
Agree, but still it make sense to have an example.

2022-01-18 02:09 UTC, ndench commented
@ScottGuymer @npalm no problem, updated it to remove `arm-runner-patch.tpl` entirely. Tested on my infrastructure and it works a treat.

2022-01-18 08:49 UTC, ScottGuymer approved these changes
LGTM.

If extra things are needed in the future they can always be added by the pre or post userdata hooks.

2022-01-18 17:36 UTC, npalm requested changes
@ndench thanks great work!. Tested and all worked. 
![image](https://user-images.githubusercontent.com/11609620/149988824-9f577df1-4246-4c85-b153-602a2b887cdb.png)

Only one small request. Can you update the ci workflow file `.github/workflows/terraform.yml` and add the `arm` example dir to the matrix of the job `verify_examples` See https://github.com/hyraiq/terraform-aws-github-runner/blob/519f130ec9fd36a6e327857809256178ca1aa4ba/.github/workflows/terraform.yml#L46

2022-01-18 22:17 UTC, ndench commented
No problem @npalm, I also noticed that the ephemeral and windows examples were missing from the github workflow, so I added them while I was there.

2022-01-18 22:27 UTC, npalm commented
@ndench thanks for adding the other examples as well

2022-01-18 22:27 UTC, npalm approved these changes

2022-01-18 22:27 UTC, merged