feat: output image id used in launch template
philips-labs/terraform-aws-github-runner pull request #1676
Opened 2022-01-28 17:47 UTC by toast-gear

2022-01-28 21:18 UTC, npalm requested changes
Thanks, can you also add a small description to the PR?

2022-01-28 21:18 UTC, npalm commented on modules/runners/outputs.tf
> +output "image_id" {
Looks no reason to output, can you remove this aoput. Used image_id is part of the launch templates whic is already outputed

2022-01-29 08:28 UTC, toast-gear commented on modules/runners/outputs.tf
> +output "image_id" {
We output the launch template but the launch template doesn't expose anything of its settings so we need to output them as well if we want them exposed? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#attributes-reference Apologies if it does, I'm somewhat new to Terraform still.

2022-02-01 08:16 UTC, npalm requested changes

2022-02-01 08:16 UTC, npalm commented on modules/runners/outputs.tf
> +output "image_id" {
No there is no need to output the image_id in this way, it is already outputted as part of the object launch_template., see https://github.com/philips-labs/terraform-aws-github-runner/blob/db4fc4b7caafe36c633f7fcfcbd2257e424dbb39/modules/runners/outputs.tf#L1

2022-02-01 08:16 UTC, npalm commented on outputs.tf
> +    launch_template_image_id = module.runners.image_id
```suggestion
    launch_template_image_id = module.runners.launch_template.image_id
```

2022-02-03 17:56 UTC, toast-gear commented on outputs.tf
> +    launch_template_image_id = module.runners.image_id
For my benefit how can I tell what is already output? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#attributes-reference I thought it was a case of looking at the attribute references for a given resource? So in this case `launch_template.id` and `launch_template.latest_version` are both documented attribute references, how can I tell `image_id` is one without just trying it?

2022-02-04 07:12 UTC, npalm commented on outputs.tf
> +    launch_template_image_id = module.runners.image_id
Don't have a solid answer. One thing you can do is check state. But agree it is not always very clear what is exported.

2022-02-04 21:59 UTC, toast-gear commented
- removed output from runner module
- added image_id output as suggested
- removed `launch_template_ami_id   = module.runners.launch_template.latest_version` as the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#attributes-reference) say that the `latest_version` is the "the latest version of the launch template", not the AMI.

2022-02-04 22:32 UTC, npalm approved these changes
LGTM

2022-02-04 22:33 UTC, merged