Ability to disable default security group creation step
philips-labs/terraform-aws-github-runner pull request #1718
Opened 2022-02-10 12:43 UTC by krlydm

Closes: #1717 

It can restricted who has access to create/modify VPCs or Security groups in AWS, so implicit security group creating in runner modul can be a problem in these cases. Removing VPC creation is easy, but there is no option to do it for the default security group. This change adds option to disable the security group creation of the runner module.

2022-02-11 12:30 UTC, npalm requested changes
@krlydm Tested and is not working due to dependency of the security group.

2022-02-11 12:30 UTC, npalm commented on modules/runners/main.tf
> +  count = var.enable_managed_runner_security_group ? 1 : 0
Please can you check line 91, here the security group is used and needs to be updated for the count. I think this should work

```hcl
  vpc_security_group_ids = compact(concat(
    var.enable_managed_runner_security_group ? [aws_security_group.runner_sg[0].id] : [],
    var.runner_additional_security_group_ids,
  ))
```

2022-02-11 12:39 UTC, krlydm commented on modules/runners/main.tf
> +  count = var.enable_managed_runner_security_group ? 1 : 0
Updated.

2022-02-11 14:21 UTC, npalm commented on modules/runners/main.tf
> +  count = var.enable_managed_runner_security_group ? 1 : 0
Thx will check asap, CI is also failing with formatting errors. Can you check that as well?

2022-02-11 14:29 UTC, krlydm commented on modules/runners/main.tf
> +  count = var.enable_managed_runner_security_group ? 1 : 0
Updated again. Sorry about these "newbie" issues, Terraform is entirely new for me, but now I know what should I run locally to avoid these issues.

2022-02-11 17:37 UTC, npalm commented on modules/runners/main.tf
> +  count = var.enable_managed_runner_security_group ? 1 : 0
Still two jobs are failing. I will have a look later, this seems to be caused by the new Terraform AWS provider 4.0 See #1739

2022-02-11 21:52 UTC, npalm commented
@krlydm can you rebase with the develop branch, I hope that will fix the build failures

2022-02-14 08:01 UTC, krlydm commented
> @krlydm can you rebase with the develop branch, I hope that will fix the build failures

@npalm Rebased.

2022-02-15 09:57 UTC, krlydm commented
@npalm Is there anything that I need to do to resolve the change request?

2022-02-15 15:30 UTC, npalm commented
@krlydm no I only need a bit of time. WIll do my best to merge asap. Thx!

2022-02-17 08:43 UTC, npalm approved these changes
@krlydm LGTM, thanks!

2022-02-17 08:43 UTC, merged