fix: updated S3 resource as per AWS 4.0 version
philips-labs/terraform-aws-github-runner pull request #1739
Opened 2022-02-10 20:47 UTC by shashidhar087

Terraform released new version AWS provider 4.0.0 today one hour ago.  The version mentioned in our terraform is version = ">= 3.38" . The version 4.0.0 is a breaking change for S3 resource and some of the arguments like "acl", "lifecycle_rule", "lifecycle_configuration" became "read_only".

Reference - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

2022-02-11 01:35 UTC, shashidhar087 commented
The example workflows are failing since the terraform init is reusing the version present terraform.lock.hcl file .
How do we make it work ? I could think of two possible ways 

1. "terraform init -upgrade" 
2. Mention the AWS version >=4.0.0 in all the providers files

2022-02-11 09:03 UTC, npalm commented
@shashidhar087 thanks for your contribution. We will check the PR in next days. I normally prefer to wait a bit with upgrading the new major version. Normally prefer to wait for a first bug fix. For the time being I have created a quick fix to limit the max provider version, see #1741

2022-02-25 10:33 UTC, npalm commented
@shashidhar087 can you run a rebase. And can you run on the terraform examples `terraform init -upgrade` to upgrade the aws provider in the lock file. That should solve the breaking builds

2022-02-25 17:11 UTC, shashidhar087 commented
@npalm Thanks for reaching out. I have done rebase and resolved the conflicts.
Could you please review and let me know if any changes to be done ?

2022-02-25 18:22 UTC, npalm commented
@shashidhar087 will check next week, builds are now all good

2022-02-28 11:27 UTC, julada requested changes

2022-02-28 11:27 UTC, julada commented on modules/runner-binaries-syncer/main.tf
> +    for_each = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? [] : [lookup(var.server_side_encryption_configuration, "rule", {})]
```suggestion
  count = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? 0 : 1

  dynamic "rule" {
    for_each = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? [] : [lookup(var.server_side_encryption_configuration, "rule", {})]
```

  dynamic "rule" {
    for_each = [lookup(var.server_side_encryption_configuration, "rule", {})]

it is not allowed to define a `aws_s3_bucket_server_side_encryption_configuration` resource without any rule:
`aws_s3_bucket_server_side_encryption_configuration`

the resource must be omitted completely when no rule ist defined

2022-02-28 11:46 UTC, julada commented on modules/runner-binaries-syncer/main.tf
>  }
```suggestion
resource "aws_s3_bucket_server_side_encryption_configuration" "action_dist" {
  bucket = aws_s3_bucket.action_dist.id

  count = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? 0 : 1

  rule {
    bucket_key_enabled = lookup(var.server_side_encryption_configuration.rule, "bucket_key_enabled", null)

    dynamic "apply_server_side_encryption_by_default" {
      for_each = [var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default]

      content {
        sse_algorithm     = apply_server_side_encryption_by_default.value.sse_algorithm
        kms_master_key_id = lookup(apply_server_side_encryption_by_default.value, "kms_master_key_id", null)
      }
    }

  }
}
```

2022-03-01 08:37 UTC, julada commented on modules/runner-binaries-syncer/main.tf
> +    for_each = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? [] : [lookup(var.server_side_encryption_configuration, "rule", {})]
@shashidhar087

2022-03-01 15:03 UTC, shashidhar087 commented on modules/runner-binaries-syncer/main.tf
> +    for_each = length(keys(lookup(var.server_side_encryption_configuration, "rule", {}))) == 0 ? [] : [lookup(var.server_side_encryption_configuration, "rule", {})]
Good catch, thans @julada I will commit the suggested change

2022-03-01 15:21 UTC, shashidhar087 commented on modules/runner-binaries-syncer/main.tf
>  }
@julada updated resource as suggested. Thank You.

2022-03-10 13:15 UTC, npalm commented
@shashidhar087 sorry for keep you wating. Will test the PR asap.

2022-04-06 07:00 UTC, prashanthbgoud commented
@npalm did you get any chance to review this?

2022-04-06 07:22 UTC, npalm commented
@shashidhar087 sorry no, was ill.

2022-04-08 20:00 UTC, npalm requested changes
@shashidhar087 First of my excuse for keep you wainting that long. But thanks for the great work. And we think it is time to upgrade provider. I have added one small command related to the examples. Can you update the examples as well.

2022-04-08 20:00 UTC, npalm commented on .github/workflows/terraform.yml
> +        run: terraform init -upgrade -get -backend=false -input=false
Can you revert the upgrade here, and update the examples by updating the version.tf files and running an init upgrade?

2022-04-11 17:33 UTC, shashidhar087 reviewed
Review request

2022-04-13 13:32 UTC, shashidhar087 commented
@npalm - Terraform error - Could not retrieve the list of available versions for provider
│ hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 3.71.0
│ does not match configured version constraint >= 3.63.0, ~> 4.0; must use
│ terraform init -upgrade to allow selection of new versions

2022-04-13 13:42 UTC, npalm commented
We have the lock file in the repo, we prefer an immutal setup. Please can you run in each example dir `terrraform init -upgrade` and commit the lock file. That should fix the CI

2022-04-13 13:54 UTC, shashidhar087 commented
> We have the lock file in the repo, we prefer an immutal setup. Please can you run in each example dir `terrraform init -upgrade` and commit the lock file. That should fix the CI

Done. Waiting for workflow approval.

2022-04-13 14:01 UTC, npalm approved these changes
LGTM, @ScottGuymer can you a double check due to the impact of the change

2022-04-13 14:06 UTC, npalm commented
@shashidhar087 thanks, CI is happy. I have created an Issue #1938  (and pinned the issue). Let give the community several days to react. Also asked for a second review due to the impact. Thanks for you contribution!

2022-04-13 14:59 UTC, npalm commented
@shashidhar087 please can you resolve the conflict? You can simply ignore the incoming change.

2022-04-13 15:34 UTC, shashidhar087 commented
> @shashidhar087 please can you resolve the conflict? You can simply ignore the incoming change.

Conflict resolved.

2022-04-21 15:09 UTC, spider-network commented
Really cool, we are waiting for the AWS provider 4.x support.

2022-05-03 10:03 UTC, prashanthbgoud commented
@npalm I am waiting for this feature, do we have any timelines for merging this?

2022-05-03 19:04 UTC, npalm commented
> @npalm I am waiting for this feature, do we have any timelines for merging this?

I have planned some time tomorrow to get the PR's related version 4.0 merged. So hope to have the feature available this week.

2022-05-04 12:33 UTC, npalm approved these changes

2022-05-04 12:34 UTC, merged