Added new variable to allow userdata to be passed as string to aws launch template
philips-labs/terraform-aws-github-runner pull request #1963
Opened 2022-04-22 22:51 UTC by rashidnhm

Fix for the issue mentioned in #1960. This PR enabled the passing of userdata script as a string to the module.

If both variables `userdata_string` and `userdata_template` are passed, then `userdata_string` would take precedence.

2022-04-25 10:36 UTC, npalm commented
Note: check conflicts with #1956

2022-05-09 08:07 UTC, ScottGuymer commented
As this is a quite advanced usecase I think this needs an example to show a potential user how to do this and call out some of the things they need to consider along the way.

2022-05-09 08:11 UTC, ScottGuymer requested changes

2022-05-09 08:11 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  description = "Alternative user-data as string, replacing the default template. By providing your own user_data you have to take care of installing all required software, including the action runne
It needs to be made clear in this that this is an advanced use case and here be dragons. Maybe prepend `**Advanced**` or something, not sure if we have a convention for this yet.

It also needs an example with an extensive readme on what to look for and the fact that future upgrades can likely cause issues.

2022-05-16 17:47 UTC, rashidnhm commented on main.tf
> +  userdata_string       = var.userdata_string
I have updated the variable name to `userdata` as I felt it captured the usecase well. I have also updated the variable description to include more "use with care" cautions.

2022-05-16 17:48 UTC, rashidnhm commented on modules/runners/variables.tf
> +  description = "Alternative user-data as string, replacing the default template. By providing your own user_data you have to take care of installing all required software, including the action runne
Variable description has been updated. Please re-assess and let me know

2022-05-16 19:43 UTC, rashidnhm commented
I am also open to adding a `userdata` example if you'd like. Let me know.

2022-05-17 09:15 UTC, ScottGuymer commented
Yes, I think an example of how to use this is warranted. With some notes in the readme to guide the user when they might want to use it and what issues there could be.

2022-05-17 16:20 UTC, npalm requested changes
@rashidnhm please can you rebase the PR. We have updated the module last week to AWS terraform provide 4.x

2022-05-17 16:20 UTC, npalm commented on main.tf
> +  userdata_string       = var.userdata_string
I think userdata_override is a better name; it gives a much clearer message it is ovrriding the default behavior of the module. By overriding the user_data the user of the module have to write a own custom script to manage the runner instllation and registration.

2022-05-19 15:39 UTC, rashidnhm commented on main.tf
> +  userdata_string       = var.userdata_string
Sounds good, I will update shortly

2022-05-19 16:03 UTC, rashidnhm commented on main.tf
> +  userdata_string       = var.userdata_string
I have updated the userdata variable name to `userdata_override`

2022-05-20 09:59 UTC, ScottGuymer commented on README.md
> +| <a name="input_userdata"></a> [userdata](#input\_userdata) | Alternative to userdata\_template to pass userdata as string. Note: Usage of this variable overrides all templates in place by this modu
This doc just needs updating to the new name.

2022-05-20 10:00 UTC, ScottGuymer commented on modules/runners/variables.tf
> +  description = "Alternative user-data as string, replacing the default template. By providing your own user_data you have to take care of installing all required software, including the action runne
LGTM

2022-05-20 10:00 UTC, ScottGuymer commented
I think we are just missing the example now.

2022-05-20 13:55 UTC, rashidnhm commented on README.md
> +| <a name="input_userdata"></a> [userdata](#input\_userdata) | Alternative to userdata\_template to pass userdata as string. Note: Usage of this variable overrides all templates in place by this modu
I've updated the README

2022-06-27 20:12 UTC, npalm commented
Will put it on my list, sorry the PR got out of sight.

2022-07-07 02:49 UTC, rashidnhm commented
@npalm Sorry about the late reply, I've fixed the formatting issue. Please take a look and let me know.

2022-07-13 15:48 UTC, rashidnhm commented
@npalm Just checking in to see if you got a chance to comb through this?

2022-07-13 16:13 UTC, npalm commented
not yet, hope to check all the open PR's this week

2022-09-14 14:37 UTC, rashidnhm commented
@npalm I will try to update this PR soon and pull in all latest changes, will you have time to review anytime soon?

2022-10-12 19:17 UTC, rashidnhm commented
@npalm the reason I had this PR is to add functionality myself for having multiple runners. However, now that #2472 is in progress, this is no longer needed on my end.

2022-10-12 19:52 UTC, npalm commented
I think in that case we should close, thanks fro reaching out

2022-10-12 21:09 UTC, closed without merging