feat: Support arm64 lambda functions
philips-labs/terraform-aws-github-runner pull request #2121
Opened 2022-06-07 19:31 UTC by dylanmtaylor

2022-06-08 09:48 UTC, ScottGuymer reviewed
Looks good. Just a couple of small comments.

Is this worth an addition to the readme to explain why you might set this.

I would also be curious to understand what the potential cost savings are here and if we might want to make arm64 the default.

2022-06-08 09:48 UTC, ScottGuymer commented on modules/runner-binaries-syncer/variables.tf
> +variable "lambda_architecture" {
Can you add some validation for the possible values here?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#architectures

2022-06-08 09:48 UTC, ScottGuymer commented on variables.tf
> +  description = "AWS Lambda architecture."
Can you expand on this description a little to explain why you might want to set this value and what the possible options are to help make the documentation more robust.

2022-06-08 09:56 UTC, ScottGuymer commented
You also need to run `terraform fmt`

2022-06-08 12:54 UTC, dylanmtaylor commented
> I would also be curious to understand what the potential cost savings are here and if we might want to make arm64 the default.

I'm not sure about the actual numbers, but for any workload that supports it, the Graviton2 systems are almost always cheaper than x86_64. Amazon themselves claim "34% better price/performance", so it's sizable. I am fine with making it the default and will update the PR. I just wasn't sure if anyone would be against that. https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/

2022-06-08 12:59 UTC, dylanmtaylor commented on modules/runner-binaries-syncer/variables.tf
> +variable "lambda_architecture" {
Done :)

2022-06-08 13:00 UTC, dylanmtaylor commented
> Is this worth an addition to the readme to explain why you might set this.

Maybe. Honestly, as long as it works, and I haven't seen any evidence there are issues with it, arm64 seems to be a sane default.

2022-06-09 11:21 UTC, npalm commented
Looks good, need to test later this week. Please can you also update the pool module? See https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/modules/runners/pool

2022-06-09 11:53 UTC, dylanmtaylor commented
> Looks good, need to test later this week. Please can you also update the pool module? See https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/modules/runners/pool

Sure thing. I'll do that now.

2022-06-09 12:16 UTC, dylanmtaylor commented
I updated it and think it's good to go now, I thought about rebasing and squashing those commits but figured it'd be preferable to have the commit history and the maintainers could squash it down at merge time.

2022-06-10 12:30 UTC, dylanmtaylor commented
I see the test is failing, sorry about that. Let me try to get it in good shape.

2022-06-10 12:36 UTC, npalm requested changes
@dylanmtaylor thanks for the updates. Tested at all works. I prefer to keep the default to x64 for the moment (made code suggestions). Also made a small correction suggestion in the change for the pool

2022-06-10 12:36 UTC, npalm commented on modules/runner-binaries-syncer/variables.tf
> +  default     = "arm64"
I prefer to keep the default the same as the current default architecture
```suggestion
  default     = "x86_64"
```

2022-06-10 12:36 UTC, npalm commented on modules/runners/variables.tf
> +  default     = "arm64"
I prefer to keep the default the same as the current default architecture
```suggestion
  default     = "x86_64"
```

2022-06-10 12:36 UTC, npalm commented on modules/runners/pool/main.tf
> +  architectures                  = [var.config.lambda_architecture]
```suggestion
  architectures                  = [var.config.lambda.architecture]
```

2022-06-10 12:36 UTC, npalm commented on modules/webhook/variables.tf
> +  default     = "arm64"
I prefer to keep the default the same as the current default architecture
```suggestion
  default     = "x86_64"
```

2022-06-10 12:36 UTC, npalm commented on variables.tf
> +  default     = "arm64"
I prefer to keep the default the same as the current default architecture
```suggestion
  default     = "x86_64"
```

2022-06-10 13:15 UTC, npalm approved these changes

2022-06-10 13:16 UTC, merged