fix: set kms key on aws_s3_object when encryption is enabled
philips-labs/terraform-aws-github-runner pull request #2147
Opened 2022-06-13 10:46 UTC by julada

* fixes an error during apply on aws_s3_object when encryption is enabled
* set kms key id when encryption is enabled
* dont set unsupported etag property when encryption is enabled

2022-06-14 05:35 UTC, npalm commented
Reference to docs: https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/s3_object#etag

2022-06-14 05:37 UTC, npalm commented
fix: #2105

2022-06-14 13:11 UTC, npalm requested changes
@julada tested with the default example, got an error. See fixed in the comments.

2022-06-14 13:11 UTC, npalm commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  etag       = lookup(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default, "kms_master_key_id", null) == null ? filemd5("${path.module}/trigger.json") : null
Apply is failing in the case SSE is not configured since `server_side_encryption_configuration` is not set. By using`try` this can be avoided.
```suggestion
  etag       = try(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.kms_master_key_id, null) == null ? filemd5("${path.module}/trigger.json") : null
```

2022-06-14 13:11 UTC, npalm commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  kms_key_id = lookup(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default, "kms_master_key_id", null)
Apply is failing in the case SSE is not configured since `server_side_encryption_configuration` is not set. By using`try` this can be avoided.
```suggestion
  kms_key_id = try(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.kms_master_key_id, null)
```

2022-06-14 13:41 UTC, julada commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  etag       = lookup(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default, "kms_master_key_id", null) == null ? filemd5("${path.module}/trigger.json") : null
You are absolutely right, i should have checked that. Thanks for fixing it. I will apply your suggestion.

2022-06-14 13:54 UTC, npalm approved these changes

2022-06-14 13:54 UTC, npalm commented
@julada thanks!

2022-06-14 13:54 UTC, merged

2022-06-24 21:38 UTC, shashidhar087 commented
@julada Could you pls provide an example of where to set KMS Key ID. I am running into this issue where I have enabled SSE encryption and not KMS type on S3.

2022-06-24 21:56 UTC, julada commented
Can you provide an example of your actual issue?

2022-06-24 22:11 UTC, julada commented
Ah i got it. Pls try to add the server_side_encryption property on the aws_s3_object ressource. It must be set to the configured sse algorithm. In your case this attribute should be set to "AES256". If you dont want to create a fix for this case u can switch to kms encryption by adjusting your sse configuration.

2022-06-26 02:53 UTC, shashidhar087 commented
Thank you for the quick response. Issue got fixed after setting the server_side_encryption key in 'aws_s3_object' resource. 

 server_side_encryption = try(var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.sse_algorithm, null)