feat: Changes to publish gh actions event to second queue for monitoring.
philips-labs/terraform-aws-github-runner pull request #2268
Opened 2022-07-20 15:05 UTC by GuptaNavdeep1983

2022-07-21 12:16 UTC, npalm requested changes
@GuptaNavdeep1983 thanks for you PR. I think we have to explain the feature we adding here in a bit more detail. And update the readme as well.

We should be really clear about the message definition that we put on the secondary queue. Main purpose is to hook in any kind of monitor or analitics soluition. 

The max message size for SQS is 256 KB, can we ensure that the message we are forwarding will fit? Does GitHub specify anything about the size?

2022-07-21 12:16 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +async function monitorWorkflowEvents(githubEvent: string, payload: any) {
I think most of the logic here can be moved to sendMonitorGHWorfkflowEvent. You call the function in the if statement above. The checks for sedning the event can be done inside the sendMonitorGHWorfkflowEvent as well the logging.

2022-07-21 12:16 UTC, npalm commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +  await sqs.sendMessage(sqsMessage).promise();
Any error should be catched, logged and ignored here.

2022-07-21 12:16 UTC, npalm commented on modules/webhook/variables.tf
> +variable "sqs_monitored_build_events" {
Please update the resource name, we still have to find a good name.

2022-07-21 12:16 UTC, npalm commented on modules/webhook/variables.tf
> +variable "webhook_events_secondary_queue" {
Do we use this variable here?

2022-07-21 12:16 UTC, npalm commented on modules/webhook/webhook.tf
> +resource "aws_iam_role_policy" "webhook_sqs_1" {
Can you update the naming so it match the queue name?

2022-07-22 14:36 UTC, GuptaNavdeep1983 commented on main.tf
> +resource "aws_sqs_queue_policy" "monitored_build_events_policy" {
Updated.

2022-07-22 14:36 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/sqs/index.test.ts
> +    process.env.SQS_MONITORED_BUILD_EVENTS = sqsMessage.QueueUrl;
Done.

2022-07-22 14:37 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +  await sqs.sendMessage(sqsMessage).promise();
Updated to catch the exceptions and ignored after logging.

2022-07-22 14:37 UTC, GuptaNavdeep1983 commented on modules/webhook/variables.tf
> +variable "sqs_monitored_build_events" {
Updated.

2022-07-22 14:38 UTC, GuptaNavdeep1983 commented on modules/webhook/variables.tf
> +variable "webhook_events_secondary_queue" {
Removed. It once seemed required as the tf was unable to prepare a plan but worked fine after removing and multiple level of testing

2022-07-22 14:38 UTC, GuptaNavdeep1983 commented on modules/webhook/webhook.tf
> +resource "aws_iam_role_policy" "webhook_sqs_1" {
Updated.

2022-07-22 14:39 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +async function monitorWorkflowEvents(githubEvent: string, payload: any) {
Updated.

2022-08-15 07:10 UTC, npalm requested changes

2022-08-15 07:10 UTC, npalm commented on README.md
> +### Secondary Queue
Would call this GItHub Workflow even copy queue. Secondary is to vague

2022-08-15 07:10 UTC, npalm commented on main.tf
> +  delay_seconds               = var.workflow_job_queue_configuration.delay_webhook_event_queue
Would suggest you define an object with the queue configuration. The new quque has no relation to other values. Since the queue is not part of the system, only a way to caputure the GitHub evens.

2022-08-15 07:10 UTC, npalm commented on README.md
> +### Secondary Queue
Can you also add a reference or explain the expected message interface?

2022-08-15 07:10 UTC, npalm commented on modules/webhook/lambdas/webhook/src/sqs/index.test.ts
> +  it('Does not send webhook events to secondary queue', async () => {
```suggestion
  it('Does not send webhook events to workflow job event copy queue', async () => {
```

2022-08-15 07:10 UTC, npalm commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +export interface GithubWorkflowEvent {
I think we should add this interface to the docs.

2022-08-15 07:10 UTC, npalm commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +export const sendWebhookEventToSecondaryQueue = async (message: GithubWorkflowEvent): Promise<void> => {
Can you update the method name consisently, no secondary queue

2022-08-15 07:10 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +async function monitorWorkflowEvents(githubEvent: string, workflowEventPayload: WorkflowJobEvent) {
We ended up with several names right now, monitorWorkflowEvents, secondary... and worflowJobEventCopy. I think I prefer the latest one. Since it is clear and specific.

2022-08-15 07:10 UTC, npalm commented on README.md
> +### Secondary Queue
Can you make also explicit that the feature is experimental

2022-08-22 18:23 UTC, GuptaNavdeep1983 commented on modules/webhook/variables.tf
> +variable "sqs_secondary_queue" {
Resolved.

2022-08-22 18:36 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +async function monitorWorkflowEvents(githubEvent: string, workflowEventPayload: WorkflowJobEvent) {
Fixed.

2022-08-22 18:36 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +export const sendWebhookEventToSecondaryQueue = async (message: GithubWorkflowEvent): Promise<void> => {
Fixed.

2022-10-04 06:34 UTC, npalm commented
@GuptaNavdeep1983 thought we had this PR almost finished, should we not re-open it?

2022-10-04 17:22 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +export interface GithubWorkflowEvent {
Added.

2022-10-04 17:23 UTC, GuptaNavdeep1983 commented on main.tf
> +  delay_seconds               = var.workflow_job_queue_configuration.delay_webhook_event_queue
updated.

2022-10-04 17:23 UTC, GuptaNavdeep1983 commented on README.md
> +As per the solution architecture, the web hook events for workflow jobs are sent to a primary queue, from where they are consumed by scale up lambda. In addition to that primary queue, this module al
updated.

2022-10-05 11:02 UTC, npalm commented on README.md
> +which is extendible format to add more fields to be published along with the workflow job event.
```suggestion
This extendible format allows to add more fields to be added if needed.
```

2022-10-05 11:05 UTC, npalm commented on README.md
> +On the second queue we just forward the incoming github event. Which can be used for metrics. You can configure `webhook_events_workflow_job_queue` to enable this experimental feature.
Suggested also to rename the parameters, would require some more changes.

2022-10-05 11:27 UTC, npalm commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +  logger.debug(`Webhook events workflow job queue: ${webhook_events_workflow_job_queue}`, LogFields.print());
Not reason to log this again, or not?

2022-10-05 16:28 UTC, GuptaNavdeep1983 commented on examples/arm64/README.md
> +Steps for the full setup, such as creating a GitHub app can be found in the root module's [README](https://github.com/philips-labs/terraform-aws-github-runner). First download the Lambda releases fro
updated.

2022-10-05 16:33 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/sqs/index.ts
> +  logger.debug(`Webhook events workflow job queue: ${webhook_events_workflow_job_queue}`, LogFields.print());
updated.

2022-10-06 20:44 UTC, GuptaNavdeep1983 commented on main.tf
> +  tags                        = var.tags
updated.

2022-10-07 08:42 UTC, npalm requested changes
One minor left.

2022-10-07 08:42 UTC, npalm commented on README.md
> +  - [Secondary Queue](#secondary-queue)
Still the wrong title here :(

2022-10-07 13:23 UTC, GuptaNavdeep1983 commented on README.md
> +  - [Secondary Queue](#secondary-queue)
upadted.

2022-10-14 20:36 UTC, npalm approved these changes

2022-10-14 20:38 UTC, merged