feat: Added the Machine setup info to runner workflows.
philips-labs/terraform-aws-github-runner pull request #2451
Opened 2022-09-22 14:37 UTC by GuptaNavdeep1983

This PR adds the AMI Id for the runner machine to github workflows.

2022-09-22 14:43 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +tee /opt/actions-runner/.setup_info <<EOL
Should the group not have a value?

2022-09-22 14:45 UTC, npalm commented
What other values would be nice to set? For example OS or linux distro?

Like the GitHub hosted runners, group OS, group image

2022-10-06 07:10 UTC, npalm commented
@GuptaNavdeep1983 can you check the comments please?

2022-10-06 20:53 UTC, GuptaNavdeep1983 commented on modules/runners/templates/start-runner.sh
> +tee /opt/actions-runner/.setup_info <<EOL
updated.

2022-10-07 08:43 UTC, npalm submitted a review, later dismissed
LGTM, @ScottGuymer can you have a quick look on the windows scripts?

2022-10-07 10:31 UTC, npalm requested changes
Add some small improvements in the suggestions, tested with the default example

2022-10-07 10:31 UTC, npalm commented on modules/runners/templates/start-runner.ps1
> +)
```suggestion
$jsonBody = @(
    @{
        group='Runner Image'
        details="AMI id: $ami_id"
    }
)
```

2022-10-07 10:31 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +EOL
Adding a bit more info, and similar to GH hosted runners
```suggestion
info_arch=$(uname -p)
info_os=$(( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1 | cut -d "=" -f2- | tr -d '"')

tee /opt/actions-runner/.setup_info <<EOL
[
  {
    "group": "Operating System",
    "detail": "Distribution: $info_os\nArchitecture: $info_arch"
  },
  {
    "group": "Runner Image",
    "detail": "AMI id: $ami_id"
  }
]
EOL
```

2022-10-07 10:31 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +EOL
Example:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/11609620/194533649-44c43089-376b-41be-943d-7fc3dd3a4d45.png">

2022-10-07 14:20 UTC, ScottGuymer commented on modules/runners/templates/start-runner.ps1
> +ConvertTo-Json -InputObject $jsonBody > "$pwd\.setup_info"
```suggestion
ConvertTo-Json -InputObject $jsonBody | Set-Content -Path "$pwd\.setup_info"
```

Small change to be more explicit for powershell

2022-10-07 20:57 UTC, npalm approved these changes
Thx, nice job!

2022-10-07 20:57 UTC, merged