feat: Added a new feature to allow the creation of single webhook to handle all workflow events
philips-labs/terraform-aws-github-runner pull request #2472
Opened 2022-09-27 22:53 UTC by GuptaNavdeep1983

2022-10-10 17:55 UTC, npalm requested changes
Partial first review. Great to see we finally can create runners for different configurations. I did a first partial review.

- Can you also update the main README and add a section to explain the mulit runner setup.
- Can you add a readme to the multi. runner example.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/queues.tf
> +  delay_seconds               = var.delay_webhook_event
I think the delay should also move to the runner config. For ephemeral I would set it to zero in other cases from 5 to 30.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/queues.tf
> +  visibility_timeout_seconds  = var.runners_scale_up_lambda_timeout
Not sure yet. But the visibility timeout should match the lambda timeout.  I don't see a reason yet to differ per runner. I think could be the same for all configs.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/queues.tf
> +  unique_os_and_arch         = distinct([for index, config in local.multi_runner_queues_config : { "os_type" : config["runner_config"]["runner_os"], "architecture" : config["runner_config"]["runner_a
Is it needed to check `enabled_runner_binaries_syncer`? The local name unique_os_and_arch suggest that you try list all supported os and arch bij the config.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  instance_max_spot_price       = var.instance_max_spot_price
I think it make sense to move those properties to the runner config, this will support the option to run a spot-fleet and on-demand-fleet. Max spot price will differ based on instance type.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  runner_run_as                        = var.runner_run_as
I would move this also to the runner config

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  idle_config                          = var.idle_config
Would also move to the runner config, what do you think?

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  runner_group_name                = local.multi_runner_queues_config[count.index]["runner_config"]["runner_group_name"]
would multi_runner_config not be a better name?

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  scale_up_reserved_concurrent_executions = var.scale_up_reserved_concurrent_executions
This is to control the concurrent lambda execution. Assume you have a config supporting a big fleet and small fleet. I think you also would like to set this differently. Therefore I think we should move it to the config as wel.

2022-10-10 17:55 UTC, npalm commented on modules/multi-runner/runners.tf
> +  enabled_userdata      = var.enabled_userdata
userdata / cloudinit is baded on the runner AMI, so would move this to the config.

2022-10-10 17:55 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +      if (body.action === 'queued') {
Would it not more efficient to check this before the for loop?

2022-10-10 17:55 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +        logger.info(`Successfully queued job for ${body.repository.full_name}`, LogFields.print());
We should update this log line, so we know to which queue the event was submitted, and which config was applied.

2022-10-12 13:15 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +      if (body.action === 'queued') {
moved.

2022-10-12 13:15 UTC, GuptaNavdeep1983 commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +        logger.info(`Successfully queued job for ${body.repository.full_name}`, LogFields.print());
updated to add queue id.

2022-10-12 13:15 UTC, GuptaNavdeep1983 commented on modules/multi-runner/runners.tf
> +  enabled_userdata      = var.enabled_userdata
updated.

2022-10-12 13:16 UTC, GuptaNavdeep1983 commented on modules/multi-runner/runners.tf
> +  runner_group_name                = local.multi_runner_queues_config[count.index]["runner_config"]["runner_group_name"]
i think you already updated this.

2022-10-12 13:16 UTC, GuptaNavdeep1983 commented on modules/multi-runner/runners.tf
> +  idle_config                          = var.idle_config
updated.

2022-10-12 13:16 UTC, GuptaNavdeep1983 commented on modules/multi-runner/runners.tf
> +  runner_run_as                        = var.runner_run_as
you updated.

2022-10-12 13:16 UTC, GuptaNavdeep1983 commented on modules/multi-runner/runners.tf
> +  instance_max_spot_price       = var.instance_max_spot_price
updated.

2022-10-12 13:16 UTC, GuptaNavdeep1983 commented on modules/multi-runner/queues.tf
> +  delay_seconds               = var.delay_webhook_event
updated.

2022-10-12 15:02 UTC, npalm commented on examples/multi-runner/README.md
> +This module shows how to create GitHub action runners with multiple runner configuration together in one deployment.
I think it could be helpful to explain how the filters are working, that the order is important, and if relevant the exact match. Would also mention that a single App is used for all runners.

2022-10-13 14:14 UTC, GuptaNavdeep1983 commented on examples/multi-runner/main.tf
> +        "runner_extra_labels" : "staging"
Do we need to change something here?

2022-10-13 14:14 UTC, GuptaNavdeep1983 commented on modules/multi-runner/queues.tf
> +  visibility_timeout_seconds  = var.runners_scale_up_lambda_timeout
I think it can be outside runner configuration.

2022-10-13 14:15 UTC, GuptaNavdeep1983 commented on examples/multi-runner/README.md
> +This module shows how to create GitHub action runners with multiple runner configuration together in one deployment.
Updated the readme.

2022-10-13 14:15 UTC, npalm commented on modules/multi-runner/queues.tf
> +  visibility_timeout_seconds  = var.runners_scale_up_lambda_timeout
Agree, we koop them on top level.

2022-10-13 14:16 UTC, npalm commented on modules/multi-runner/queues.tf
> +  unique_os_and_arch         = distinct([for index, config in local.multi_runner_queues_config : { "os_type" : config["runner_config"]["runner_os"], "architecture" : config["runner_config"]["runner_a
agree,

2022-10-13 14:17 UTC, npalm commented on examples/multi-runner/main.tf
> +        "runner_extra_labels" : "staging"
I will have a look again

2022-10-14 10:55 UTC, npalm commented on modules/multi-runner/variables.tf
> +  type = map(object({
Here we missing a description. We should point out that in general all the variables are based on the one in the underlying modules and documente there. But explain the one we introduce here like matcher config

2022-10-14 10:58 UTC, npalm commented
Checked an upgrade for the default example, went smooth without an issue

2022-10-14 13:17 UTC, GuptaNavdeep1983 commented on modules/multi-runner/variables.tf
> +  type = map(object({
Added the description already in this block, is there anything else required?

2022-10-18 14:36 UTC, npalm commented on examples/multi-runner/main.tf
> +  aws_region  = "eu-central-1"
```suggestion
  aws_region  = "eu-west-1"
```

2022-10-18 14:37 UTC, npalm commented on examples/multi-runner/versions.tf
> +  required_version = ">= 1"
```suggestion
  required_version = ">= 1.3"
```

2022-10-18 14:40 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
>    // ensure header keys lower case since github headers can contain capitals.
```suggestion
  # ensure header keys lower case since github headers can contain capitals.
```

2022-10-19 20:17 UTC, merged