Cleanup ssm parameters
philips-labs/terraform-aws-github-runner pull request #2587
Opened 2022-10-24 20:59 UTC by rmrf-run

Adding in the removal of un needed instance parameters from SSM parameter store. Currently there is no method to clean up parameter store and with a large Org the AWS quota for parameters can be hit fairly quickly. This should fix issue #1808

2022-11-04 00:00 UTC, npalm requested changes
Thank you for the contribution, need to do a bit of testing. The solution will solve the problem for non-ephemeral runners, and ephemeral runners tha ffailed to boot correctly. Which I believe are most of the cases. The only case left is that deletion failes when booting an ephemeral runner correctly.

2022-11-10 19:27 UTC, rmrf-run commented on modules/runners/lambdas/runners/src/aws/runners.ts
> +    .deleteParameter({
i will take a look at this, it could throw an exception, thanks

2022-12-01 07:27 UTC, npalm commented on modules/runners/lambdas/runners/src/aws/runners.ts
> +    .deleteParameter({
Already had time to have a look?

2023-02-21 02:03 UTC, closed without merging

2023-03-09 18:26 UTC, chasemgray commented
Is this still going to be merged? I see it auto closed.