feat: Allow to toggle access to EC2 instance tags
philips-labs/terraform-aws-github-runner pull request #2592
Opened 2022-10-29 18:48 UTC by MGSousa

Added variable option for toggle (`enabled`/`disabled`) access to EC2 instance tags through metadata service.

2022-10-31 18:09 UTC, npalm reviewed
@MGSousa looks good, but curious in what case do you disable the metadaservice_tags? The instance start-up requires on tags. Or do you use an alternative user_data script to start your runners in such way you are not requiring the tags.

2022-10-31 22:28 UTC, MGSousa commented
> @MGSousa looks good, but curious in what case do you disable the metadaservice_tags? The instance start-up requires on tags. Or do you use an alternative user_data script to start your runners in such way you are not requiring the tags.

For this case, I need to disable this metadata service since this restricts "spacing" in tags (https://github.com/aws/aws-cli/issues/6914), and for now, it's the only solution.
Also, I am using a custom user_data.sh script for starting the runners that call the `describe-tags` for each instance.

2022-11-03 23:52 UTC, npalm requested changes
Looks good, need to run a quick deployment test. Added a small suggestion

2022-11-03 23:52 UTC, npalm commented on variables.tf
>    description = "Metadata options for the ec2 runner instances."
```suggestion
  description = "Metadata options for the ec2 runner instances. By default, the module uses metadata tags for bootstrapping the runner, only disable `instance_metadata_tags` when using custom scripts for starting the runner."
```

2022-11-03 23:52 UTC, npalm commented on modules/runners/variables.tf
>    description = "Metadata options for the ec2 runner instances."
```suggestion
  description = "Metadata options for the ec2 runner instances. By default, the module uses metadata tags for bootstrapping the runner, only disable `instance_metadata_tags` when using custom scripts for starting the runner."
```

2022-11-08 22:30 UTC, npalm approved these changes

2022-11-08 22:30 UTC, merged