Add ability to specify iam instance role
philips-labs/terraform-aws-github-runner pull request #2688
Opened 2022-11-25 17:26 UTC by mattgodbolt

2023-02-17 09:37 UTC, npalm approved these changes

2023-02-17 09:38 UTC, npalm requested changes
Sorry for the late reply, please can you format the packer code?

2023-03-20 12:31 UTC, mattgodbolt commented
> Sorry for the late reply, please can you format the packer code?

Done! Sorry for _my_ late reply :)

2023-03-21 08:52 UTC, npalm commented on images/ubuntu-focal/github_agent.ubuntu.pkr.hcl
> +  default     = ""
Maybe better to set the default to null

2023-05-01 01:55 UTC, closed without merging