fix: added permissions for lambda to attach lambda to the VPC.
philips-labs/terraform-aws-github-runner pull request #2734
Opened 2022-12-08 06:48 UTC by GuptaNavdeep1983

2022-12-08 07:44 UTC, npalm requested changes
@GuptaNavdeep1983 thanks looks good, one small suggestion

2022-12-08 07:44 UTC, npalm commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  name = "${var.prefix}-lambda-syncer-vpc"
Can you add a conditional and only activate the policy if the lambda is attached to the vpc aka `lambda_subnet_ids` has more than zero elements.

2022-12-08 07:59 UTC, GuptaNavdeep1983 commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  name = "${var.prefix}-lambda-syncer-vpc"
Addressed.

2022-12-08 08:07 UTC, npalm commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  count = var.lambda_subnet_ids != null && var.lambda_security_group_ids != null ? 1 : 0
This won't work would, default for both `[]`. So would check for a non empty list.

2022-12-08 10:36 UTC, GuptaNavdeep1983 commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  count = var.lambda_subnet_ids != null && var.lambda_security_group_ids != null ? 1 : 0
I have tested it and it worked just fine!

2022-12-08 12:40 UTC, npalm commented on modules/runner-binaries-syncer/runner-binaries-syncer.tf
> +  count = var.lambda_subnet_ids != null && var.lambda_security_group_ids != null ? 1 : 0
I testing the default example and it tries to create the policies, which should not be created



``` 
  # module.runners.module.runners.aws_iam_role_policy.lambda_scale_up_vpc[0] will be created
  + resource "aws_iam_role_policy" "lambda_scale_up_vpc" {
      + id     = (known after apply)
      + name   = "npalm-lambda-scale-up-vpc"
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "ec2:CreateNetworkInterface",
                          + "ec2:DescribeNetworkInterfaces",
                          + "ec2:DeleteNetworkInterface",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + role   = "npalm-action-scale-up-lambda-role"
    }
```

2022-12-09 09:18 UTC, npalm approved these changes
Thanks @navdeepg2021 looks good

2022-12-09 09:18 UTC, npalm commented
close #2732

2022-12-09 12:27 UTC, merged