feat: Add runner logfiles to output
philips-labs/terraform-aws-github-runner pull request #2858
Opened 2023-01-09 12:57 UTC by sanketrathi

This PR adds logfile information for runners to the module output

2023-01-11 07:08 UTC, npalm requested changes
Thanks for your contribution. Please can yo shortly describe the need for the output, would like to understand the problem you solving. In general ok, one small remark.

2023-01-11 07:08 UTC, npalm commented on modules/multi-runner/outputs.tf
> +    logfiles                = module.runners.logfiles
This won't work, you need to refer to the runner object.
```suggestion
    logfiles                = runner.logfiles
```

2023-01-11 17:20 UTC, sanketrathi commented on modules/multi-runner/outputs.tf
> +    logfiles                = module.runners.logfiles
Thanks for the review @npalm . The PR got closed with an accidental force push, sincere apologies

2023-01-11 17:23 UTC, sanketrathi commented on modules/multi-runner/outputs.tf
> +    logfiles                = module.runners.logfiles
I've also updated the PR description with the motivating use case(s) I'm trying to solve with this change

2023-01-11 17:24 UTC, sanketrathi commented on modules/multi-runner/outputs.tf
> +    logfiles                = module.runners.logfiles
Another quick question: I was also planning on modifying the `multi-runner` module to allow `ami_id_ssm_parameter_name` as a parameter with `runner_config`. Should I raise a separate PR for it?

2023-01-12 12:20 UTC, npalm commented on modules/multi-runner/outputs.tf
> +    logfiles                = module.runners.logfiles
Yes please create a separate PR

2023-01-12 12:24 UTC, npalm requested changes

2023-01-12 12:24 UTC, npalm commented on modules/multi-runner/outputs.tf
> +    logfiles                = runners.logfiles
```suggestion
    logfiles                = runner.logfiles
```

2023-01-12 23:06 UTC, npalm approved these changes

2023-01-12 23:07 UTC, npalm approved these changes

2023-01-12 23:08 UTC, merged