Make a note about subnet AZ uniqueness requirement
philips-labs/terraform-aws-github-runner pull request #2912
Opened 2023-01-25 10:52 UTC by jpalomaki

With link to [issue](https://github.com/philips-labs/terraform-aws-github-runner/issues/2904) where this is discussed

2023-02-10 11:57 UTC, npalm requested changes
Variable section in the REAMDE.md are generated based on the terraform varaibles.tf files. Please update the varaiable.tf file. The pre-commit hooks will update the README.

2023-02-17 09:39 UTC, npalm commented
@jpalomaki  did you had time to check the requested change?

2023-02-22 11:16 UTC, jpalomaki commented
@npalm No, not yet, been busy with other stuff and need to look into the precommit hook

2023-03-01 14:43 UTC, npalm approved these changes

2023-03-01 14:44 UTC, merged