feat: allow to use a shared encrypted AMI
philips-labs/terraform-aws-github-runner pull request #2933
Opened 2023-02-07 13:36 UTC by v-rosa

Currently its not possible to use an AMI encrypted using an external KMS key.

Co-authored with @rsmolinski

2023-02-17 10:14 UTC, npalm requested changes
@v-rosa thanks for you work. In general looks good. Added a few comments.

2023-02-17 10:14 UTC, npalm commented on modules/runners/main.tf
> +  ami_kms_key_arn = var.ami_kms_key_arn != null ? var.ami_kms_key_arn : ""
Can you add the variable also to the mult-runner module?

2023-02-17 10:14 UTC, npalm commented on modules/runners/scale-up.tf
> +    ami_kms_key_arn           = local.ami_kms_key_arn
The submodule pool can also create instances, please can you hadd the ami_kms key ass well to the pool module.

2023-02-17 10:14 UTC, npalm commented on modules/runners/policies/lambda-scale-up.json
> +                "kms:ReEncrypt*",
Is ReEncrypt needed?

2023-02-17 10:14 UTC, npalm commented on modules/runners/policies/lambda-scale-down.json
> +      "Effect": "Allow",
Bit wondering why scale-down needs to be-able to decrypt en reencrypt. This lambda only terminates and describes instances.

2023-02-17 13:53 UTC, v-rosa commented on modules/runners/policies/lambda-scale-up.json
> +                "kms:ReEncrypt*",
From my tests, yes. Here you can find a redacted version of the `ReEncrypt` event in CloudTrail triggered by the user name `<runnerprefix>-scale-up`

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "redacted:<runnerprefix>-scale-up",
        "arn": "arn:aws:sts::redacted:assumed-role/<runnerprefix>-action-scale-up-lambda-role/<runnerprefix>-scale-up",
        "accountId": "redacted",
        "accessKeyId": "redacted",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "redacted",
                "arn": "arn:aws:iam::redacted:role/<runnerprefix>/<runnerprefix>-action-scale-up-lambda-role",
                "accountId": "redacted",
                "userName": "<runnerprefix>-action-scale-up-lambda-role"
            },
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2023-02-17T11:57:30Z",
                "mfaAuthenticated": "false"
            }
        },
        "invokedBy": "ec2-frontend-api.amazonaws.com"
    },
    "eventTime": "2023-02-17T13:45:01Z",
    "eventSource": "kms.amazonaws.com",
    "eventName": "ReEncrypt",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "ec2-frontend-api.amazonaws.com",
    "userAgent": "ec2-frontend-api.amazonaws.com",
    "requestParameters": {
        "destinationEncryptionAlgorithm": "SYMMETRIC_DEFAULT",
        "sourceAAD": "redacted",
        "sourceEncryptionContext": {
            "aws:ebs:id": "redacted"
        },
        "destinationEncryptionContext": {
            "aws:ebs:id": "redacted"
        },
        "sourceEncryptionAlgorithm": "SYMMETRIC_DEFAULT",
        "destinationKeyId": "alias/aws/ebs",
        "destinationAAD": "redacted"
    },
    "responseElements": null,
    "requestID": "x",
    "eventID": "y",
    "readOnly": true,
    "resources": [
        {
            "accountId": "redacted",
            "type": "AWS::KMS::Key",
            "ARN": "arn:aws:kms:us-east-1:redacted:key/redacted"
        },
        {
            "accountId": "redacted",
            "type": "AWS::KMS::Key",
            "ARN": "arn:aws:kms:us-east-1:redacted:key/redacted"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "redacted",
    "sharedEventID": "z",
    "eventCategory": "Management"
}
```

2023-02-17 14:11 UTC, v-rosa commented on modules/runners/scale-up.tf
> +    ami_kms_key_arn           = local.ami_kms_key_arn
sure!

2023-02-17 14:11 UTC, v-rosa commented on modules/runners/main.tf
> +  ami_kms_key_arn = var.ami_kms_key_arn != null ? var.ami_kms_key_arn : ""
sure!

2023-02-17 14:21 UTC, v-rosa commented on modules/runners/policies/lambda-scale-down.json
> +      "Effect": "Allow",
Indeed this is not needed for scale down. Will remove.

2023-02-22 11:20 UTC, v-rosa commented on modules/runners/main.tf
> +  ami_kms_key_arn = var.ami_kms_key_arn != null ? var.ami_kms_key_arn : ""
done.

2023-02-22 11:20 UTC, v-rosa commented on modules/runners/scale-up.tf
> +    ami_kms_key_arn           = local.ami_kms_key_arn
done

2023-02-22 11:21 UTC, v-rosa commented on modules/runners/policies/lambda-scale-down.json
> +      "Effect": "Allow",
done

2023-03-08 07:27 UTC, npalm approved these changes

2023-03-08 07:28 UTC, npalm commented
@v-rosa @rsmolinski Thanks!

2023-03-08 07:29 UTC, merged