fix: Allow lambda inside VPC
philips-labs/terraform-aws-github-runner pull request #2938
Opened 2023-02-09 12:54 UTC by jsalcedo1987

Hi! 👋

This PR contains the following changes:
-  It allows webhook lambda to run inside a VPC 
-  fix a minor issue in the syncer module, when the lambda is running inside vpc AWSLambdaVPCAccessExecutionRole needs to be attached.

Updated doc.

Do not hesitate to ask if you need further details,
Thanks!

2023-02-10 13:20 UTC, npalm requested changes
@jsalcedo1987 Thanks for your contribution. A small remark. We basides the top level main module also the variables needs to be added to the mult-runner module.

2023-02-10 13:20 UTC, npalm commented on main.tf
> +  lambda_subnet_ids         = var.lambda_subnet_ids
Can you also update the file `modules/multi-runner/webhook.tf` and pass the new varabiles down to the webhook module.

2023-02-10 14:38 UTC, jsalcedo1987 commented on main.tf
> +  lambda_subnet_ids         = var.lambda_subnet_ids
Thanks for the heads up! 😅 I'm not using the new multi-runner module so I missed that bit. I've now added the missing variables to the file 👍

2023-02-17 10:06 UTC, npalm approved these changes
@jsalcedo1987 thanks looks all good now

2023-02-17 10:07 UTC, merged