feat: Add option to disable Runner Syncer Lambda trigger
philips-labs/terraform-aws-github-runner pull request #2986
Opened 2023-02-22 12:14 UTC by anjosluc

Currently the module allows us to use Lambda functions to sync GitHub runner binaries on S3 automatically to the latest release available on actions/runners repository, but sometimes a release can have issues in their functionality that were not caught by Github prior to release it, so we need to rollback the binary distribution on S3 to a previous version and disable Lambda Syncer to stop checking for updates. This option allows us to quickly solve problems in runners version like we had in https://github.com/actions/runner/issues/2435 by freezing automatic updates and still being able to use Runner Syncer.

2023-02-24 11:01 UTC, npalm requested changes
@anjosluc looks good, can you add the new variable also to the multi-runner module? See https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/multi-runner/runner-binaries.tf

2023-02-24 11:02 UTC, npalm commented on variables.tf
> +  description = "Option to disable EventBridge Lambda trigger, useful to stop automatic updates of binary distribution"
```suggestion
  description = "Option to disable EventBridge Lambda trigger for the binary syncer, useful to stop automatic updates of binary distribution"
```

2023-02-24 14:47 UTC, anjosluc commented on variables.tf
> +  description = "Option to disable EventBridge Lambda trigger, useful to stop automatic updates of binary distribution"
done

2023-03-01 14:57 UTC, npalm approved these changes

2023-03-01 14:57 UTC, npalm commented
@anjosluc thanks for your contribution!

2023-03-01 14:58 UTC, merged