feat(syncer): Enable S3 bucket versioning for syncer S3 bucket
philips-labs/terraform-aws-github-runner pull request #3108
Opened 2023-03-24 17:24 UTC by reedloden

Many compliance obligations require S3 bucket versioning be enabled in order to meet specific integrity and availability controls.

Considering the limited objects in this bucket and minimal cost associated with keeping any versions, enabling it by default.

2023-03-30 20:41 UTC, npalm requested changes

2023-03-30 20:41 UTC, npalm commented on modules/runner-binaries-syncer/main.tf
> +    status = "Enabled"
I don't see any good readon to version this bucket. It is just a cache. Version the bucket will result in the runner wil use the latest available version. Unless you update the runner start script. If you are subject to regulation it might be better to build a custom AMI to control the version.

But supporting versioning for this bucket is fine. Would suggest that you a variable to allow users to enable versioning.

This requires 
- Adding a variable support the values of the field Status, with default `Disabled`
- Add the variable to the root, runner-binary-syncer and multi runner.
- Naming suggestion: top-level and multi-runner runner_binaries_s3_versioning, and on the module it self  s3_versioning

2023-03-31 05:54 UTC, reedloden commented on modules/runner-binaries-syncer/main.tf
> +    status = "Enabled"
I implemented the ability to configure S3 bucket versioning as you requested. Let me know if that works for you.

2023-04-18 22:17 UTC, npalm requested changes
@reedloden thanks the PR is good. But added two small suggestion to the docs to indicate the change cannot be reverted via Terraform. I also fixed some conflicts by main. Removed the terraform docs from the readme, they will be generated once on the release branch. You can also enable the CI on your fork (even better), this will ensure the docs will be re-created.

2023-04-18 22:17 UTC, npalm commented on variables.tf
> +  description = "Status of S3 versioning for runner-binaries S3 bucket."
```suggestion
  description = "Status of S3 versioning for runner-binaries S3 bucket. Once set to Enabled the change cannot be reverted via Terraform!"
```

2023-04-18 22:17 UTC, npalm commented on modules/multi-runner/variables.tf
> +  description = "Status of S3 versioning for runner-binaries S3 bucket."
```suggestion
  description = "Status of S3 versioning for runner-binaries S3 bucket. Once set to Enabled the change cannot be reverted via Terraform!"
```

2023-05-05 14:05 UTC, GuptaNavdeep1983 approved these changes

2023-05-05 16:20 UTC, npalm approved these changes

2023-05-05 16:21 UTC, merged