feat(lambda): Add support for X-Ray tracing
philips-labs/terraform-aws-github-runner pull request #3142
Opened 2023-03-31 15:15 UTC by mcaulifn

Add support for x-ray

2023-03-31 16:07 UTC, mcaulifn commented
@npalm Not sure what is up with the tfdocs workflow

2023-03-31 16:22 UTC, koendelaat commented
> @npalm Not sure what is up with the tfdocs workflow

I was facing the same issue.
I've resolved it here: https://github.com/philips-labs/terraform-aws-github-runner/pull/3143/commits/e70bf2ff109ad068d1d80553be1a5537f888c6b3

2023-03-31 22:39 UTC, npalm commented
I recently move the update of the tfdocs to the release branch. But this conflicts with the pre-commit hook with tfdocs. So therefore I removed the pre-commit. And run the workflow on the PR. But that seems not working. Will dig in next week.

2023-04-01 10:50 UTC, npalm commented on .github/workflows/update-docs.yml
> +        if: github.event.pull_request.head.repo.full_name == github.repository
This will avoid to generate docs for PR's at all. Which means it does almost make no sense to run the workflow on the pull_request event.

Just created a PR to run the docs action on branches. For forks that have actions enabled it will update the docs. If not enabled no impact. And docs will updated once released (or via PR to main).

See https://github.com/philips-labs/terraform-aws-github-runner/pull/3144

What do you think?

2023-04-01 13:15 UTC, mcaulifn commented on .github/workflows/update-docs.yml
> +        if: github.event.pull_request.head.repo.full_name == github.repository
Removing these fixes in favor of yours.

2023-04-05 04:43 UTC, npalm reviewed
Looks good, will check in detail later. But it seems you missed the pool lambda, which is in as submodule of the runners.

2023-04-07 16:23 UTC, npalm reviewed
@mcaulifn thx, I ran a quick test and only see tracing for the scale-down, not for the scale-up. Need to dig in a bit more next wee. 

Besides that can you also add the tracing variable to multi-runner module.

2023-04-10 18:59 UTC, mcaulifn commented
Added to multi- and pool.

2023-04-19 11:07 UTC, npalm requested changes
Tested and got a working with some tweaks:

- multi-runner module file runner-binaries.tf add `lambda_tracing_mode = var.lambda_tracing_mode`
- multi-runner module file webhook.tf add `lambda_tracing_mode = var.lambda_tracing_mode`
- missed a policy for the pool see inlince comment.

changes also available on branch https://github.com/philips-labs/terraform-aws-github-runner/tree/mcaulifn/xray

2023-04-20 11:06 UTC, npalm commented
> Tested and got a working with some tweaks:
> 
> * multi-runner module file runner-binaries.tf add `lambda_tracing_mode = var.lambda_tracing_mode`
> * multi-runner module file webhook.tf add `lambda_tracing_mode = var.lambda_tracing_mode`
> * missed a policy for the pool see inlince comment.
> 
> changes also available on branch https://github.com/philips-labs/terraform-aws-github-runner/tree/mcaulifn/xray

@mcaulifn just pushed my addition to your branch

2023-04-20 11:07 UTC, npalm approved these changes

2023-04-20 11:09 UTC, merged