chore(ci) - fix tf-docs on PR
philips-labs/terraform-aws-github-runner pull request #3144
Opened 2023-04-01 08:08 UTC by npalm

2023-04-01 13:15 UTC, mcaulifn approved these changes
I like ! :shipit:

2023-04-03 20:43 UTC, GuptaNavdeep1983 requested changes

2023-04-03 20:43 UTC, GuptaNavdeep1983 commented on CONTRIBUTING.md
>  * Install [Terraform](https://www.terraform.io/). We lock the version with [tvenv](https://github.com/tfutils/tfenv), check `required_version` in `versions.tf` for the current development version of
```suggestion
* Install [Terraform](https://www.terraform.io/). We lock the version with [tfenv](https://github.com/tfutils/tfenv), check `required_version` in `versions.tf` for the current development version of the module.
```

2023-04-03 21:40 UTC, GuptaNavdeep1983 approved these changes

2023-04-05 04:39 UTC, merged