Make the VPC and Subnet ID configurable for multi runner
philips-labs/terraform-aws-github-runner pull request #3196
Opened 2023-04-19 07:49 UTC by prashanthbgoud

2023-04-19 11:15 UTC, npalm commented on modules/multi-runner/runners.tf
> +  vpc_id        = each.value.runner_config.vpc_id
Could you try someting like this. If `each.value.runner_config.vpc_id` is not set set var.vpc_id. An dsimilar for the subnets

By doing this we can keep the change non breaking. And it avoid in many cases extra configuration.

2023-04-21 08:38 UTC, prashanthbgoud commented on modules/multi-runner/runners.tf
> +  vpc_id        = each.value.runner_config.vpc_id
I will have a look today

2023-04-25 07:32 UTC, prashanthbgoud commented
@npalm can you have a look?

2023-05-09 14:58 UTC, GuptaNavdeep1983 approved these changes

2023-05-12 19:37 UTC, npalm requested changes
some small suggestions

2023-06-30 11:27 UTC, npalm commented
@prashanthbgoud is the PR still relevant?

2023-08-30 01:46 UTC, closed without merging