feat: Add var.runner_credit_specification
philips-labs/terraform-aws-github-runner pull request #3244
Opened 2023-05-02 06:40 UTC by alexjurkiewicz

Allow configuring T instance types as explicitly standard or unlimited
credit model.

This can help to control costs when using T instances as a "cpu-limited"
runner pool.

2023-05-03 12:43 UTC, GuptaNavdeep1983 submitted a review, later dismissed

2023-05-04 16:58 UTC, npalm requested changes
Thanks looks good in general, one change request. The runners can be created from the root and the submodule multi-runners

2023-05-04 16:58 UTC, npalm commented on modules/runners/variables.tf
> +variable "credit_specification" {
Please can you add the variable also to the module multi-runner. Please define the variable on the level of the runner_config https://github.com/philips-labs/terraform-aws-github-runner/blob/97c4ee7d1145c5f10ea01bbe4a81e1e6e827cef9/modules/multi-runner/variables.tf#L30

Would set the default to null, and ensure you pass the variable in the module via runners.tf in this module

2023-05-06 00:47 UTC, alexjurkiewicz commented on modules/runners/variables.tf
> +variable "credit_specification" {
done

2023-05-08 14:56 UTC, GuptaNavdeep1983 commented on modules/runners/variables.tf
> +variable "credit_specification" {
@alexjurkiewicz, I dont think that this is what Niek mentioned in his comment. In this case, same config will apply 

You have defined the variable at the level of the multi runner module but inside multi runner module, there is a variable multi_runner_config which defines the config for all individual runner configs supported by this module. Its this location under which he requested you to create this variable from where it can be controlled for individual runner configs. As of now the same credit specification would apply to all runner configs.

2023-05-09 09:27 UTC, alexjurkiewicz commented on modules/runners/variables.tf
> +variable "credit_specification" {
my bad, I understand now! I've made the requested change

2023-05-10 11:56 UTC, GuptaNavdeep1983 commented
Tested the changes and they look good. Thanks.

2023-05-11 20:22 UTC, npalm approved these changes

2023-05-12 19:32 UTC, merged