feat: Ephemeral runners - integration with new GitHub API
philips-labs/terraform-aws-github-runner pull request #3350
Opened 2023-07-03 21:32 UTC by GuptaNavdeep1983

2023-07-17 15:36 UTC, GuptaNavdeep1983 commented on examples/multi-runner/main.tf
> -  #  Alternative to loading runner configuration from Yaml files is using static configuration:
removed commented code.

2023-07-17 19:17 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.d.ts
>  export interface RunnerInputParameters {
runners module doesnt create the ssm parameter anymore, hence removed those fields.

2023-07-17 19:26 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.ts
>    TerminateInstancesCommand,
creation of ssm parameters have moved to scale-up module.

2023-07-17 19:26 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.ts
> +  return instances;
moved to scale-up module.

2023-07-17 19:28 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +async function getRunnerGroupId(githubRunnerConfig: CreateGitHubRunnerConfig, ghClient: Octokit): Promise<number> {
this function gets the runner group id for the given runner group name either from github or from ssm, attempts to get it from ssm first and if not found from github.

2023-07-17 19:28 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +async function GetRunnerGroupByName(ghClient: Octokit, githubRunnerConfig: CreateGitHubRunnerConfig): Promise<number> {
gets the runner group name from github.

2023-07-17 19:29 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> -  const token = await getGithubRunnerRegistrationToken(githubRunnerConfig, ghClient);
moved from here to the function responsible for creating token.

2023-07-24 11:54 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +      runnerGroup = await getParameter(
This still requires an extra call to SSM for every runner we create. An idea for improment ould be whne the groupId is provided we not store it in ssm. What do you think, address this in an issue as improvement?

2023-07-24 12:03 UTC, npalm requested changes

2023-07-24 12:03 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +      runner_jit_config: runnerConfig.data.encoded_jit_config,
Is the jit config sensible data?

2023-07-24 12:03 UTC, npalm commented on modules/runners/variables.tf
>    default     = ""
Should we not make the variable required now we expect ALL labels?

2023-07-24 12:03 UTC, npalm commented on lambdas/functions/control-plane/src/aws/runners.test.ts
> -  it('calls create fleet of 40 instances (ssm rate limit condition) to test time delay ', async () => {
I think this test case is not move, correct?

2023-07-24 12:11 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.test.ts
> -  it('calls create fleet of 40 instances (ssm rate limit condition) to test time delay ', async () => {
this is moved to scale-up.test.ts

2023-07-24 12:17 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +  const runnerLabels = process.env.RUNNER_LABELS || '';
can be changed now.

2023-07-24 12:26 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +      runnerGroup = await getParameter(
will create an issue.

2023-07-24 12:29 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +      runnerGroup = await getParameter(
https://github.com/philips-labs/terraform-aws-github-runner/issues/3379

2023-07-25 12:06 UTC, npalm approved these changes

2023-07-25 12:31 UTC, merged

2023-07-25 13:24 UTC, mariusfilipowski commented
Will this break support for GitHub Enterprise? There seems to be no support for JIT yet.

2023-07-27 00:51 UTC, jkruse14 commented
This breaks ephemeral runners. When running with `enable_ephemeral_runners = true`, I get:

```
<13>Jul 26 23:57:02 user-data: Starting runner after 0:1:32
<13>Jul 26 23:57:02 user-data: Starting the runner as user ec2-user
<13>Jul 26 23:57:02 user-data: Starting the runner in ephemeral mode
[   92.500730] cloud-init[2611]: ci-info: no authorized ssh keys fingerprints found for user ec2-user.
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
<snip>
[   92.562938] cloud-init[2611]: Cloud-init v. 19.3-46.amzn2.0.1 finished at Wed, 26 Jul 2023 23:57:02 +0000. Datasource DataSourceEc2.  Up 92.55 seconds
<13>Jul 26 23:57:03 user-data: Unrecognized command-line input arguments for command run: 'ephemeral, url, token, runnergroup'. For usage refer to: .\config.cmd --help or ./config.sh --help
<13>Jul 26 23:57:03 user-data: An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
<13>Jul 26 23:57:03 user-data: Runner listener exit with terminated error, stop the service, no retry needed.
<13>Jul 26 23:57:03 user-data: Exiting runner...
```

Notice:
**user-data: Unrecognized command-line input arguments for command run: 'ephemeral, url, token, runnergroup'. For usage refer to: .\config.cmd --help or ./config.sh --help
**

setting `enable_ephemeral_runners = false` allows it to work. The difference is non-ephemeral runners do not use jitconfig

Also of note, I'm using the multi-runner config.