Add eviction strategy to idle config
philips-labs/terraform-aws-github-runner pull request #3375
Opened 2023-07-20 19:50 UTC by maschwenk

We do some on-instance caching so when we scale down we'd prefer to keep the older instances around instead of the new ones (because they will have a hotter cache). This adds a configurable setting to the idleConfig to pick a sorting strategy. Never contributed to this repo, so please tell me if I'm doing something wrong!

2023-07-20 19:54 UTC, maschwenk commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +      .sort(evictionStrategy === 'oldest_first' ? oldestFirstStrategy : newestFirstStrategy)
We default to the existing strategy of `oldest_first` by default

2023-07-21 17:48 UTC, maschwenk commented
@npalm I rebased and fixed the prettier failures as well as one typecheck failure. I'm running into failures for tests because of missing type coverage. Will wait to make sure you approve of the approach before proceeding to write tests.

2023-07-23 09:45 UTC, npalm commented
> @npalm I rebased and fixed the prettier failures as well as one typecheck failure. I'm running into failures for tests because of missing type coverage. Will wait to make sure you approve of the approach before proceeding to write tests.

Thanks for the PR. WIll check the approach ASAP.

2023-07-24 07:03 UTC, GuptaNavdeep1983 commented
@maschwenk one of the test case is failing for this PR. Can you please fix that?

2023-07-24 07:08 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +  if (a.launchTime === undefined) return 1;
You can use here oldestFirstStrategy, for example

```return oldestFirstStrategy(a, b) * -1;```

2023-07-24 07:10 UTC, npalm reviewed
The approach looks good to me. I understand the idea of keeping caches aroudn. But we see this as a risk as well. Supporting this eviction strategy is fine as long you esnure you add a test case.

2023-07-24 14:25 UTC, maschwenk commented
@npalm 👍🏼 sounds good. Will fix.

2023-07-24 17:47 UTC, maschwenk commented
@npalm I've added a test to make sure the default config is extracted correctly

@GuptaNavdeep1983 took on your suggestion as well 👍🏼

2023-07-24 17:48 UTC, maschwenk commented on lambdas/functions/control-plane/src/scale-runners/scale-down-config.ts
> +  evictionStrategy?: EvictionStrategy;
I changed this to be an optional type so that nobody needs to mess with their existing TF config and make sure that the types are accurate (because we do a cast)

2023-07-24 17:50 UTC, maschwenk commented on lambdas/functions/control-plane/src/scale-runners/scale-down-config.ts
> +      return scalingDownConfig.evictionStrategy ?? 'oldest_first';
This ensures we always default to `oldest_first` in both the case of not configuring and also being outside of the cron window

2023-07-25 15:16 UTC, maschwenk commented
@npalm Ahh I just realized it's failing due to the test coverage? I couldn't figure out why before. Happy to add a bit of coverage.

2023-07-26 01:45 UTC, maschwenk commented
@npalm Added a test in `lambdas/functions/control-plane/src/scale-runners/scale-down.test.ts` to get the coverage level to acceptable

2023-07-26 19:02 UTC, maschwenk commented
@npalm 😅 the Code health thing did not like some duplication I had, cleaned that up. This should be ready for review! 🙏🏼

2023-07-28 12:21 UTC, maschwenk commented
@npalm should be ready for another look 🙏🏼 sorry for the churn

2023-07-31 09:09 UTC, npalm requested changes
Changes to the Lambda looks good. But also the Terraform code needs to be adjusted to pass the variable to the lambda.

Can you update:
- variables files in root module, runner module and multi-runner module
- Suggest to add an `optional(string)` or `optional(string, "oldest_first)`.
- The README in the root explains the idle_config, can you update this section as well

2023-07-31 09:09 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down-config.ts
> +  for (const scalingDownConfig of scalingDownConfigs) {
Can you add a debug logger line here that writes which strategy will be applied?

2023-08-02 03:42 UTC, maschwenk commented
@npalm Added all that here I think [3c7d840](https://github.com/philips-labs/terraform-aws-github-runner/pull/3375/commits/3c7d8404157b219881ee79f68012904c05354007)

Unsure how best to edit the READMEs with the HTML. Formatting there is a bit rough. Let me know if there's anything I missed. I had missed the note in the CONTRIBUTING.md to allow the Actions to run on my fork, now a bit easier to see how things are working.

2023-08-02 07:21 UTC, npalm commented on README.md
> +   # for example if the oldest runners have a long-living cache
Looks like in that case you would remove the newest first

2023-08-02 07:24 UTC, npalm commented on README.md
Can you add here a sentence like:

By default the oldest istances are removed. This helps to keep your environment up-to-date and reduce problems as full disks or memory issues. You can overwrite this behavior by setting the `evictionStrategy`.

2023-08-02 07:25 UTC, npalm reviewed
Looks in gneral good, a few remarks. Will test asap

2023-08-02 15:03 UTC, maschwenk commented
@npalm I think my comment above the eviction strategy was more confusing so I just moved it up into the paragraph above to give a more thoughtful explanation. Completely aside from the point of this PR, your note of:

> This helps keep your environment up-to-date and reduce problems like running out of disk space or RAM

The disk space clause makes sense to me, but I'd be curious how often your instances are carrying around "dead" RAM after jobs run on them? We definitely have RAM issues but because we don't run things containerized it often just toasts the box completely and we take it out of rotation versus leaking over time. Just curious about your experience there. Thanks for reviewing!

2023-08-04 14:59 UTC, maschwenk commented
@npalm were you able to take a look?

2023-08-04 16:08 UTC, npalm commented
> @npalm were you able to take a look?

Sorry not yet, seems also the coerage is dropped slightly. I wil have a look early next week

2023-08-04 20:32 UTC, npalm commented
Just ran the test suite locally, but see no coverage error. Will have a check later.

2023-08-05 11:20 UTC, npalm commented
> Just ran the test suite locally, but see no coverage error. Will have a check later.

Re-ran the build, seems no fine.

2023-08-08 16:23 UTC, npalm approved these changes
@maschwenk thx for your contribution

2023-08-08 16:24 UTC, merged

2023-08-08 18:15 UTC, maschwenk commented
@npalm I'm seeing those failures you are getting on master, I think I have an idea of why they are happening. Will upstream a change if I figure it out.

2023-08-08 20:40 UTC, npalm commented
Do you mean the release build on main? For some reason the build is randomly failing. I have no clue why (yet). The documentation build is another problem. And a less a big issue. Do you have any clue why the release build is failing when building all lambda's?

2023-08-08 21:16 UTC, maschwenk commented
> Do you mean the release build on main? For some reason the build is randomly failing. I have no clue why (yet). The documentation build is another problem. And a less a big issue. Do you have any clue why the release build is failing when building all lambda's?

@npalm I don't yet, but my test was mutating `process.env`, so I was thinking perhaps the mutation was polluting global state. Haven't been able to repro locally. It's also odd because the stack-trace is pretty useless, not clear what the actual error is, just shows where it's coming from.

2023-08-09 04:01 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.test.ts
> +          process.env.SCALE_DOWN_CONFIG = JSON.stringify([{ ...defaultConfig, evictionStrategy: 'newest_first' }]);
@maschwenk Your suggestion is right. We need to ensure SCALE_DOWN_CONFIG is alwasy set to the default / undefined before the test. Can you add tot the most outer before the statement process.env.SCALE_DOWN_CONFIG = 'oldest_first'

2023-08-09 08:55 UTC, npalm commented
I think I have solved the issue in #3418

2023-08-09 08:58 UTC, npalm commented
Not yet, still failing

2023-08-09 21:13 UTC, npalm commented
@maschwenk I have tried earlier today to fix the test. I am not able to reproduce the failing test on my local. Assume it has something to do with the order. I added the SCALE_DOWN_CONFIG to other test to ensure the value is set right. At some moment got a error the coverage was not metting our settings. Fixed that as well. THought it was all good. But now the main is failing again. So ondering if you have still any ieda.

2023-08-10 14:52 UTC, maschwenk commented
@npalm still at a little bit of a loss. Is there any way we can get better logs out of the failing tests perhaps? Or maybe try forcing the Jest test to run in an order that will deterministically fail?

2023-08-10 20:12 UTC, npalm commented
Yes we can set a few things in jest (at least)
- verbose -> true
- silent -> false
- define reporters. and save as artiefact (retention 1 day).

I will also dig in a bit more next week.

2023-08-15 14:55 UTC, npalm commented
This PR should fix the issue: #3432

2023-08-15 14:57 UTC, maschwenk commented
@npalm ❤️