support for cloudwatch config on multi-runners
philips-labs/terraform-aws-github-runner pull request #3447
Opened 2023-08-23 10:06 UTC by piscue

2023-08-23 10:11 UTC, piscue commented
@npalm could you take a look on this one?

2023-08-23 12:06 UTC, npalm requested changes
Looks good, see comment with a suggestion

2023-08-23 12:06 UTC, npalm commented on modules/multi-runner/runners.tf
> +  cloudwatch_config                = each.value.runner_config.cloudwatch_config
Can you change this to something like

```coalesce(each.value.runner_config.cloudwatch_config, var.cloudwatch_config)```


And update the docs of both variables/

2023-08-23 12:54 UTC, piscue commented on modules/multi-runner/runners.tf
> +  cloudwatch_config                = each.value.runner_config.cloudwatch_config
I did the update and the doc I've found. The rest of the documentation seems to exist already.

2023-08-23 20:01 UTC, npalm reviewed
Looks god, wil run asap a quick test

2023-08-24 07:27 UTC, npalm approved these changes

2023-08-24 07:28 UTC, merged