feat: Adding runner_enable_default_labels variable
philips-labs/terraform-aws-github-runner pull request #3491
Opened 2023-09-21 10:27 UTC by jgutierrezglez

In case the pool of runners deployed using this module are fully available for an wide GH org (no repository restrictions) any workflow configured to run in runners that contain just default labels in the runs-on definition:

e.g.

`runs-on: self-hosted`
`runs-on: Linux`

can end-up running in this pool without knowing it. That's why I have decided to remove the default labels from our runners and just rely on unique custom labels, and I believed the best way to do it by adding a runner_enable_default_labels variable - that by default is true (so, it doesn't change the current behavior), but it can help other people to deal with similar issues like the one described above.

2023-09-21 12:36 UTC, npalm commented
I think I missed GitHub changes this. In the past the default labels are added by GitHub without control. When we introduced the JIT config the default labels are not added by default. But is this the same for non JIT?

2023-10-04 12:44 UTC, jgutierrezglez commented
> I think I missed GitHub changes this. In the past the default labels are added by GitHub without control. When we introduced the JIT config the default labels are not added by default. But is this the same for non JIT?

We're using JIT - and the default labels are added by default, that's why we have created this new variable and set it to false in the cases where we just want to use custom labels

2023-10-05 06:23 UTC, npalm reviewed
Need to find some time to test.

- Changes impacted the runner module should also reflected to the multi-runner module. See comment
- I think this option requires that JIT config is enabled. Can you hadd this to the docs of the introduced variable.

2023-10-05 06:23 UTC, npalm commented on main.tf
> +  runner_labels         = !var.runner_enable_default_labels ? var.runner_extra_labels : var.runner_extra_labels != "" ? "${local.default_runner_labels},${var.runner_extra_labels}" : ""
This change should also be reflected to the mult-runners. This module can be used as root module as well.

See https://github.com/philips-labs/terraform-aws-github-runner/blob/35aa73ac1e6df30d4a5c314457da5646a117131b/modules/multi-runner/runners.tf#L47

2023-11-01 23:25 UTC, sdarwin commented
For the reasons explained in the original post, this feature would be great, so you can enable runners without repository restrictions.  

`runs-on: self-hosted` won't accidentally trigger a launch if only custom labels have been added.  

Maybe I am mistaken (and I might be!) but here are a few quick comments:

1. This appears to be the pull request adding the feature: https://github.com/actions/runner/pull/2443

2. It doesn't mention JIT config.  Isn't JIT completely orthogonal to default labels? Unrelated.  So remove JIT from this PR.

3.  The feature uses the flag `--no-default-labels`.   Where is the flag `--no-default-labels` in this PR?

2023-12-08 08:08 UTC, npalm commented
Sorry we had no time yet to dig in this PR. I do my best to check the PR in the coming week. Sorry for the delay.

2024-06-27 00:58 UTC, jeff-wassouf commented
Hi @npalm, any update on this PR? This will help us a lot once merged. Thank you.

2024-07-26 12:11 UTC, iotanum commented
hello, any updates on this? would be a huge help!

2024-08-27 16:16 UTC, jgutierrezglez commented
Hello @npalm, 

Is there something that we can do to speed-up the review / merge of this change ? 

Regards,

Javier G.

2024-08-29 13:11 UTC, npalm commented
sorry, shame on me. But the whole label stuff is become so complex over the years. I am a bit afraid of breaking tings. I need to have some focus time to dig in the topic deep. And maybe we should also think on how we can grow the maintainer pool of this module.

2024-08-29 18:14 UTC, iotanum commented
I've been using up-to-date module with these custom label changes for my organization for the past month, didn't encounter any issues (using another module for another AWS organization in the same GitHub org)

2024-08-30 14:25 UTC, sdarwin commented
@jgutierrezglez 

- At least in your own opinion, is this PR ready to merge?

- The github feature itself is implemented with the command-line flag `--no-default-labels` .   Otherwise default labels are added.  Please correct me if I am wrong...  How is `--no-default-labels`  not mentioned in the files of this pull request?  Without it, default labels would be applied.

2024-09-03 10:15 UTC, jgutierrezglez commented
> At least in your own opinion, is this PR ready to merge?

I really think it's ready for review. We have been using this changes in our own version of the module for more than a year without no issue (ephemeral runners)

> The github feature itself is implemented with the command-line flag --no-default-labels . Otherwise default labels are added. Please correct me if I am wrong... How is --no-default-labels not mentioned in the files of this pull request? Without it, default labels would be applied.

I don't really understand what you mean with this..the way how I implemented is:

runner_enable_default_labels var is set to true by default, so, by default nobody should notice any change. In case you set this var to false, it's when the default labels won't be added to the runner_labels var

2024-09-03 14:51 UTC, sdarwin commented
@jgutierrezglez , let's continue from this scenario:  "In case you set this var to false, it's when the default labels won't be added to the runner_labels var"

Perhaps the default labels won't be added to the runner_labels var.  That variable is 'internal' to terraform, at least one some level. It's part of terraform. But we have to ask: what about the actual real runners themselves?  Notice these references:

https://github.com/actions/runner/pull/2443 "Add --no-default-labels config option to self-hosted runners"

https://stackoverflow.com/questions/75330363/remove-default-labels-on-github-self-hosted-runner "Remove default labels on self-hosted runners"
```
The support for not adding default labels to self-hosted runners, was added in this PR:
https://github.com/actions/runner/pull/2443
It should become available in the next stable release that includes this change.
To use it, pass in:
--no-default-labels
``` 

How are you bypassing the usage of "--no-default-labels"?   It's not mentioned in this pull request.   Without applying "--no-default-labels" (which previously was not available), the runner will always apply your custom labels + the default labels, so you would always get the default labels + the custom labels, on the runner.

Investigating more, "--no-default-labels" is a flag on config.sh.  

config.sh is called in `modules/runners/templates/start-runner.sh`.  Rather than applying all the time, it is used "if the runner is non ephemeral or jit config is disabled".

Otherwise, `--jitconfig $${config}` is used.

Ok...  So from this perspective, maybe your code changes are working after all.  Great.   Perhaps they are effective with `--jitconfig $${config}` . But, still broken if `config.sh` is called.   Because `config.sh` requires "--no-default-labels".   Do you agree?

2024-09-11 01:51 UTC, sdarwin commented
I don't understand how there is any connection between a new method of terraform variable validation, and what ought to be done here: 

conditionally adding the "--no-default-labels" flag to `config.sh`.

2024-09-14 20:04 UTC, sdarwin commented
In the absence of automated CI tests, how about manual testing. 

Run through these cases and report back the findings. Not what might be expected, but what the test show.  Post screen shots perhaps.  

Let's say your chosen labels are [a,b,c]. We'll call them my_custom_labels. You can use any that you prefer. 

Check in the Github control panel UI at https://github.com/_my_org_/_my_repo_/settings/actions/runners to see what labels are ultimately applied by Terraform. Let's call that "real resulting labels".  

Fill in the blanks.  

| runner_enable_default_labels | your labels  | enable_jit_config | enable_ephemeral_runners | real resulting labels |
| ---- | ---- | ---- | ---- | ---- |
| true | my_custom_labels | false | false | |
| true | my_custom_labels | false | true | |
| true | my_custom_labels | true | false | |
| true | my_custom_labels | true | true  | |
| false | my_custom_labels | false | false | |
| false | my_custom_labels | false | true | |
| false | my_custom_labels | true | false | |
| false | my_custom_labels | true | true  | |

If all eight tests are correct, hopefully the maintainers will agree the PR is ready.

2024-09-15 12:00 UTC, sdarwin commented
Windows `modules\runners\templates\start-runner.ps1` with `config.cmd` is missing.

2024-09-20 16:40 UTC, sdarwin commented
How about this instead?

```
if [[ "$default_labels" == "true" ]]; then
    extra_flags="--no-default-labels"
else
    extra_flags=""
fi

sudo --preserve-env=RUNNER_ALLOW_RUNASROOT -u "$run_as" -- ./config.sh ${extra_flags} --unattended --name "$runner_name_prefix$instance_id" --work "_work" $${config}
```

2024-10-04 09:39 UTC, npalm requested changes
Thx the PR already looks quite good. But made some comments to suggest different names. Please can you also update the following parts.

- Update the windows start script to read the parameter
- Update docs, add the paramater: https://philips-labs.github.io/terraform-aws-github-runner/configuration/#aws-ssm-parameters
- Update the multi-runner module to pass the parameter down.

2024-10-04 09:39 UTC, npalm commented on modules/runners/runner-config.tf
> +resource "aws_ssm_parameter" "default_labels" {
I think a better name is `disable_default_labels` this indicates that the paramater is a boolean, and is in line with the agent paramater (diable -> no-default).

2024-10-04 09:39 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +  sudo --preserve-env=RUNNER_ALLOW_RUNASROOT -u "$run_as" -- ./config.sh ${extra_flags} --unattended --name "$runner_name_prefix$instance_id" --work "_work" $${config}
```suggestion
  sudo --preserve-env=RUNNER_ALLOW_RUNASROOT -u "$run_as" -- ./config.sh $${extra_flags} --unattended --name "$runner_name_prefix$instance_id" --work "_work" $${config}
```

2024-10-04 09:39 UTC, npalm commented on modules/runners/variables.tf
> +  validation {
This is breaking, we don't know if someone is using the module with extra labels. Condition cannot be scoped outside the variable to check if default labels are disabled. 

I would remove the condition for now, and create issue to see if we can use pre-conditions checks to validate the labels array is set.

2024-10-04 09:39 UTC, npalm commented on modules/runners/variables.tf
> +variable "runner_enable_default_labels" {
Can you rename this to `runner_disable_default_labels`

2024-10-04 09:39 UTC, npalm commented on variables.tf
> +variable "runner_enable_default_labels" {
Variables introduced on top-level also needs to be defined in the multi-runner module. 

See also previous comment for naming.

2024-10-07 15:26 UTC, npalm commented
@jgutierrezglez feel free to grant maintainers access to write to the PR branch. There is a checkbox you can tick to that. In that case I can push my updates used for local testing as well.

2024-10-07 15:43 UTC, jgutierrezglez commented
> @jgutierrezglez feel free to grant maintainers access to write to the PR branch. There is a checkbox you can tick to that. In that case I can push my updates used for local testing as well.

It's already enabled, you should be able to push your updates

2024-11-06 22:10 UTC, mohramadan911 commented
Is this merged already ? we are really looking forward for this PR as soon as possible- we need to separate our runners so self-hosted will act for all jobs but only runners with dependabot label

2024-11-07 13:20 UTC, jgutierrezglez commented
@npalm do you need any change from my side in order to approve this PR?

2024-11-12 14:51 UTC, mohramadan911 commented
> @npalm do you need any change from my side in order to approve this PR?



> npalm

Do you think this PR can be released soon ?

2024-11-12 15:46 UTC, sdarwin commented
> do you need any change from my side in order to approve this PR?

On Oct 4, he mentioned certain requirements. For example this has not yet been done: "Update the windows start script to read the parameter".    Check the other notes from there.

2024-11-14 10:59 UTC, jgutierrezglez commented
Update the windows start script to read the parameter is done already, and I reviewed the rest of them, and normally all the remarks have been already implemented. @npalm could you check again let me know if you have any comment or remark about the last changes?

2024-11-14 14:32 UTC, npalm commented
Planned to check the PR tomorrow.

2024-11-15 12:18 UTC, npalm requested changes
@jgutierrezglez thanks for this great PR. I have tested several cases

- [ ] Default runner - works, requires a suggested change on defaults
- [x] Multi runner (linux) 
- [ ] Multi runner (linux) - with JIT
- [ ] Multi runner (windows)

For the multi runner I needed to make the follwoing adjusments:

1. mutli-runner module runners.tf

Pass parametr into runner module:
```  
runner_disable_default_labels        = each.value.runner_config.runner_disable_default_labels
```

and avoid setting defaults if labels are disabled.
```
  runner_labels                        = each.value.runner_config.runner_disable_default_labels ?  sort(distinct(each.value.runner_config.runner_extra_labels)) :  sort(distinct(concat(["self-hosted", each.value.runner_config.runner_os, each.value.runner_config.runner_architecture], each.value.runner_config.runner_extra_labels)))
```

I would say the PR is getting close to merge. To get it faster passed you could split the PR in two parts. First the linux part adding the feature, next another PR to fix the windows part.

2024-11-15 12:18 UTC, npalm commented on modules/runners/templates/start-runner.ps1
> +        if ($disable_default_labels -eq "true") {
I think all cases should support the default labels. I tried testing based on the multi-runner example. Bot got windows not working. 

I have tried some uupdates on the powershell script, but for some reason the runner starts but just applyting the diable label switch:

<img width="1055" alt="Screenshot 2024-11-15 at 12 58 06" src="https://github.com/user-attachments/assets/cd01ca75-7ac8-4758-bf72-ef624cbcd561">

I changed the Window script as follow:

```powershell
$runnerExtraOptions = ""
if ($disable_default_labels -eq "true") {
    $runnerExtraOptions += "--no-default-labels"
}

if ($agent_mode -eq "ephemeral") {
    if ($enable_jit_config -eq "true") {
        Write-Host "Starting with jit config"
        Invoke-Expression ".\run.cmd --jitconfig $${config}"
    }
    else {
        Write-Host "Starting without jit config and with default labels with runnerExtraOptions: $runnerExtraOptions"
        Invoke-Expression ".\run.cmd $runnerExtraOptions"
    }
    Write-Host "Runner has finished"

    if ($enable_cloudwatch_agent)
    {
        Write-Host "Stopping CloudWatch Agent"
        & 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a stop
    }

    Write-Host "Terminating instance"
    aws ec2 terminate-instances --instance-ids "$InstanceId" --region "$Region"
} else {
    if ($runnerExtraOptions) {
        $runnerArguments = "-Argument $runnerExtraOptions"
    }
    Write-Host "Installing the runner as a service with runnerArguments: $runnerArguments"

    $action = New-ScheduledTaskAction -WorkingDirectory "$pwd" -Execute "run.cmd" $runnerArguments
    $trigger = Get-CimClass "MSFT_TaskRegistrationTrigger" -Namespace "Root/Microsoft/Windows/TaskScheduler"
    Register-ScheduledTask -TaskName "runnertask" -Action $action -Trigger $trigger -User $username -Password $password -RunLevel Highest -Force
    Write-Host "Starting runner after $(((get-date) - (gcim Win32_OperatingSystem).LastBootUpTime).tostring("hh':'mm':'ss''"))"
}

```

And test the non ephemeral case, but this was not working
 
<img width="846" alt="Screenshot 2024-11-15 at 12 58 41" src="https://github.com/user-attachments/assets/4c8f45ac-d9e9-47da-83e3-1746f230226e">

2024-11-15 12:32 UTC, jgutierrezglez commented on variables.tf
> +  validation {
We can do it, but that will require the upgrade of the TF version required: https://www.hashicorp.com/blog/terraform-1-9-enhances-input-variable-validations

2024-11-15 12:35 UTC, jgutierrezglez commented on modules/runners/templates/start-runner.ps1
> +        if ($disable_default_labels -eq "true") {
As you suggested, I'll address this issue on a new PR dedicated to fix the issue with Windows

2024-11-15 12:45 UTC, jgutierrezglez commented
@npalm https://github.com/philips-labs/terraform-aws-github-runner/pull/4261 PR to address the Windows fix

2024-11-15 12:59 UTC, sdarwin commented
@jgutierrezglez , this is a question rather than definitely something needs to change, but why does it say `$${extra_flags}` instead of `${extra_flags}` in start-runner.sh?  What effect does that have?  isn't `extra_flags` a regular variable within the bash script that would have one `$`?

2024-11-15 17:30 UTC, npalm commented on variables.tf
> +  validation {
let's do that later, don't like to to drop to many versions of Terraform at once.

2024-11-15 17:36 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +  sudo --preserve-env=RUNNER_ALLOW_RUNASROOT -u "$run_as" -- ./config.sh ${extra_flags} --unattended --name "$runner_name_prefix$instance_id" --work "_work" $${config}
extra_flags needs to be escaped otherwise terraform is this expecting as a template input.


```suggestion
  sudo --preserve-env=RUNNER_ALLOW_RUNASROOT -u "$run_as" -- ./config.sh $${extra_flags} --unattended --name "$runner_name_prefix$instance_id" --work "_work" $${config}
```

2024-11-15 20:51 UTC, npalm requested changes
Made two tiny documentation suggestions. Rest looks good and tested for linux (amazon and ubuntu). 

Maybe worth to add a small section in the [docs](https://philips-labs.github.io/terraform-aws-github-runner/configuration/#configuration-considerations) to disuss the choice betwoon using default labels and disable them. 

Besides those small notes good to go 🚀

2024-11-15 20:51 UTC, npalm commented on variables.tf
> +  description = "Disable default labels for the runners (os, architecture and `self-hosted`). If enabled, the runner will only have the extra labels provided in `runner_extra_labels`."
```suggestion
  description = "Disable default labels for the runners (os, architecture and `self-hosted`). If enabled, the runner will only have the extra labels provided in `runner_extra_labels`. In case you on own start script is used, this configuration parameter needs to be parsed via SSM. For Windows no support yet."
```

2024-11-15 20:51 UTC, npalm commented on modules/multi-runner/variables.tf
> +        runner_disable_default_labels: "Disable default labels for the runners (os, architecture and `self-hosted`). If enabled, the runner will only have the extra labels provided in `runner_extra_l
```suggestion
        runner_disable_default_labels: "Disable default labels for the runners (os, architecture and `self-hosted`). If enabled, the runner will only have the extra labels provided in `runner_extra_labels`. In case you on own start script is used, this configuration parameter needs to be parsed via SSM. For Windows no support yet."
```

2024-11-18 05:48 UTC, jgutierrezglez commented
> Made two tiny documentation suggestions. Rest looks good and tested for linux (amazon and ubuntu).
> 
> Maybe worth to add a small section in the [docs](https://philips-labs.github.io/terraform-aws-github-runner/configuration/#configuration-considerations) to disuss the choice betwoon using default labels and disable them.
> 
> Besides those small notes good to go 🚀

I added a small note under "Configuration considerations" - let me know what you think about it

2024-11-18 16:39 UTC, npalm requested changes
Tested and all good, one tiny change requested

2024-11-18 21:08 UTC, npalm approved these changes

2024-11-18 21:08 UTC, merged