Document using labels with self-hosted runners
philips-labs/terraform-aws-github-runner pull request #3508
Opened 2023-09-26 17:50 UTC by sdarwin

Explanation of issue: There are many popular CI systems that exist out in the world, not only GitHub Actions. It's probably common enough that a developer comes to this project and needs to configure the Terraform runners with GitHub Actions, while also having in their mind how other systems operate, and those may be different. It's easy to imagine all runner labels must match all job labels. Other systems are designed that way. To quickly solve the problem this is a sort of cheatsheet.

2023-09-27 06:49 UTC, npalm requested changes
@sdarwin thanks for adding this extra explanation. Maybe good to link the doc from in the readme. Would use one of the first places where the readme explain the labels on a high level. Ensure you link relative

2023-09-27 06:49 UTC, npalm commented on docs/additional_notes.md
> +Some CI systems require that all labels match between a job and a runner. In the case of GitHub Actions, workflows will be assigned to runners which have all the labels requested by the workflow, how
I think expaling labels as capabilites will help as well. See it as follow the labels specifies the capabilites the runner have, and the labels in the workflow the capabilites need. If the capabailites requrest by the workflow are provided by the runnerw have a match. Can in coroprate this?

2023-09-27 15:00 UTC, sdarwin commented on docs/additional_notes.md
> +Some CI systems require that all labels match between a job and a runner. In the case of GitHub Actions, workflows will be assigned to runners which have all the labels requested by the workflow, how
Text updated

2023-09-28 08:12 UTC, npalm approved these changes

2023-09-28 08:13 UTC, merged