feat: Use Instance Metadata Service Version 2 by default.
philips-labs/terraform-aws-github-runner pull request #3513
Opened 2023-09-29 22:50 UTC by dylanmtaylor

2023-10-03 01:29 UTC, dylanmtaylor commented
We are running this module in production with this set and it works perfectly fine.

2023-10-06 07:25 UTC, npalm requested changes
Thanks, can you apply the cahnge to the mult-runner moduel as well

2023-10-06 07:25 UTC, npalm commented on modules/runners/variables.tf
> +    http_tokens                 = "required"
Can you also apply this change to:
https://github.com/philips-labs/terraform-aws-github-runner/blob/35aa73ac1e6df30d4a5c314457da5646a117131b/modules/multi-runner/variables.tf#L36

2023-10-06 15:13 UTC, dylanmtaylor commented on modules/runners/variables.tf
> +    http_tokens                 = "required"
Yes, of course.

2023-10-09 17:49 UTC, dylanmtaylor commented
> Thanks, can you apply the cahnge to the mult-runner moduel as well

@npalm This is ready for re-review.

2023-10-19 15:26 UTC, npalm approved these changes
@dylanmtaylor Thanks and sorry for the delay. Changes is checked and all good.

2023-10-19 15:26 UTC, merged