feat: added changes to enable tracing in lambdas.
philips-labs/terraform-aws-github-runner pull request #3554
Opened 2023-10-20 18:41 UTC by GuptaNavdeep1983

2023-10-25 19:53 UTC, npalm commented on modules/webhook/variables.tf
> +    capture_http_requests = optional(bool, false)
http is not relevant for the webhook

2023-10-25 19:54 UTC, npalm commented on modules/webhook/webhook.tf
> +      POWERTOOLS_TRACE_ENABLED                 = var.lambda_tracing_mode == "Active" ? true : false
Can we encode the POWERTOOLS config like the RUNNER_CONFIG?

2023-10-25 19:54 UTC, npalm commented on modules/runners/scale-down.tf
> +# resource "aws_cloudwatch_event_target" "scale_down" {
Comment needs to be removed

2023-10-25 19:56 UTC, npalm commented on lambdas/libs/aws-powertools-util/src/tracer/index.ts
> +import { Tracer, captureLambdaHandler } from '@aws-lambda-powertools/tracer';
Do we need to wrap the tracer, like we do for the logger?

2023-10-25 19:59 UTC, npalm commented on lambdas/functions/webhook/src/lambda.ts
> +export const handlerWebhook = middy(githubWebhook).use(captureLambdaHandler(tracer));
Need to read a bit of middy, for logging we do not use middy.

2023-10-31 16:29 UTC, GuptaNavdeep1983 commented on lambdas/libs/aws-powertools-util/src/tracer/index.ts
> +import { Tracer, captureLambdaHandler } from '@aws-lambda-powertools/tracer';
if we have to replace ti with opentelemetry tomorrow. Its ideai being away.

2023-10-31 20:10 UTC, npalm requested changes
@GuptaNavdeep1983 nice work. Made some comments. If you like we can pair next week to get them resolved. 

I also will try to run some tests later this week.

2023-10-31 20:10 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +  sudo chmod +x ./aws-xray-daemon-linux-3.x/xray
sudo should not be needed.

2023-10-31 20:10 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +    create_xray_error_segment "$SEGMENT" "runner-start-failed with exit code $exit_code occurred on $error_location - $error_lineno"
A conditional check seems missing here that tracing is enabled.

2023-10-31 20:10 UTC, npalm commented on modules/webhook/variables.tf
> +variable "tracing_config" {
Did we not discussed to combine the tracing variable?

2023-10-31 20:10 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +  const runnerTracingEnabled = yn(process.env.POWERTOOLS_TRACE_ENABLED, { default: false });
would tracingEnabled not be a better name?

2023-10-31 20:16 UTC, GuptaNavdeep1983 commented
@npalm are these comments blocker to the PR? Can we not address them separately?

2023-11-01 17:10 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.test.ts
> +      ...expectedCreateFleetRequest({ ...defaultExpectedFleetRequestValues, runnerTracingEnabled: true }),
this function expectedCreateFleetRequest is already checking this tag to be set.

2023-11-02 22:11 UTC, GuptaNavdeep1983 commented on modules/webhook/webhook.tf
> +      POWERTOOLS_TRACE_ENABLED                 = var.lambda_tracing_mode == "Active" ? true : false
No discussed that these env variables are used by tracer module as it is.

2023-11-02 22:11 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/axios/fetch-override.ts
> +export const axiosFetch = async (url: string, options: any) => {
Added

2023-11-02 22:12 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/lambda.ts
> +  middy(adjustPool).use(handler);
Done

2023-11-02 22:13 UTC, GuptaNavdeep1983 commented on modules/runners/templates/start-runner.sh
> +  sudo chmod +x ./aws-xray-daemon-linux-3.x/xray
Need to test it.

2023-11-02 22:14 UTC, GuptaNavdeep1983 commented on modules/runners/templates/start-runner.sh
> +    create_xray_error_segment "$SEGMENT" "runner-start-failed with exit code $exit_code occurred on $error_location - $error_lineno"
Its checked inside the function if the segment is available or not which is created only if the tracing is enabled.

2023-11-02 22:14 UTC, GuptaNavdeep1983 commented on modules/webhook/variables.tf
> +variable "tracing_config" {
already combined.

2023-11-02 22:16 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +  const runnerTracingEnabled = yn(process.env.POWERTOOLS_TRACE_ENABLED, { default: false });
Changed

2023-11-03 10:57 UTC, npalm commented on README.md
Please can you add the tracing options to the readme. Briefly explain as well what is traced.

2023-11-03 11:01 UTC, npalm commented on variables.tf
> +variable "tracing_config" {
Can you add the variable `lambda_tracing_mode` to the file depcrecated and print an error with how to migrate?

2023-11-03 11:38 UTC, npalm commented on variables.tf
> +  description = "Configuration for lambda tracing."
Please can you add more details how to use tracing?

2023-11-06 20:20 UTC, npalm commented on README.md
> +This tracing config generates timelines for following events:
Maybe mention that tracing is disabled by default.

2023-11-06 20:21 UTC, npalm reviewed
Looks good. Let's finish the PR in tomorrows call

2023-11-08 08:31 UTC, npalm commented
Notes about testing:

Testing deployment of main -> updateing to PR -> enable tracing

- [ ] multi-runner example 
- [ ] ephemeral with pool

2023-11-08 15:31 UTC, npalm approved these changes

2023-11-08 16:31 UTC, merged