chore: avoid update-docs workflow runs on pushes to main
philips-labs/terraform-aws-github-runner pull request #3617
Opened 2023-11-17 10:25 UTC by npalm

Docs should be updated on branches, in case of the locked main branch a PR is created. This to ensure the main is up-to-date.

2023-11-17 10:50 UTC, koendelaat requested changes
I think there are two options to handle `update-docs` on the `main` branch

1. Don't update docs on the `main` branch
2. Create a PR when docs need to be updated on the `main` branch

Current suggestion seems to implement both options at the same time, which makes no sense to me. So we either have to skip checking on the main branch (as suggested), but then we should also remove the conditional PR creation step.

Other option could be to fix the PR creation step.
Suggestion:

```yaml
      - name: Create Pull Request (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # ratchet:peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ steps.token.outputs.token || secrets.GITHUB_TOKEN }}
          commit-message: "Update Terraform docs"
          title: "docs: Update Terraform docs"
          branch: update-docs
          base: ${{ github.ref }}
```

2023-11-20 06:32 UTC, npalm commented
@koendelaat thx. Updated the workflow. The workflow should now run on any branch in any repo and commit changes. With only an exception for the main branch in this repo. In that case a PR should be opened.

2023-11-20 06:33 UTC, npalm commented on .github/workflows/update-docs.yml
> -      - name: Get installation token
Removed the app. This is a left over from the time we were making changes to protected branches.

2023-11-20 06:34 UTC, npalm commented on examples/default/variables.tf
> +  description = "Environment name, used as prefix."
Test workflow by making a tiny change.

2023-11-20 06:38 UTC, koendelaat requested changes

2023-11-20 06:38 UTC, koendelaat commented on .github/workflows/update-docs.yml
>            token: ${{ steps.token.outputs.token || secrets.GITHUB_TOKEN }}
This token doesn't exist anymore

2023-11-20 06:38 UTC, koendelaat commented on .github/workflows/update-docs.yml
>          uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # ratchet:peter-evans/create-pull-request@v5.0.2
The parameters of this action are incorrect, see my previous review for a suggestion

2023-11-20 06:41 UTC, npalm commented on .github/workflows/update-docs.yml
>            token: ${{ steps.token.outputs.token || secrets.GITHUB_TOKEN }}
which token?

2023-11-20 06:42 UTC, npalm commented on .github/workflows/update-docs.yml
>          uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # ratchet:peter-evans/create-pull-request@v5.0.2
fixing...

2023-11-22 11:14 UTC, npalm commented on .github/workflows/update-docs.yml
>          uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # ratchet:peter-evans/create-pull-request@v5.0.2
fiexed and testes

2023-11-22 12:19 UTC, koendelaat approved these changes

2023-11-22 12:31 UTC, merged