fix: deprecate aws_cloudwatch_event_rule.is_enabled
philips-labs/terraform-aws-github-runner pull request #3655
Opened 2023-12-07 06:29 UTC by officel

see https://github.com/philips-labs/terraform-aws-github-runner/issues/3652

2023-12-08 07:35 UTC, npalm commented
This changes also requires the verison.tf files to be updated and set the provider to minimum 5.27

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.27.0

2023-12-08 09:33 UTC, npalm commented
Just ran a deployment got the following error

```
➜  multi-runner git:(fix/deprecate_aws_cloudwatch_event_rule.is_enabled) ✗ terraform apply                               <aws:swcoe-dev-admin>
╷
│ Error: expected state to be one of ["ENABLED" "DISABLED" "ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS"], got true
│
│   with module.runners.module.ami_housekeeper.aws_cloudwatch_event_rule.ami_housekeeper,
│   on ../../modules/ami-housekeeper/main.tf line 106, in resource "aws_cloudwatch_event_rule" "ami_housekeeper":
│  106:   state               = true
```

See also https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#state

2023-12-08 09:35 UTC, npalm requested changes
The state property should be an enum, see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#state

2023-12-08 21:01 UTC, officel commented on modules/ami-housekeeper/main.tf
> +  state               = true
Would `state_event_rule_ami_housekeeper` have been better for naming?

2023-12-08 21:25 UTC, officel commented
Once you have decided on the naming and code direction, decide how to fix ssm_houcekeeper.
Are you okay like that?

2023-12-11 10:02 UTC, officel commented on modules/ami-housekeeper/main.tf
> +  state               = true
It was a variable name.

The variable name that stores the value passed to the state parameter is cloudwatch_event_rule_state.

https://github.com/philips-labs/terraform-aws-github-runner/pull/3655/commits/595382a60d4ce83ad44cfd3a99eaf45072f99568

I then found var.enable_event_rule_binaries_syncer and made it var.state_event_rule_binaries_syncer.

https://github.com/philips-labs/terraform-aws-github-runner/pull/3655/commits/f88cbb4a1da6fbb7982a0ff95589747b94b7b6cb

I thought it might be better to unify var.state_event_rule_ami_housekeeper.

2023-12-16 10:43 UTC, npalm requested changes
@officel thx, the variable `enable_event_rule_binaries_syncer` used on the top-level module and multi-runner. Can you update those as well. See also CI errors

2023-12-16 10:43 UTC, npalm commented on modules/runner-binaries-syncer/variables.tf
> +variable "state_event_rule_binaries_syncer" {
Can you add a file called varaibles.deprecated.tf and add the something like this:

```hcl
variable "enable_event_rule_binaries_syncer" {
  description = "Deprecated, see state_event_rule_binaries_syncer"
  type        = string
  default     = null
  validation {
    condition     = var.enable_event_rule_binaries_syncer == null
    error_message = "DEPRECATED: `enable_event_rule_binaries_syncer` is replaced by state_event_rule_binaries_syncer. "
  }
}
```

2023-12-18 19:31 UTC, npalm commented
@officel can you also update this file? `modules/multi-runner/runner-binaries.tf line 23, in module "runner_binaries"`

2023-12-19 01:31 UTC, officel commented
@npalm maybe green?

```bash
terraform-aws-github-runner $ gg enable_event_rule_binaries_syncer
README.md:524:| <a name="input_enable_event_rule_binaries_syncer"></a> [enable\_event\_rule\_binaries\_syncer](#input\_enable\_event\_rule\_binaries\_syncer) | DEPRECATED: Replaced by `state_event_rule_binaries_syncer`. | `bool` | `null` | no |
variables.deprecated.tf:12:variable "enable_event_rule_binaries_syncer" {
variables.deprecated.tf:17:    condition     = var.enable_event_rule_binaries_syncer == null
```

2023-12-19 20:18 UTC, npalm commented
We almost there, you need to run a `terraform init -upgrade` upgrade on the terraform examples failing in CI. The version is locked on a provider version not supporting the new field.

2023-12-20 00:21 UTC, officel commented
Do we need a setup-iam-permissions directory?

```bash
terraform-aws-github-runner $ gg -A 1 'hashicorp/aws' -- '**/versions.tf'
examples/arm64/versions.tf:4:      source  = "hashicorp/aws"
examples/arm64/versions.tf-5-      version = "~> 5.27.0"
--
examples/base/versions.tf:4:      source  = "hashicorp/aws"
examples/base/versions.tf-5-      version = "~> 5.27.0"
--
examples/default/versions.tf:4:      source  = "hashicorp/aws"
examples/default/versions.tf-5-      version = "~> 5.27.0"
--
examples/ephemeral/versions.tf:4:      source  = "hashicorp/aws"
examples/ephemeral/versions.tf-5-      version = "~> 5.27.0"
--
examples/multi-runner/versions.tf:4:      source  = "hashicorp/aws"
examples/multi-runner/versions.tf-5-      version = "~> 5.27.0"
--
examples/permissions-boundary/setup/versions.tf:4:      source  = "hashicorp/aws"
examples/permissions-boundary/setup/versions.tf-5-      version = "~> 5.27.0"
--
examples/permissions-boundary/versions.tf:4:      source  = "hashicorp/aws"
examples/permissions-boundary/versions.tf-5-      version = "~> 5.27.0"
--
examples/prebuilt/versions.tf:4:      source  = "hashicorp/aws"
examples/prebuilt/versions.tf-5-      version = "~> 5.27.0"
--
examples/ubuntu/versions.tf:4:      source  = "hashicorp/aws"
examples/ubuntu/versions.tf-5-      version = "~> 5.27.0"
--
examples/windows/versions.tf:4:      source  = "hashicorp/aws"
examples/windows/versions.tf-5-      version = "~> 5.27.0"
--
modules/ami-housekeeper/versions.tf:6:      source  = "hashicorp/aws"
modules/ami-housekeeper/versions.tf-7-      version = "~> 5.27.0"
--
modules/download-lambda/versions.tf:6:      source  = "hashicorp/aws"
modules/download-lambda/versions.tf-7-      version = "~> 5.27.0"
--
modules/multi-runner/versions.tf:6:      source  = "hashicorp/aws"
modules/multi-runner/versions.tf-7-      version = "~> 5.27.0"
--
modules/runner-binaries-syncer/versions.tf:6:      source  = "hashicorp/aws"
modules/runner-binaries-syncer/versions.tf-7-      version = "~> 5.27.0"
--
modules/runners/pool/versions.tf:6:      source  = "hashicorp/aws"
modules/runners/pool/versions.tf-7-      version = "~> 5.27.0"
--
modules/runners/versions.tf:6:      source  = "hashicorp/aws"
modules/runners/versions.tf-7-      version = "~> 5.27.0"
--
modules/setup-iam-permissions/versions.tf:6:      source  = "hashicorp/aws"
modules/setup-iam-permissions/versions.tf-7-      version = "~> 5.27.0"
--
modules/ssm/versions.tf:6:      source  = "hashicorp/aws"
modules/ssm/versions.tf-7-      version = "~> 5.27.0"
--
modules/webhook/versions.tf:6:      source  = "hashicorp/aws"
modules/webhook/versions.tf-7-      version = "~> 5.27.0"
```

2023-12-20 06:58 UTC, npalm commented
> Do we need a setup-iam-permissions directory?
> 
> ```shell
> terraform-aws-github-runner $ gg -A 1 'hashicorp/aws' -- '**/versions.tf'
> examples/arm64/versions.tf:4:      source  = "hashicorp/aws"
> examples/arm64/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/base/versions.tf:4:      source  = "hashicorp/aws"
> examples/base/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/default/versions.tf:4:      source  = "hashicorp/aws"
> examples/default/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/ephemeral/versions.tf:4:      source  = "hashicorp/aws"
> examples/ephemeral/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/multi-runner/versions.tf:4:      source  = "hashicorp/aws"
> examples/multi-runner/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/permissions-boundary/setup/versions.tf:4:      source  = "hashicorp/aws"
> examples/permissions-boundary/setup/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/permissions-boundary/versions.tf:4:      source  = "hashicorp/aws"
> examples/permissions-boundary/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/prebuilt/versions.tf:4:      source  = "hashicorp/aws"
> examples/prebuilt/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/ubuntu/versions.tf:4:      source  = "hashicorp/aws"
> examples/ubuntu/versions.tf-5-      version = "~> 5.27.0"
> --
> examples/windows/versions.tf:4:      source  = "hashicorp/aws"
> examples/windows/versions.tf-5-      version = "~> 5.27.0"
> --
> modules/ami-housekeeper/versions.tf:6:      source  = "hashicorp/aws"
> modules/ami-housekeeper/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/download-lambda/versions.tf:6:      source  = "hashicorp/aws"
> modules/download-lambda/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/multi-runner/versions.tf:6:      source  = "hashicorp/aws"
> modules/multi-runner/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/runner-binaries-syncer/versions.tf:6:      source  = "hashicorp/aws"
> modules/runner-binaries-syncer/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/runners/pool/versions.tf:6:      source  = "hashicorp/aws"
> modules/runners/pool/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/runners/versions.tf:6:      source  = "hashicorp/aws"
> modules/runners/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/setup-iam-permissions/versions.tf:6:      source  = "hashicorp/aws"
> modules/setup-iam-permissions/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/ssm/versions.tf:6:      source  = "hashicorp/aws"
> modules/ssm/versions.tf-7-      version = "~> 5.27.0"
> --
> modules/webhook/versions.tf:6:      source  = "hashicorp/aws"
> modules/webhook/versions.tf-7-      version = "~> 5.27.0"
> ```

iam premission module is only an example if you would like to setup permission budnaries

2023-12-20 12:00 UTC, npalm commented
Can you run this script in the root of the repo will will fix all the lock files

```
for dir in $(find . -name ".terraform.lock.hcl" -exec dirname {} \;); do
    echo "Upgrading modules in $dir"
    (cd "$dir" && terraform init -upgrade)
done
```

2023-12-20 13:25 UTC, officel commented
@npalm 

Sorry.
We usually don't maintain .terraform.lock.hcl at our workplace and always run it with init -upgrade, so i forgot it existed... 🙇

2023-12-20 13:31 UTC, npalm commented
CI is 😄

2023-12-20 13:49 UTC, merged

2023-12-20 13:55 UTC, officel commented
@npalm 
Thank you very much, too.
I learned a lot. 👍

2024-01-02 10:53 UTC, jizi commented on versions.tf
> +      version = "~> 5.27.0"
@npalm Was this really required? Didn't you actually mean `~> 5.27`?

2024-01-04 08:00 UTC, jizi commented on versions.tf
> +      version = "~> 5.27.0"
or actually @officel ?

2024-01-04 08:28 UTC, officel commented on versions.tf
> +      version = "~> 5.27.0"
@jizi maybe yes?

This PR was satisfied where at a minimum the state property indicated a valid version.
You may be right.

2024-01-04 09:05 UTC, jizi commented on versions.tf
> +      version = "~> 5.27.0"
yeah, but upgrading to the latest github-runner module version actually downgraded the `aws` module which is probably not what you wanted