enable_workflow_job_labels_check -> enable_runner_workflow_job_labels_check_all
philips-labs/terraform-aws-github-runner pull request #3665
Opened 2023-12-12 10:15 UTC by NadavOps

enable_workflow_job_labels_check is no longer exist, correct?
and now enable_runner_workflow_job_labels_check_all is the functioning variable, correct?

This is just to swap in the READMEs and samples

2023-12-18 19:48 UTC, npalm requested changes

2023-12-18 19:48 UTC, npalm commented on CHANGELOG.md
> +* Strict label check and replace disable_check_wokflow_job_labels by opt in enable_runner_workflow_job_labels_check_all ([#1591](https://github.com/philips-labs/terraform-aws-github-runner/issues/159
Can you revert the changelog, the log is generated based on the PRs
```suggestion
```

2023-12-19 08:48 UTC, NadavOps commented on CHANGELOG.md
> +* Strict label check and replace disable_check_wokflow_job_labels by opt in enable_runner_workflow_job_labels_check_all ([#1591](https://github.com/philips-labs/terraform-aws-github-runner/issues/159
Sure. Removed `CHANGELOG` changes

2023-12-19 09:29 UTC, npalm submitted a review, later dismissed

2023-12-20 17:16 UTC, sdarwin commented
With the PR, `enable_runner_workflow_job_labels_check_all` is being mentioned in the multi-runner README.md and variables.tf.

However, `enable_runner_workflow_job_labels_check_all`  doesn't actually exist in the context of multi-runner.   To check that:  

```

cd terraform-aws-github-runner
grep -r "enable_runner_workflow_job_labels_check_all"
```

Its only appearance is in the root level variables.tf and main.tf.  Do those apply in /examples/multi-runner/ or modules/multi-runner/?  Correct me if this is wrong.  I think what should happen, is to slightly refactor the code of multi-runner so that it uses the variable   `enable_runner_workflow_job_labels_check_all` instead of exactmatch.

2023-12-20 21:21 UTC, npalm commented
@sdarwin I hope to have tomorrow some time to dig in the label part. It certainly require some owrk. And evenutally I think some reafactoring.

2024-01-06 09:14 UTC, NadavOps commented
Did I fat finger close the PR? @npalm

2024-01-06 09:20 UTC, NadavOps commented
BTW it seems it is mentioned in variables only in the description as it actually take it from another place @sdarwin

2024-01-12 08:43 UTC, npalm approved these changes
LGTM, thx!

2024-01-12 08:44 UTC, merged

2024-01-12 14:30 UTC, sdarwin commented
> it actually take it from another place @sdarwin

@npalm which place?

The variable "enable_runner_workflow_job_labels_check_all" is defined in the root level, top level, files `variables.tf `and `main.tf`.   

https://github.com/philips-labs/terraform-aws-github-runner/blob/main/main.tf
https://github.com/philips-labs/terraform-aws-github-runner/blob/main/variables.tf

Does multi-runner reference those files?

2024-01-12 14:44 UTC, sdarwin commented
There are two possibilities:

1. A "minimal fix".  The multi-runner example files should be configured to use  "enable_runner_workflow_job_labels_check_all".   Currently https://github.com/philips-labs/terraform-aws-github-runner/tree/main/examples/multi-runner doesn't mention that variable.  

2. A more in-depth fix as mentioned in my earlier comments.