fix: move away from lambda environment variable due to size constraints
philips-labs/terraform-aws-github-runner pull request #3728
Opened 2024-01-18 17:48 UTC by GuptaNavdeep1983

[#si](https://github.com/philips-labs/terraform-aws-github-runner/issues/3594)

2024-01-30 11:30 UTC, spcaipers-arm commented
Hey guys, any idea when this is going to be merged?

2024-02-07 21:30 UTC, GuptaNavdeep1983 commented
> Hey guys, any idea when this is going to be merged?

There were few comments on this PR. Addressed and tested them today. Hopefully we should be able to merge this week.

2024-02-08 16:10 UTC, npalm reviewed
Still working on the review and test.

2024-02-08 18:09 UTC, GuptaNavdeep1983 commented on modules/webhook/variables.tf
> +variable "queues_config" {
I have tried to explain the reason for it in the PR description.

2024-02-15 16:27 UTC, npalm requested changes
A few remarks

2024-02-15 16:27 UTC, npalm commented on modules/webhook/variables.tf
> +    condition     = try(var.queues_config.matcherConfig.priority, 999) >= 0 && try(var.queues_config.matcherConfig.priority, 999) < 1000
Should we not name this to runner or matcher config.

2024-02-15 16:27 UTC, npalm commented on modules/webhook/policies/lambda-ssm.json
> +        "${parameter_queues_config_arn}"
Here also name it matcher / runner config

2024-02-15 16:27 UTC, npalm commented on modules/webhook/main.tf
> +  name  = "${var.ssm_paths.root}/runner-matcher-config"
Here include webhook in the path, so we can brinag later more webhook config in the same SSM path. Pererable via the object.

Ensure you also update the docs, see the onnfiguration docs (table with SSM paths).

2024-02-16 16:07 UTC, npalm commented on main.tf
> +    root = "${local.ssm_root_path}"
Root module was not working
```suggestion
    root = "${local.ssm_root_path}"
    webhook = "${var.ssm_paths.webhook}"
```

2024-02-16 16:08 UTC, npalm commented on modules/webhook/webhook.tf
> +    replace_triggered_by = [aws_ssm_parameter.runner_matcher_config]
Can we trigger also on change of the webhook secret?

2024-02-16 16:16 UTC, npalm commented on lambdas/functions/webhook/src/ConfigResolver.ts
> +    // load the queues config from SSM if it's not already loaded and cached
Comment can be something like, load parallel config if not cached

2024-02-16 16:17 UTC, npalm commented on modules/webhook/webhook.tf
> +    replace_triggered_by = [aws_ssm_parameter.runner_matcher_config]
Why do we need the lifecyle for the loggroup?

2024-02-16 16:20 UTC, npalm reviewed
PR looks good, made a few minor comments. Can you also check the failing CI?

2024-02-21 02:34 UTC, GuptaNavdeep1983 commented on modules/webhook/webhook.tf
> +    replace_triggered_by = [aws_ssm_parameter.runner_matcher_config]
done.

2024-02-21 02:35 UTC, GuptaNavdeep1983 commented on modules/webhook/webhook.tf
> +    replace_triggered_by = [aws_ssm_parameter.runner_matcher_config]
This is not the log group but lambda permission resource which needs to be recreated every time lambda updates.

2024-02-26 07:58 UTC, npalm approved these changes

2024-02-26 12:28 UTC, merged