feat: add retry logic to libicu download
philips-labs/terraform-aws-github-runner pull request #3748
Opened 2024-02-02 19:22 UTC by jkruse14

## Background
---
There seems to be a race condition some where with the user-data script and the EC2 starting up and locking RPM. This issue is seen elsewhere, not necessarily with this repo's user-data, see the following:

[Amazon Linux 2023 - issue with installing packages with cloud-init](https://repost.aws/questions/QU_tj7NQl6ReKoG53zzEqYOw/amazon-linux-2023-issue-with-installing-packages-with-cloud-init)

[dnf/yum both fails while being executed on instance bootstrap on Amazon Linux 2023](https://repost.aws/questions/QUgNz4VGCFSC2TYekM-6GiDQ/dnf-yum-both-fails-while-being-executed-on-instance-bootstrap-on-amazon-linux-2023)

Also, #3741

## Changes Made
---
Added a loop to retry if the rpm lock file is found which sleeps for 5 seconds then retries again with a total of 5 iterations.

## Testing
---
Spun up an instance and ran the script directly (using sudo the second time because this was not run via user-data)
<img width="339" alt="image" src="https://github.com/philips-labs/terraform-aws-github-runner/assets/16331726/33679c00-b092-4900-80fd-838bb6c31409">

2024-02-08 04:16 UTC, jkruse14 commented
@npalm - any chance we could get eyes on this?

2024-02-08 14:33 UTC, npalm reviewed
Thanks, looks good. Need to test asap

2024-02-10 00:07 UTC, jkruse14 commented
> Thanks, looks good. Need to test asap

@npalm  - Anything you need from me for testing?

2024-02-12 13:37 UTC, npalm requested changes
Looks good, a small suggestion

2024-02-12 13:37 UTC, npalm commented on modules/runners/templates/install-runner.sh
> +  attempt_count=1
```suggestion
  attempt_count=0
```

2024-02-12 16:11 UTC, npalm approved these changes

2024-02-12 16:12 UTC, merged