Add variable to configure ebs optimization for runner instances
philips-labs/terraform-aws-github-runner pull request #3901
Opened 2024-05-09 13:30 UTC by AlexShemeshWix

Add runners_ebs_optimized variable to configure ebs optimization on runner instances

2024-05-09 13:31 UTC, AlexShemeshWix commented
#skipreview

2024-05-17 07:52 UTC, npalm commented on main.tf
> +  ebs_optimized = var.runners_ebs_optimized
```suggestion
  ebs_optimized  = var.runners_ebs_optimized
```

2024-05-17 07:52 UTC, npalm commented on main.tf
> +  ebs_optimized = var.runners_ebs_optimized
please can you run the terraform formatter?

2024-05-17 07:53 UTC, npalm requested changes
Thanks, looks good, please can you fix the formatting issues?

2024-05-19 09:57 UTC, AlexShemeshWix commented on main.tf
> +  ebs_optimized = var.runners_ebs_optimized
Done

2024-05-22 12:07 UTC, npalm approved these changes

2024-05-22 12:09 UTC, merged