Allow configuring additional security groups
philips-labs/terraform-aws-github-runner pull request #392
Opened 2020-12-10 12:55 UTC by surminus

We've started recently looking to use this module and to fit it into our current infrastructure we'd like to be able to attach additional security groups to the runners. This will enable us to SSH to them which will help us debug some small customisations we're making in the user data.

2020-12-14 09:05 UTC, npalm requested changes

2020-12-14 09:05 UTC, npalm commented on modules/runners/variables.tf
> +variable "additional_security_group_ids" {
Can you rename `additional_security_group_ids` to `runner_ additional_security_group_ids` whould be a bit more aligned with other variable names.

2020-12-14 09:05 UTC, npalm commented on variables.tf
> +variable "additional_security_group_ids" {
Can you rename `additional_security_group_ids` to `runner_ additional_security_group_ids` whould be a bit more aligned with other variable names.

2020-12-16 12:38 UTC, jpalomaki commented
For better readability, would it make sense to allow a user to pass in security group _names_ using https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/security_groups?

2020-12-18 11:05 UTC, surminus commented on variables.tf
> +variable "additional_security_group_ids" {
Done!

2020-12-30 09:23 UTC, npalm approved these changes

2021-01-04 10:40 UTC, surminus commented
> For better readability, would it make sense to allow a user to pass in security group names, using this data source to then look up the IDs?

I personally think using IDs is more idiomatic for Terraform resources, but I'm happy to make this change if the consensus is to use names instead.

2021-01-18 17:04 UTC, surminus commented
Just realised this got merged in a little while ago [here](https://github.com/philips-labs/terraform-aws-github-runner/commit/99f7cc931f94c4a34773bad20d507d5f4f0121e0). Thanks! :tada:

2021-01-18 17:04 UTC, closed without merging