feat: mark orphan runners before removing them
philips-labs/terraform-aws-github-runner pull request #4001
Opened 2024-07-17 15:38 UTC by npalm

2024-07-31 13:20 UTC, stuartp44 requested changes

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/aws/runners.ts
> +      ec2FiltersBase.push({ Name: 'tag:ghr:orphan', Values: ['true'] });
```suggestion
      ec2FiltersBase.push({ Name: 'tag:ghr:Orphan', Values: ['true'] });
```
Everything else uses caps?

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/aws/runners.ts
> +            orphan: i.Tags?.find((e) => e.Key === 'ghr:orphan')?.Value === 'true',
```suggestion
            orphan: i.Tags?.find((e) => e.Key === 'ghr:Orphan')?.Value === 'true',
```
As Above

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/scale-runners/scale-down.test.ts
> +            Key: 'orphan',
```suggestion
            Key: 'Orphan',
```
As above?

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +    await tag(instanceId, [{ Key: 'orphan', Value: 'true' }]);
```suggestion
    await tag(instanceId, [{ Key: 'Orphan', Value: 'true' }]);
```
as above

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +        logger.error(`Failed to terminate orphan runner '${runner.instanceId}'`, { error: e });
Is there any need to do a catch twice?

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +  const scaleDownConfigs = JSON.parse(process.env.SCALE_DOWN_CONFIG) as [ScalingDownConfig];
I have noted here that we parse without sanity checking it first?

2024-07-31 13:20 UTC, stuartp44 commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +        logger.error(`Failed to terminate orphan runner '${runner.instanceId}'`, { error: e });
Is there any point doing a catch twice? maybe worth doing it once in the catch block

2024-07-31 13:55 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +  const scaleDownConfigs = JSON.parse(process.env.SCALE_DOWN_CONFIG) as [ScalingDownConfig];
The config is typed in Terraform, but it is a loose coupling.

2024-07-31 13:55 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +        logger.error(`Failed to terminate orphan runner '${runner.instanceId}'`, { error: e });
Did quite some testing with it, but it needed due to all the async executing.

2024-07-31 16:10 UTC, npalm commented on lambdas/functions/control-plane/src/aws/runners.ts
> +      ec2FiltersBase.push({ Name: 'tag:ghr:orphan', Values: ['true'] });
Most of the tags we use are in lower case like `ghr:environment`, `ghr:ssm_config_path` would suggest we stick to lower case an update owner and type to lower as well in a sperate PR.

2024-08-01 07:14 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +    await tag(instanceId, [{ Key: 'orphan', Value: 'true' }]);
in fact this should be `ghr:orphan`

2024-08-01 08:48 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +        logger.error(`Failed to terminate orphan runner '${runner.instanceId}'`, { error: e });
yes the inner try/catch is catchting error during termination. The outer any other inlcuding the listEC2Runners

2024-08-01 13:16 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-down.ts
> +    await tag(instanceId, [{ Key: 'orphan', Value: 'true' }]);
created #4026 for formatting of the keuys.

2024-08-01 14:02 UTC, Brend-Smits approved these changes
LGTM!

2024-08-01 14:59 UTC, merged