Add support for setting the time zone for pool schedules
philips-labs/terraform-aws-github-runner pull request #4063
Opened 2024-08-13 11:36 UTC by janslow

Fixes #4056

Replaces the `aws_cloudwatch_event_rule` in the `pool` module (which only support UTC) with `aws_scheduler_schedule`, which supports arbitrary time zones via the `schedule_expression_timezone` attribute.

The AWS EventBridge Scheduler is a drop in replacement for scheduler based AWS EventBridge Rules ([see AWS blog post](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/)), including the expression syntax and pricing.

The timezone can be set via the `schedule_expression_timezone` property via the main module or `multi-runners` module.

2024-08-13 14:06 UTC, janslow commented
Note, I've tried to run the GitHub Action to update the auto-generated Terraform Docs ([as per the contribution guide](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/CONTRIBUTING.md#submitting-a-pull-request)), but it's [failing](https://github.com/janslow/terraform-aws-github-runner/actions/runs/10369127870/job/28704207502) because [it requires credentials](https://github.com/janslow/terraform-aws-github-runner/blob/main/.github/workflows/update-docs.yml#L22-L23) that I don't have access to.

In terms of testing, I couldn't find any existing automated tests for the pool, although I have tested it on my existing install (both with and without the new property)

2024-08-13 17:13 UTC, npalm commented
> Note, I've tried to run the GitHub Action to update the auto-generated Terraform Docs ([as per the contribution guide](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/CONTRIBUTING.md#submitting-a-pull-request)), but it's [failing](https://github.com/janslow/terraform-aws-github-runner/actions/runs/10369127870/job/28704207502) because [it requires credentials](https://github.com/janslow/terraform-aws-github-runner/blob/main/.github/workflows/update-docs.yml#L22-L23) that I don't have access to.

Terraform docs will updated on either release or main branch. Feel free to create an issue to address the shortcoming in the release notes
> 
> In terms of testing, I couldn't find any existing automated tests for the pool, although I have tested it on my existing install (both with and without the new property)

We only have automated tests for the lambda's, not for the full module. We doe typically a manual test dependending on the change with one of the examples. Would be great if we have an full auto test test. Any idea would be welcome how to run auto tests for IaC on an OS repo in a secure way.

2024-08-14 18:12 UTC, janslow commented
>  Feel free to create an issue to address the shortcoming in the release notes

👍 [I've created a PR to remove the reference from the contribution guide](https://github.com/philips-labs/terraform-aws-github-runner/pull/4065), as it's no longer relevant when creating a PR.

2024-08-14 18:32 UTC, janslow commented
> Would be great if we have an full auto test test. Any idea would be welcome how to run auto tests for IaC on an OS repo in a secure way.

Unfortunately, I'm not aware of any magic solution.

For internal apps, I've used [Terratest](https://terratest.gruntwork.io/) to spin up ephemeral environments that are realistic, then run integration tests against them. I think that'd be tricky for this project though, especially given the fact it's a public project.

One possibility could be to use [Terraform's native test features](https://developer.hashicorp.com/terraform/language/tests#syntax) to plan the example modules (using [mock providers](https://developer.hashicorp.com/terraform/language/tests/mocking), so no AWS access is required), then running assertions against it. For example, asserting that all of the `aws_iam_role` resources have the correct path/permissions boundary (which I originally forgot in my PR).

2024-08-15 07:43 UTC, npalm commented
> > Would be great if we have an full auto test test. Any idea would be welcome how to run auto tests for IaC on an OS repo in a secure way.
> 
> Unfortunately, I'm not aware of any magic solution.
> 
> For internal apps, I've used [Terratest](https://terratest.gruntwork.io/) to spin up ephemeral environments that are realistic, then run integration tests against them. I think that'd be tricky for this project though, especially given the fact it's a public project.
> 
> One possibility could be to use [Terraform's native test features](https://developer.hashicorp.com/terraform/language/tests#syntax) to plan the example modules (using [mock providers](https://developer.hashicorp.com/terraform/language/tests/mocking), so no AWS access is required), then running assertions against it. For example, asserting that all of the `aws_iam_role` resources have the correct path/permissions boundary (which I originally forgot in my PR).

Thanks for the feedback! That was also my take and the reason why there no intergration tests (yet). Internally for the runners we deploy to a staging and ran validation workflows as verification. All automated.

2024-08-15 12:31 UTC, npalm commented on examples/ephemeral/main.tf
> +  #   schedule_expression_timezone = "Australia/Sydney"
Maybe also update the exmple cron expression that make sense for a certain time zone.
```suggestion
  #   size                         = 3
  #   schedule_expression = "cron(0/3 14 * * ? *)" # every 3 minutes between 14:00 and 15:00
  #   schedule_expression_timezone = "Europe/Amsterdam"

```

2024-08-15 12:34 UTC, npalm requested changes
Thanks, nice contribution. Tiny suggestion.

2024-08-15 12:34 UTC, npalm commented
Tested with ephemeral example, works as expected.

2024-08-16 08:56 UTC, janslow commented
Thanks for the review, I've accepted your suggestion

2024-08-16 10:04 UTC, npalm approved these changes

2024-08-16 10:05 UTC, npalm commented
Thanks for adding the feature! Feel free to update the other time triggers as well!

2024-08-16 10:05 UTC, npalm approved these changes

2024-08-16 10:05 UTC, merged