feat: scale up for long waiting jobs (job retry)
philips-labs/terraform-aws-github-runner pull request #4064
Opened 2024-08-13 15:37 UTC by npalm

## Description

This feature add the capability to retry scaling a runner when a job is still queued after a defined delay. This feature is added to avoid pool for ephemeral runners.

## Implementation

The module is extended with configuration top optional enable one or more retries. Once enabled the scale-up lambda will publish the same message as it recieves extend with a counter on a retry-job-queueu with a delay. A new lambda will pick the message from this queue and checks if the job is still queued (via GitHub API). In case it is still queued it is published again on je the job queue, incoming queue of the scale-up lambda

## Consequences

- This feature is meant for small fleets with ephemeral runners. Each retry check is casuing a GitHub API which can trigger a rate limit for the app. 
- This feature should make ephemerla runners more resposnive without having a pool to pick up missed jobs.
- The module allows you to force a job check before scaling, this check should be disabled.
- The delay should be set to a time that is higher than the normal boottime of a runner.

## Testing

Testing can be done as follow
- Trigger a workflow
- Terminate the created instance before the job starts
- Wait, after the delay the retry job should publish the message again which triggers a new instance creation.

- [x] Multi runners.
- [x] Default runners, not enabled requires configuraton update

## Tasks

- [x] Update docs
- [x] Update multi-runner
- [x] Check CMK keys for SQS
- [x] Limit delay to max delay of a queue.
- [x] Add optional metric for retry
- [x] Update issue with more details

2024-08-14 12:53 UTC, npalm commented on examples/default/main.tf
> +  # enable job_retry feature. Be careful with this feature, it can lead to API rate limits.
By default disabled in the example, code is for inspiration

2024-08-14 12:54 UTC, npalm commented on lambdas/functions/control-plane/jest.config.ts
> +      statements: 97.78,
Tiny change due to refactoring in gh-auth

2024-08-15 07:35 UTC, npalm commented on lambdas/functions/control-plane/src/gh-auth/gh-octokit.ts
The current way how we setup octokit is hard to mock. Started moving function around in this new module to make mocking of creating the client easier.

2024-08-15 13:24 UTC, Brend-Smits requested changes
Nice! I have yet to test these changes, will do it after pressing this request changes button.

2024-08-15 13:24 UTC, Brend-Smits commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +  const jobRetryConfig = JSON.parse(process.env.JOB_RETRY_CONFIG) as JobRetryConfig;
What would happen here if the JOB_RETRY_CONFIG is invalid? So if parsing fails.. I think an error should be logged and process should return.

2024-08-15 13:24 UTC, Brend-Smits commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +  if (jobRetryConfig.enable && payload.retryCounter < jobRetryConfig.maxAttempts) {
Could move `jobRetryConfig.enable` into an if statement before. This will make things easier to read and make logging easier. Depending on the state, the log could simply state "Job retry is disabled, skipping retry". Would leave the user not guessing in the future.

2024-08-15 13:24 UTC, Brend-Smits commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +    delay = Math.min(delay, 900); // max delay of 15 minutes
I would move this into it's own function and test it.

2024-08-15 13:24 UTC, Brend-Smits commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +    logger.debug(`Job retry is disabled or max attempts reached, skipping retry`, { payload });
Once you add an additional if statement to check if the job retry is even enabled. This log message can also be clarified to only include the message about max-attempts being reached.

2024-08-15 13:24 UTC, Brend-Smits commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> -  const ghesBaseUrl = process.env.GHES_URL;
Why did you remove this?

2024-08-15 13:24 UTC, Brend-Smits commented on modules/runners/job-retry.tf
> +module "job_retry_check" {
```suggestion
module "job_retry" {
```
to align naming with the rest..

2024-08-15 13:24 UTC, Brend-Smits commented on modules/runners/job-retry/README.md
> +# Module - Termination Watcher
This whole documentation needs updating. This is not the README for the job-retry, but a copied version of the termination watcher?

2024-08-15 13:24 UTC, Brend-Smits commented on modules/runners/job-retry/main.tf
> +  name       = "job-retry-check"
So.... job-retry or job-retry-check?
If it's job-retry-check, we should align naming of files and directories. IF not, name should be changed.

2024-08-15 13:24 UTC, Brend-Smits commented on modules/runners/job-retry/main.tf
> +  name       = "job-retry-check"
The same goes for every _check below.

2024-08-15 13:24 UTC, Brend-Smits commented on modules/runners/scale-up.tf
> +    queueUrl       = module.job_retry_check[0].job_retry_check_queue.url
So if this variable is not set, the queueUrl will be empty? What happens if it's empty? Will something down the line crash?

2024-08-15 14:25 UTC, npalm commented on docs/index.md
> +!!! Warning
No this is intended, is is mkdocs markdown

2024-08-15 14:26 UTC, npalm commented on docs/index.md
> +    This feature is Beta, changes will not trigger a major release as long in beta.
mkdocs markdown, this is ok

2024-08-15 14:26 UTC, npalm commented on docs/index.md
> +The Job Retry will allow you to retry scaling when a job is not started. When enabled the scale up lambda will send a retry message to the a SQS queue. The job retry lambda will check after a delay i
Title is here, see line 76

2024-08-15 14:41 UTC, npalm commented on modules/runners/job-retry/README.md
> +# Module - Termination Watcher
LOL the better copy paste :)

2024-08-15 14:42 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> -  const ghesBaseUrl = process.env.GHES_URL;
logic is moved to a function. The GHES_URL is part of the unit test so certainly checked.

2024-08-15 14:43 UTC, npalm commented on docs/index.md
> +!!! Warning
mkdocs markdown slang

2024-08-15 14:48 UTC, npalm commented on modules/runners/job-retry/README.md
> +# Module - Termination Watcher
good catch

2024-08-15 14:51 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +    delay = Math.min(delay, 900); // max delay of 15 minutes
for just 2 lines, lets keep it here

2024-08-15 14:56 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +  const jobRetryConfig = JSON.parse(process.env.JOB_RETRY_CONFIG) as JobRetryConfig;
Parse error. Not handled at all by the module. But the terraform input here is part of the system (interal) and typed. In case you would like to address this futerh. i suggest we make an issue to fix this in general.

2024-08-15 14:56 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/job-retry.ts
> +  if (jobRetryConfig.enable && payload.retryCounter < jobRetryConfig.maxAttempts) {
done

2024-08-16 10:43 UTC, Brend-Smits approved these changes
Looks good. I tested it and works :) 
Good job 👍🏼

2024-08-16 10:47 UTC, merged

2024-09-11 06:41 UTC, mariusfilipowski commented
Thanks for this interesting option. 
1) What do you mean with small fleets? 
2) I assume that these rate limits won't apply to GHES, will they?
3) Can this also be used with idle/pooled runners or do they have to be turned off? We have certain problem in the night, where we set the pool to 0, where we would expected that this approach could help us to get more stability.