chore: Update typos/grammar in index.md
philips-labs/terraform-aws-github-runner pull request #4151
Opened 2024-09-23 21:22 UTC by steveclifton

Fix various typo's and tidy some small grammatical errors in the index.md documentation.
Areas changed 
- Overview
- Control plane
- Job Retry
- Security
- Recommendations

2024-09-25 13:37 UTC, stuartp44 requested changes
Small change, but thanks for your contribution

2024-09-25 13:37 UTC, stuartp44 commented on docs/index.md
> +The module is designed to be used in a GitHub organization. It can also be used in a GitHub repository, but this not supports all features. The module is receiving GitHub webhook events for the `work
```suggestion
The module is designed to be used in a GitHub organization. It can also be used in a GitHub repository, but this does not supports all features. The module is receiving GitHub webhook events for the `workflow_job` event. The module will create a new runner if the event is for a workflow that requires a runner, and no runner is available. Alternatively the module can be configured as ephemeral runners. In this case the module will create a new runner for each workflow job event.
```

2024-09-25 20:55 UTC, steveclifton commented on docs/index.md
> +The module is designed to be used in a GitHub organization. It can also be used in a GitHub repository, but this not supports all features. The module is receiving GitHub webhook events for the `work
Great thanks @stuartp44 👍

2024-10-02 05:52 UTC, npalm approved these changes
thx!

2024-10-02 05:52 UTC, merged