Allow setting the market_options runners module value
philips-labs/terraform-aws-github-runner pull request #657
Opened 2021-03-09 10:39 UTC by dimisjim

In order to be able to use on_demand runners

2021-03-09 12:39 UTC, npalm commented
Thanks for submitting the PR 

@dimisjim did you check what value needs to be provided or non spot (on demand)?

2021-03-09 18:53 UTC, dimisjim commented
@npalm Yeah, according to the docs, the only possible value is "spot"

- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceMarketOptionsRequest.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template

So my assumption is that setting it to `null` would do the trick easily

2021-03-10 20:43 UTC, npalm requested changes
@dimisjim Thanks, just tested and it works. If you have time can you add in the REAMDE a small not about switching from spot to on-demand?

On small change suggested

2021-03-10 20:43 UTC, npalm commented on variables.tf
> +  description = "Market options for the action runner instances."
```suggestion
  description = "Market options for the action runner instances. Setting the value to `null` let the scaler create on-demand instances instead of spot instanes."
```

2021-03-11 15:21 UTC, dimisjim commented
@npalm https://github.com/philips-labs/terraform-aws-github-runner/pull/657/commits/360acfcd0886d13ea436870a17589197264fb6b6 lgtm :+1:

2021-03-11 15:42 UTC, npalm approved these changes

2021-03-11 15:43 UTC, merged

2021-03-26 14:33 UTC, whythecode commented
Hi! thanks a lot for this change and for this module! 😄  any plans on when this change will be released? thanks a lot in advance!

2021-03-26 15:18 UTC, npalm commented
@whythecode will release the change in the next days. Need to make one more fix in the release automation. Sorry for the delay and thx for the reminder

2021-03-26 20:33 UTC, whythecode commented
awesome, thank you for the quick response, @npalm ! And thanks again for the module, it seriously saved my team's sanity.