Improve readme
philips-labs/terraform-aws-github-runner pull request #659
Opened 2021-03-09 16:16 UTC by marcofranssen

When testing the Ubuntu example I ran into a few small issues. To resolve these I have slightly updated the docs and as well added some core dependencies in this example that allows others to use the ubuntu example without having issues running workflows that utilize commonly used actions.

2021-03-10 20:54 UTC, npalm requested changes

2021-03-10 20:54 UTC, npalm commented on README.md
> +The module supports two main scenarios for creating runners. On repository level a runner will be dedicated to only one repository, no other repository can use the runner. On organization level you c
Just wondering why this change is only syntax? Both way of linking are supported by github markdown according their spec.

2021-03-10 20:54 UTC, npalm commented on README.md
> +    -v /var/run/docker.sock:/var/run/docker.sock \
There is currently work in progress to fully automated this, I would call this stille manual but an alternative. I prefer only add a link here to the readme to this repo, instead of listing the full example. The socket is not required at all for creating an offline runner.

2021-03-10 20:54 UTC, npalm commented on README.md
> +| cloudwatch\_config | (optional) Replaces the module default cloudwatch log config. See <https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.ht
Pleease do not alter manaul those tables, the input and output table are created via terraform-docs. Via pre-commit hooks. There should be a note on the pre-commit hooks in the contribution guiide.

2021-03-26 02:48 UTC, bumbummen99 commented on README.md
> +The module supports two main scenarios for creating runners. On repository level a runner will be dedicated to only one repository, no other repository can use the runner. On organization level you c
Why is it a plain link in this paragraph but a pretty one in the paragraph below? I do not see the benefit of showing the full url in a text meant to be read.

2021-04-07 11:48 UTC, marcofranssen commented on README.md
> +    -v /var/run/docker.sock:/var/run/docker.sock \
It is required to do Docker in Docker containers.

2021-04-07 12:11 UTC, marcofranssen commented on README.md
> +The module supports two main scenarios for creating runners. On repository level a runner will be dedicated to only one repository, no other repository can use the runner. On organization level you c
Also changed this paragraph to have the pretty link.

2021-04-07 12:11 UTC, marcofranssen commented on README.md
> +| cloudwatch\_config | (optional) Replaces the module default cloudwatch log config. See <https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.ht
undid this change.

2021-04-07 12:19 UTC, marcofranssen commented on README.md
> +    -v /var/run/docker.sock:/var/run/docker.sock \
Made example by default collapsed.

2021-04-07 19:08 UTC, npalm approved these changes

2021-04-08 07:25 UTC, ryanbrainard commented on README.md
> +GitHub workflows fail immediately if there is no action runner available for your builds. Since this module supports scaling down to zero, builds will fail in case there is no active runner available
What do you think about adding to link to this in Debugging section below? I ran into this because I missed it in the setup. It could help to have to called out.

2021-04-08 18:35 UTC, merged