Create version constraint on Random, and also move to 'required_providers' (post-Terraform 0.13 change).
philips-labs/terraform-aws-github-runner pull request #707
Opened 2021-03-22 21:18 UTC by boldandbusted

This is to fix Issue #658 and is my first PR to this project. Some extra icing: update to `required_providers` post-Terraform 0.13, to squelch Terraform warnings. Thanks for this project and for applying 'Good First Issues' tags. I look forward to the PR review. :)

Note that while I did run `terraform validate` (and the code throws errors unrelated to my change), I didn't have the opportunity to run apply because of this error:

```
❯ terraform validate

Error: Invalid value for module argument

  on main.tf line 52, in module "runners":
  52:   runner_log_files = [
  53:     {
  54:       "file_path" : "/var/log/user-data.log",
  55:       "log_stream_name" : "{instance_id}/user_data"
  56:     },
  57:     {
  58:       "file_path" : "/home/runners/actions-runner/_diag/Runner_**.log",
  59:       "log_stream_name" : "{instance_id}/runner"
  60:     }
  61:   ]

The given value is not suitable for child module variable "runner_log_files"
defined at ../../variables.tf:284,1-28: element 0: attributes "log_group_name"
and "prefix_log_group" are required.
```

`terraform init` does run, showing the constraint is active:

```
❯ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v3.20.0
- Using previously-installed hashicorp/random v3.1.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Also, I did try to add a line to the CHANGELOG.md per the Contributing Guidelines, but there is no section I could see labeled "Unreleased". :/

I hope to add more to the project in the future. Cheers!

2021-03-24 18:02 UTC, npalm requested changes

2021-03-24 18:02 UTC, npalm commented on examples/ubuntu/providers.tf
>    region  = local.aws_region
Thanks for the contribution, small remark. Please can you format your code, see also CI failing job

2021-03-25 01:29 UTC, boldandbusted commented on examples/ubuntu/providers.tf
>    region  = local.aws_region
Thanks! I just pushed a commit to address formatting. I usually do run `terraform fmt --recursive` but I got too excited. :)

2021-03-28 12:40 UTC, npalm approved these changes

2021-03-28 12:41 UTC, merged