.ci: Improve dockerfile to include caching
philips-labs/terraform-aws-github-runner pull request #708
Opened 2021-03-26 19:04 UTC by seemethere

Improves dockerfile / .ci/build.sh script to output lambda zips in a
central location as well as adds buildkit caching to the docker build so
that you don't have to re-download the node_modules of each zip directly
each time you build with .ci/build.sh

This also makes improvements in that if there are only changes in one
directory then the cache will remain and the remaining lambdas will not
be re-built.

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

2021-03-28 13:07 UTC, npalm requested changes
@seemethere thanks for you contribution! Just checked the chagen. First got all kind of erros. Seems the cause is the javascript heep space. Updated the memory allocated by docker from 2GB to 4GB and all works fine. 

Please can you add a note about the required memory?

2021-03-28 20:17 UTC, seemethere commented
> @seemethere thanks for you contribution! Just checked the chagen. First got all kind of erros. Seems the cause is the javascript heep space. Updated the memory allocated by docker from 2GB to 4GB and all works fine.
> 
> Please can you add a note about the required memory?

Done!

2021-03-29 05:54 UTC, npalm approved these changes

2021-03-29 06:00 UTC, npalm commented
@seemethere Can you da me a small favour and rebase your branch due to yesterdays release?

2021-03-29 17:08 UTC, seemethere commented
> @seemethere Can you da me a small favour and rebase your branch due to yesterdays release?

Done!

2021-03-29 20:57 UTC, npalm approved these changes

2021-03-29 20:58 UTC, merged