feat: support windows binary in cache lambda
philips-labs/terraform-aws-github-runner pull request #751
Opened 2021-04-15 00:00 UTC by RichiCoder1

2021-04-15 07:34 UTC, npalm commented
Just tested

Added terraform code to the default example 
```HCL
resource "random_string" "random" {
  length  = 24
  special = false
  upper   = false
}

module "runner_binaries_win" {
  source = "../../modules/runner-binaries-syncer"

  aws_region  = local.aws_region
  environment = "windows"

  distribution_bucket_name = "${local.environment}-dist-${random_string.random.result}"
  runner_os                = "win"
  //lambda_zip = "../../lambdas-download/runner-binaries-syncer.zip"
}

```

Log result in lambda:
```
Function Logs
START RequestId: a93164de-4e96-4edd-89b2-5a4a4292d443 Version: $LATEST
2021-04-15T07:31:03.778Z	a93164de-4e96-4edd-89b2-5a4a4292d443	DEBUG	No tags found
2021-04-15T07:31:03.820Z	a93164de-4e96-4edd-89b2-5a4a4292d443	DEBUG	latest: undefined
2021-04-15T07:31:04.038Z	a93164de-4e96-4edd-89b2-5a4a4292d443	DEBUG	Start downloading actions-runner-win-x64-2.277.1.zip and uploading to S3.
2021-04-15T07:32:10.200Z	a93164de-4e96-4edd-89b2-5a4a4292d443	INFO	The new distribution is uploaded to S3.
END RequestId: a93164de-4e96-4edd-89b2-5a4a4292d443
REPORT RequestId: a93164de-4e96-4edd-89b2-5a4a4292d443	Duration: 154522.85 ms	Billed Duration: 154523 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	Init Duration: 955.06 ms
```

2021-04-15 07:36 UTC, npalm commented
@RichiCoder1  now I see you have added also scripts for a windows runner, what is the status of the PR? Once still work in progress could you set the PR in draft mode? Great work!

2021-04-15 07:39 UTC, RichiCoder1 commented
Sorry for the confusion, this PR is a WIP on top of the other one 😅

2021-04-15 07:41 UTC, npalm commented
Sorry my mistake as well. Did you know you can mark a PR in github as in draft?

2021-04-16 02:37 UTC, RichiCoder1 commented
> Sorry my mistake as well. Did you know you can mark a PR in github as in draft?

Yup! That's why I did so, since I'm still doin a bit of cleaning on this.

2021-04-18 18:27 UTC, RichiCoder1 commented
I did some basic validation to see things started, but haven't run a job using this just yet.

2021-04-19 02:59 UTC, RichiCoder1 commented
I can verify that this is now working! The windows machines take upwards of 10 minutes to spin up, but they do work.

2021-04-20 13:53 UTC, npalm commented
I will try out the PR later this week. Did you had a look on:
- The readme for updates of the support of windows?
- Add an example to the examples dir based on the default one?

2021-04-21 15:21 UTC, npalm requested changes
Just tried the PR. Would be nice if you can add an windows example. I have used the default example. Besides setting the OS, I have to set as well the ami. Since the default AMI is set to linux (by default) in the main.tf

I got windows instances created, but it seems the agent was not started. I had not the time yet to debug, or check the logs.

2021-04-21 15:26 UTC, npalm requested changes

2021-04-21 15:26 UTC, npalm commented on examples/ubuntu/main.tf
> +      "file_path" : var.runner_os == "linux" ? "/home/runners/actions-runner/_diag/Runner_**.log" : "C:/actions-runner/_diag/Runner_**.log",
Please can you revert this change, can you created a dedicated windows example?

2021-04-21 15:26 UTC, npalm commented on modules/runners/main.tf
> +  default_userdata_template      = var.runner_os == "linux" ? "${path.module}/templates/user-data.sh" : "${path.module}/templates/user-data.ps1"
The default of the module is `linux`, also in the lambda. But in those terraform statement you check the value for linux and set it otherwise to windows. I think it is more logical to check if it is set to windows, and if not set it always to the linux value, in this case the user_data.sh

2021-04-21 15:50 UTC, npalm commented
I have the runner running, picing up an empty job. For some reason having no logs in cloudwatch.

 Is there any easy way to access the windows instance? I am not used to the windows eco-system. Have the instance running in a private subnet. With linux I normally connect via SSM. Is that possible for windows as well?

2021-04-21 16:01 UTC, RichiCoder1 commented
> The readme for updates of the support of windows?

I'll get the documentation updated before the end of the week!

> I have the runner running, picing up an empty job. For some reason having no logs in cloudwatch.

Windows is generally just slower. It'll pick up logs, but there's a minutes-long delay.

> Is there any easy way to access the windows instance? I am not used to the windows eco-system. Have the instance running in a private subnet. With linux I normally connect via SSM. Is that possible for windows as well?

AWS SSM should work! It won't show up in the Session Manager for bit (until you see the "Agent Start" line on COM 1 serial logs).

2021-04-21 16:09 UTC, RichiCoder1 commented
Ah, I could be wrong about SSM. I did add a specific role. The configuration I used to test:
```
module "github-runner" {
  source  = "git::https://github.com/RichiCoder1/terraform-aws-github-runner.git?ref=feat/windows_full_support"

  aws_region = "us-east-1"
  vpc_id     = data.aws_vpc.primary_vpc.id
  subnet_ids = data.aws_subnet_ids.subnets.ids

  environment = "win-runner"

  runner_extra_labels = "windows"

  github_app = {
    key_base64     = filebase64("${path.module}/runner_key.pem")
    id             = "********"
    client_id      = "********"
    client_secret  = "********"
    webhook_secret = "********"
  }

  ami_filter = {name = ["Windows_Server-20H2-English-Core-ContainersLatest-*"]}

  runner_os = "win"

  idle_config = [{
    cron      = "0 9-17 * * 1-5"
    timeZone  = "America/Chicago"
    idleCount = 1
  }]

  key_name = "********"

  runner_iam_role_managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
  ]

  webhook_lambda_zip                = "lambda/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambda/runner-binaries-syncer-windows.zip"
  runners_lambda_zip                = "lambda/runners.zip"
  enable_organization_runners       = true
}
```

2021-04-22 21:26 UTC, npalm commented
Thx used your example. Session manager is working, bot took quite a while before it was up. Not that used to windows. The runner was not booting, seems some problem downloading the dist from the bucket. Not more time right now to dive in. Great work!

2021-04-26 03:15 UTC, RichiCoder1 commented on examples/ubuntu/main.tf
> +      "file_path" : var.runner_os == "linux" ? "/home/runners/actions-runner/_diag/Runner_**.log" : "C:/actions-runner/_diag/Runner_**.log",
Oop! My bad

2021-04-26 03:29 UTC, RichiCoder1 commented
Added an example. Dist download was working here, were you still somehow running the old binaries syncer lambda?

2021-04-26 21:35 UTC, npalm commented
Still puzzling to get the windows example working. The example is not complete yet. I have added the missing terraform code here: https://github.com/philips-labs/terraform-aws-github-runner/commit/3b2665c029391e5bd4e7fda3fd824a249232d63d

What is working
- runner is starting
- can access via SSM, needed to add policies to example

What is not working yet
- get no logging in cloudwatch 
- looks like extra labes are not used, but those labels are set by the lambda, so looks like not a windows issue to mee.

2021-04-26 21:46 UTC, RichiCoder1 commented
> get no logging in cloudwatch

If you `cat C:\UserData.log` what's the output? If you SSM in and run `C:\SetupCloudwatch.ps1`, does it run successfully and do logs show up eventually?

> looks like extra labels are not used

As in, when you look the runners in the Runner settings, it's showing the runner but not with the extra labels? I've noticed it will ignore `Windows` as that's a built-in label (e.g. `runs-on: [self-hosted,windows]`

2021-04-26 22:27 UTC, npalm commented
> > get no logging in cloudwatch
> 
> If you `cat C:\UserData.log` what's the output? If you SSM in and run `C:\SetupCloudwatch.ps1`, does it run successfully and do logs show up eventually?
> 
> > looks like extra labels are not used
> 
> As in, when you look the runners in the Runner settings, it's showing the runner but not with the extra labels? I've noticed it will ignore `Windows` as that's a built-in label (e.g. `runs-on: [self-hosted,windows]`

Just checked labels are working fine.

2021-04-26 22:29 UTC, npalm commented
User data log, looks ok to me.


```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished
Loading personal and system profiles took 1172ms.
PS C:\Windows\system32> cd '\$RECYCLE.BIN\'^C
PS C:\Windows\system32> cd c:/
PS C:\> cat .\UserData.log
**********************
Windows PowerShell transcript start
Start time: 20210426221508
Username: EC2AMAZ-R6R2ERG\Administrator
RunAs User: EC2AMAZ-R6R2ERG\Administrator
Configuration Name:
Machine: EC2AMAZ-R6R2ERG (Microsoft Windows NT 10.0.19042.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted . 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\Amazon\EC2-Windows\Launch\Invok
eUserData\UserScript.ps1'
Process ID: 1980
PSVersion: 5.1.19041.906
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.906
BuildVersion: 10.0.19041.906
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\UserData.log
VERBOSE: GET https://chocolatey.org/install.ps1 with 0-byte payload
VERBOSE: received -1-byte response of content type text/plain
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/0.10.15.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/0.10.15 to C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall
VERBOSE: Preparing to expand...
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\_rels\.rels'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.nuspec'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateysetup.psm1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\init.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\VERIFICATION.txt'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\choco.exe'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\choco.exe.ignore'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\choco.exe.manifest'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\CREDITS.txt'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\LICENSE.txt'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyInstaller.psm1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyProfile.psm1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\chocolateyScriptRunner.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\ChocolateyTabExpansion.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Format-FileSize.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-CheckSumValid.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-ChocolateyUnzip.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-ChocolateyWebFile.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariable.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariableNames.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-FtpFile.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-OSArchitectureWidth.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-PackageParameters.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-ToolsLocation.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-UACEnabled.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-UninstallRegistryKey.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-VirusCheckValid.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-WebFile.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-WebFileName.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Get-WebHeaders.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-BinFile.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyDesktopLink.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyEnvironmentVariable.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyExplorerMenuItem.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyFileAssociation.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyInstallPackage.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyPackage.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyPath.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyPinnedTaskBarItem.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyPowershellCommand.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyShortcut.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~1\AppData\Local\Temp\chocolatey\chocoInstall\tools\chocolateyInstall\helpers\functions\Install-ChocolateyVsixPackage.ps1'.
VERBOSE: Created 'C:\Users\ADMINI~ [...]

2021-04-28 02:04 UTC, RichiCoder1 commented
I think I figured out the cloudwatch issue. Basically it wasn't waiting for the installer to finish, which it should now.

2021-04-28 20:51 UTC, npalm commented
@RichiCoder1 got the runner working 🚀 

- user data logs are now sent to cloudwatch
- runners logs still empty

2021-04-28 20:54 UTC, RichiCoder1 commented
@npalm Do you see logs in `C:/actions-runner/_diag/`? Maybe I setup the windows pattern incorrectly

2021-04-28 20:56 UTC, npalm commented
> @npalm Do you see logs in `C:/actions-runner/_diag/`? Maybe I setup the windows pattern incorrectly

Will check, where do I find the AWS cloudwatch log agent config on windows?

2021-04-28 21:01 UTC, RichiCoder1 commented
I _think_ something like `& $Env:ProgramFiles\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -m ec2 -a status` should work.

2021-04-28 21:05 UTC, RichiCoder1 commented
If you wanna test log changes without having to recycle the machines, you should be able to update the CloudWatch Agent SSM Parameter and then run `& 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a fetch-config -m ec2 -s -c ssm:<ssm_key>`

2021-04-28 21:13 UTC, npalm commented
> If you wanna test log changes without having to recycle the machines, you should be able to update the CloudWatch Agent SSM Parameter and then run `& 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a fetch-config -m ec2 -s -c ssm:<ssm_key>` like you would with linux

Did some checks:

Runner dir and log files, ooks all good
```
Directory: C:\actions-runner


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/28/2021   9:01 PM                bin
d-----         4/28/2021   9:01 PM                externals
d-----         4/28/2021   9:02 PM                _diag
d-----         4/28/2021   9:02 PM                _work
-a----         4/28/2021   9:01 PM           1225 config.cmd
-a----         4/28/2021   9:01 PM           1449 run.cmd


Directory: C:\actions-runner\_diag


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/28/2021   9:02 PM                pages
-a----         4/28/2021   9:02 PM          19563 Runner_20210428-210239-utc.log
-a----         4/28/2021   9:02 PM              0 Runner_20210428-210246-utc.log
-a----         4/28/2021   9:02 PM          52645 Worker_20210428-210251-utc.log
```

Config stored in SSM used by the runner works for the user_data
```json


{
    "agent": {
        "metrics_collection_interval": 5
    },
    "logs": {
        "logs_collected": {
            "files": {
                "collect_list": [{"file_path":"/var/log/messages","log_group_name":"/github-self-hosted-runners/windows/messages","log_stream_name":"{instance_id}"},{"file_path":"C:/UserData.log","log_group_name":"/github-self-hosted-runners/windows/user_data","log_stream_name":"{instance_id}"},{"file_path":"C:/actions-runner/_diag/Runner_**.log","log_group_name":"/github-self-hosted-runners/windows/runner","log_stream_name":"{instance_id}"}]
            }
        }
    }
}
```

Checking the log files pattern in the config, also all good
```
PS C:\Program Files\Amazon\AmazonCloudWatchAgent> ls C:/actions-runner/_diag/Runner_**.log


    Directory: C:\actions-runner\_diag


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         4/28/2021   9:02 PM          19563 Runner_20210428-210239-utc.log
-a----         4/28/2021   9:04 PM          16449 Runner_20210428-210246-utc.log

```

Configuration looks good, so maybe the agent is not running proper in the background. Also messages streams reamins empty. User_data logs are sent without a problem.

2021-04-28 21:50 UTC, RichiCoder1 commented
I'll be honest, I don't know enough about CloudWatch Agent to know what's happening here 😅

2021-04-28 21:52 UTC, RichiCoder1 commented
Last effort might be to check `c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log` and see if there's any errors, but otherwise it might just be non-functional for now.

2021-04-28 22:09 UTC, npalm commented
> Last effort might be to check `c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log` and see if there's any errors, but otherwise it might just be non-functional for now.

Thx for the quick response, I will have a look again tomorrow.

2021-04-29 20:25 UTC, npalm commented
So just did another run with the windows runner. Still not have any clue why the log stream is not streamed in cloudwathc. Configuration looks al good, also the process is running. 

Checked the process
```
$Env:ProgramFiles\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -m ec2 -a status
```

Config of the runner:
```toml

PS C:\actions-runner> cd ..\ProgramData\Amazon\AmazonCloudWatchAgent\
PS C:\ProgramData\Amazon\AmazonCloudWatchAgent> cat .\amazon-cloudwatch-agent.toml
[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "1s"
  flush_jitter = "0s"
  hostname = ""
  interval = "5s"
  logfile = "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log"
  logtarget = "lumberjack"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  quiet = false
  round_interval = false

[inputs]

  [[inputs.logfile]]
    destination = "cloudwatchlogs"
    file_state_folder = "C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\state"

    [[inputs.logfile.file_config]]
      file_path = "/var/log/messages"
      from_beginning = true
      log_group_name = "/github-self-hosted-runners/windows/messages"
      log_stream_name = "i-0bc34b08c2720b446"
      pipe = false

    [[inputs.logfile.file_config]]
      file_path = "C:/UserData.log"
      from_beginning = true
      log_group_name = "/github-self-hosted-runners/windows/user_data"
      log_stream_name = "i-0bc34b08c2720b446"
      pipe = false

    [[inputs.logfile.file_config]]
      file_path = "C:/actions-runner/_diag/Runner_**.log"
      from_beginning = true
      log_group_name = "/github-self-hosted-runners/windows/runner"
      log_stream_name = "i-0bc34b08c2720b446"
      pipe = false
    [inputs.logfile.tags]
      metricPath = "logs"

```

I also find out that sometimes the runner is not starting, see the error below.


```
[2021-04-29 19:53:24Z ERR  Runner] System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.GetTenantCredential(String githubUrl, String githubToken, String runnerEvent)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2021-04-29 19:53:24Z ERR  Terminal] WRITE ERROR: Response status code does not indicate success: 500 (Internal Server Error).
[2021-04-29 19:53:24Z INFO Listener] Runner execution has finished with return code 1
```

2021-05-03 11:13 UTC, ScottGuymer commented on modules/runners/main.tf
> +        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_**.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
My suspicion is that the glob here is not understood correctly by either the OS or the thing that is doing the uploading.

2021-05-03 11:15 UTC, ScottGuymer commented on modules/runners/main.tf
> +        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_**.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
you could also just try using a single `*` instead.

2021-05-03 21:31 UTC, npalm commented on modules/runners/main.tf
> +        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_**.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
Just tested, logs get streamed to cloudwatch when I update the log config to: `"C:/actions-runner/_diag/Runner_*.log" `

2021-05-03 21:32 UTC, npalm commented on modules/runners/main.tf
> +        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_**.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
```suggestion
        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_*.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
```

2021-05-04 08:57 UTC, ScottGuymer commented on modules/runners/main.tf
> +        "file_path" : var.runner_os == "win" ? "C:/actions-runner/_diag/Runner_**.log" : "/home/runners/actions-runner/_diag/Runner_**.log",
Nice. Glad i could help!

2021-05-05 12:16 UTC, npalm commented
I have updated the target branch to a feature branch. So I can add a few minor updates before merging it back to develop.

2021-05-10 21:09 UTC, seemethere commented on modules/runners/templates/user-data.ps1
> +choco install git jq awscli archiver -y
Does this include support for running bash as shell for Windows executors or is this mainly just geared towards `cmd` and `pwsh`?

2021-05-10 22:30 UTC, RichiCoder1 commented on modules/runners/templates/user-data.ps1
> +choco install git jq awscli archiver -y
Just `cmd` and `pwsh` at the moment. Would take more work to ensure `bash` like actions does.

2021-05-10 23:50 UTC, seemethere commented on modules/runners/templates/user-data.ps1
> +choco install git jq awscli archiver -y
```suggestion
choco install jq awscli archiver -y
choco install git --params "/GitAndUnixToolsOnPath" -y
```

I believe this should get the desired effect

2021-05-11 00:32 UTC, seemethere commented
So I've tested some of this PR (mainly the user-data scripts) and one big potential problem I've identified is the fact that the windows runner service end up getting run as a non-elevated user meaning you don't have access to things like `choco install`, etc.

See an example: https://github.com/seemethere/test-repo/actions/runs/829882300

In this example `test-win-default` is the default GHA runner while `test-win-cpu` and `test-win-gpu` are using the `user-data` scripts provided here in this PR:

These are the following users (who the actions get run as):
* `test-win-default`: `fv-az153-956\runneradmin`
* `test-win-cpu`: `NT AUTHORITY\NETWORK SERVICE`

Is there a way to actually run the GHA runner service as a different user altogether?

2021-05-12 01:31 UTC, seemethere commented on modules/runners/templates/install-config-runner.ps1
> +Invoke-Expression $configCmd
This should allow you to run the actual service as an Administrator

```suggestion
# Create or update user
Add-Type -AssemblyName "System.Web"
$password = [System.Web.Security.Membership]::GeneratePassword(24, 4)
$securePassword = ConvertTo-SecureString $password -AsPlainText -Force
$username = "runneruser"
if (!(Get-LocalUser -Name $username -ErrorAction Ignore)) {
    New-LocalUser -Name $username -Password $securePassword
    Write-Host "Created $username"
}
else {
    Set-LocalUser -Name $username -Password $securePassword
    Write-Host "Changed password for $username"
}
# Add user to groups
foreach ($group in @("Administrators", "docker-users")) {
    if ((Get-LocalGroup -Name "$group" -ErrorAction Ignore) -and
        !(Get-LocalGroupMember -Group "$group" -Member $username -ErrorAction Ignore)) {
        Add-LocalGroupMember -Group "$group" -Member $username
        Write-Host "Added $username to $group group"
    }
}

# Disable User Access Control (UAC)
Set-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System -Name ConsentPromptBehaviorAdmin -Value 0 -Force
Write-Host "Disabled User Access Control (UAC)"

$configCmd = ".\config.cmd --unattended --name $InstanceId --work `"_work`" $config"
Write-Host "Invoking config command..."
Invoke-Expression $configCmd

Write-Host "Scheduling runner daemon to run as runneruser..."
$pwd = Get-Location
$action = New-ScheduledTaskAction -WorkingDirectory "$pwd" -Execute "run.cmd"
$trigger = Get-CimClass "MSFT_TaskRegistrationTrigger" -Namespace "Root/Microsoft/Windows/TaskScheduler"
Register-ScheduledTask -TaskName "runnertask" -Action $action -Trigger $trigger -User $username -Password $password -RunLevel Highest -Force

```

2021-05-21 12:59 UTC, merged