add white listing of repositories
philips-labs/terraform-aws-github-runner pull request #915
Opened 2021-06-21 13:19 UTC by ravenolf

Signed-off-by: ravenolf <benahmed@soramitsu.co.jp>

2021-06-24 22:34 UTC, npalm commented
Thanks for creating the PR. I will check the PR early next week

2021-06-30 12:16 UTC, npalm requested changes
@ravenolf thanks for proposing the change, in general the change looks good to me. Can you add a unit test to check the case.

2021-06-30 12:16 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    if (repositoryWhiteList.length > 0) {
Can you add a unit test for this case?

2021-06-30 12:18 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    const repositoryWhiteList = JSON.parse(repositoryWhiteListEnv) as Array<string>;
Just a thought, may it is better to specify the repos's as `owner/repo` this ensure the nameas are always unique. Potential the runner can also be setup on org level. What do you think?

2021-07-06 18:51 UTC, ravenolf commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    const repositoryWhiteList = JSON.parse(repositoryWhiteListEnv) as Array<string>;
In the code I'm using the repository.full_name which looks like `owner/repo-name`

2021-07-06 19:14 UTC, ravenolf commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    if (repositoryWhiteList.length > 0) {
Sure, done!

2021-07-06 20:35 UTC, npalm commented on modules/webhook/lambdas/webhook/src/webhook/handler.ts
> +    const repositoryWhiteList = JSON.parse(repositoryWhiteListEnv) as Array<string>;
yep

2021-07-07 12:15 UTC, npalm approved these changes
@ravenolf thanks!

2021-07-07 12:15 UTC, merged

2021-08-13 15:20 UTC, dimisjim commented
what's the default behavior after introducing this variable?

if one doesn't set this var, does it mean that the github app is not gonna work for any repo?

2021-08-17 06:45 UTC, npalm commented
Default is: no white list is used. Only once set