Move Lambda Vars to Parameter Store
philips-labs/terraform-aws-github-runner pull request #941
Opened 2021-06-25 18:40 UTC by mcaulifn

With the addition of #898 , the environment variable size for the `scale-up` lambda could exceed the 4kb size limit. This reduces the size by moving variables to Parameter Store as `SecureString`s.

- Moves GitHub auth variables to Parameter Store
- Removes KMS from `runners` submodule
- Fixes outstanding lint

Fixes #587

2021-06-25 19:29 UTC, mcaulifn commented
@npalm Got another one for you 🚀

2021-06-30 05:50 UTC, npalm commented
@mcaulifn short update, planned to check your PR this afternoon

2021-06-30 15:07 UTC, npalm requested changes
@mcaulifn thanks for taking the time to contribute to this module!!! I have a few somments. The change is not working at the moment since some policies to retrieve the parameters from SSM by the Lambda are missing.

2021-06-30 15:15 UTC, mcaulifn commented on modules/runners/ssm.tf
> +  name  = "/actions_runner/${var.environment}/github_app_client_id"
I will add it to the policy. Not looking to change the existing pattern.

2021-06-30 16:40 UTC, mcaulifn commented on modules/runners/ssm.tf
> +  value = var.github_app.key_base64
Added `kms_key_id` back in. There is no option to not encrypt though.

2021-06-30 16:42 UTC, mcaulifn commented on modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts
> +const GITHUB_APP_CLIENT_ID = '1';
I do see these being used for auth.

2021-06-30 16:54 UTC, npalm commented on modules/runners/policies-runner.tf
> +        "arn:aws:ssm:${var.aws_region}:${data.aws_caller_identity.current.account_id}:parameter/${var.environment}/*"
Having a second thougt, this change grants the runner instance role to read any parameter in SSM. The runner should only able to read the token generated for the instance. So suggest we only grant the runner access to environment-*. I will refactor this later in even a more clear path that only gives access to this token. We should avoid that a process in the runner could call the aws api and fetch the token to start acting as the app.

With updating this policy you change only the policies attached to runner. I think it is better to create a new template, for example lambda-ssm-parameter-policies.json. Which you grant read access to the pramaters in the path environment/github_app/* So it clear that the lambda can act on behalf of the app.

2021-06-30 16:56 UTC, mcaulifn commented on modules/runners/policies-runner.tf
> +        "arn:aws:ssm:${var.aws_region}:${data.aws_caller_identity.current.account_id}:parameter/${var.environment}/*"
Sounds good. I'll draft up something a bit more limiting.

2021-07-01 11:32 UTC, mcaulifn commented on modules/runners/policies-runner.tf
> +        "arn:aws:ssm:${var.aws_region}:${data.aws_caller_identity.current.account_id}:parameter/${var.environment}/*"
Looks like there is already a lambda policy template that has SSM permissions.

2021-07-01 11:47 UTC, mcaulifn commented
@npalm I still need to deploy this in test. Hoping today or Monday.

2021-07-01 11:56 UTC, npalm commented
> @npalm I still need to deploy this in test. Hoping today or Tuesday.

Take your time, I have no option to check a deployment before Tuesday. Great work!

2021-07-07 11:55 UTC, npalm commented
Ready to check?

2021-07-07 17:56 UTC, mcaulifn commented
@npalm Should be good now

2021-07-08 06:59 UTC, npalm commented
Thx, will run a check asap

2021-07-13 21:56 UTC, npalm commented
Please can you rebase you PR. We had a problem in the latest release related to vercel/ncc which was causing TypeErrors in the scale up lambda. I have just release 0.15.1 with a fix

2021-07-14 16:24 UTC, npalm commented
Just tried an upgrade from 0.15.1 to this PR, the scale up lambda gives the following error. Do you recognize the error?

```
2021-07-14T16:19:34.461Z	50420e48-7edd-5269-967f-57216e08d654	ERROR	Error: Cannot decrypt.
    at Object.<anonymous> (/var/task/index.js:58044:19)
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/index.js:58014:58)
    
   ```

2021-07-14 17:34 UTC, mcaulifn commented
@npalm Rebased and redeployed

2021-07-14 18:48 UTC, npalm commented
thanks, will test asap

2021-07-14 20:13 UTC, npalm commented on modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts
> +const GITHUB_APP_CLIENT_ID = '1';
Yes they are passed, pass but not required.

2021-07-15 15:46 UTC, npalm requested changes
Great work so far. I have tested a basic upgrade.

- Scaling up works fine with an AWS manabed key.
- Scaling down looks broken. I got a message like: Orphan runner 'i-123' cannot be removed. https://github.com/philips-labs/terraform-aws-github-runner/blob/68635ddb9e1828d50a5e62ce6c8c5da589d501cd/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L184 So this means the runner was removed in an earlier scale down attempt. Runner is removed from github but instance still running in AWS. most likely a permission issue.
- Not tested the CMK yet. but will fail since there is no permission to decrypt.
- Are you aware that also the webhook is using KMS to store the github app secret?
- Right now by default the standard SSM policy is attached to the runner, this grant access to all SSM parameters. Looks like we have to see how we can make this stricter

2021-07-15 15:46 UTC, npalm commented on modules/runners/scale-up.tf
> +      "ssm:GetParameter"
Also here for a CMK decrypt is required.

2021-07-15 16:14 UTC, mcaulifn commented on modules/runners/scale-down.tf
> +data "aws_iam_policy_document" "scale_down" {
Moving this to a policy file may make the CMK permissions more complicated. I'll play around with it.

2021-07-15 16:14 UTC, mcaulifn commented on modules/runners/scale-down.tf
> +    resources = [
Good catch - will add this to the policy.

2021-07-15 16:15 UTC, mcaulifn commented on modules/runners/scale-up.tf
> +      "ssm:GetParameter"
`encrypt` will also be needed based on the way I read the doc you linked.

2021-07-15 16:18 UTC, mcaulifn commented
> Are you aware that also the webhook is using KMS to store the github app secret?

2021-07-15 16:49 UTC, npalm commented
> > Are you aware that also the webhook is using KMS to store the github app secret?
> 
> Did you want me to do that in a separate PR or this PR?
> 
> > Right now by default the standard SSM policy is attached to the runner, this grant access to all SSM parameters. Looks like we have to see how we can make this stricter
> 
> The policy limits to those parameters prefaced with `${var.environment}-*`. The new parameters are `/actions_runner/${var.environment}/github_blah`. I don't think there will be unnecessary permissions for the runners here.

- Since we trying to remove KMS in this PR, I prefer to remove the webhook as well. So would prefer al in one PR.
- And the moment the user enabled ssm https://github.com/philips-labs/terraform-aws-github-runner/blob/68635ddb9e1828d50a5e62ce6c8c5da589d501cd/modules/runners/policies-runner.tf#L17 the attaced policy grant access to all parameters. This we can address in a seprate PR. But think the scope of the standard policy it so wide.

2021-07-15 16:50 UTC, npalm commented on modules/runners/scale-up.tf
> +      "ssm:GetParameter"
encrypt is used for put parameter, so that is done by terraform for the parameters you introduced.

2021-07-15 16:51 UTC, npalm commented on modules/runners/scale-down.tf
> +data "aws_iam_policy_document" "scale_down" {
Let me know if you need a couple of complex examples for inspiraction.

2021-07-16 19:05 UTC, mcaulifn commented
I think I got all the changes. I tested with and without a CMK defined.

2021-07-21 07:03 UTC, npalm commented
> I think I got all the changes. I tested with and without a CMK defined.

Thanks, sorry for the late response, will do my best to check the PR in the next days

2021-07-26 16:12 UTC, npalm reviewed
Test default example including upgrade (withou CMK). All works like a charm.

2021-07-26 19:40 UTC, npalm requested changes
@mcaulifn thanks for all the hard work. I think your change is the way forward but find some issues that I would like to addres or need at least a bit more of thinking. 

### SSM parameters
The new introduced paramaters are defined on root level of the runner. And the lambda's are doing a looking up based on convention. The whole module is designed in such way that it is also possible to use the sub modules complete seperate. When users of the module are using the module via the submodules, they also are required to create the SSM parameters as weel. Same holds for the SQS queue. What we could do is move the parameters to a submodule to do the constuction work


### Removal of CMK
Currently the runner is managoing by default a CMK. For this change we have to update the README as well. 


### Migrations paths
No migration is required which I really like. But I have tested several ipdates. Swapping between runner managed key (aws default) and CMK creates some raise conditon. SSM parameters are not correctly updated. I have made some changes to `ssm..tf`

```HCL
locals {
  default_key_ssm = "alias/aws/ssm"
}

resource "aws_ssm_parameter" "github_app_client_id" {
  name   = "/actions_runner/${var.environment}/github_app_client_id"
  type   = "SecureString"
  value  = var.github_app.client_id
  key_id = var.kms_key_id == null ? local.default_key_ssm : var.kms_key_id
}

# Same for the orther resources
````

With this changes SSM parameters are correctly stored.


### SSM sessions
I will create a seperate PR for decreasing the privileges to the runner instances for SSM sessions. 


Would be great if you can make some time to chck my remakrts. Oterwise I can merge the PR to a branch and fix the left overs in next week. Please let me know what you preferences is.

2021-07-26 20:36 UTC, mcaulifn commented
@npalm I'll get these sorted tomorrow. 

I'm curious about the migrations though. I had migrated between no key and key and didn't have any issues so I'm surprised you did.

2021-07-26 20:38 UTC, npalm commented
> @npalm I'll get these sorted tomorrow.
> 
> I'm curious about the migrations though. I had migrated between no key and key and didn't have any issues so I'm surprised you did.

Problem occurs when moving back to no key. Once looking up the resources in SSM the key was still there. Therefore I added explicit the aws alias key for SSM. And set the parameter overwrite to true

2021-07-28 14:51 UTC, mcaulifn commented
Deployed to test using CMK. @npalm Should be good to go

2021-07-28 21:18 UTC, npalm requested changes
Just 2 small findings Great work!

2021-07-28 21:18 UTC, npalm commented on kms.tf
> +data "aws_kms_key" "cmk" {
This resource generates a raise conditon when you create a KMS cmk key in the same run as the module. I was able to reslove the issue by first creating the CMK. 

I got the issue resolved by removing the data source and let the user inject the arn instead of looking up.

2021-07-28 21:32 UTC, mcaulifn commented on modules/ssm/ssm.tf
> +  key_id = var.kms_key_arn
Works with either. ARN is more deterministic. If it resolves the issue below, then I'll remove the data source and let the value passed in stand.

2021-07-28 21:37 UTC, npalm commented on modules/ssm/ssm.tf
> +  key_id = var.kms_key_arn
The arn is also required for the policies, so in some way the module requires the arn. Any idea how to fix this?

2021-07-28 23:06 UTC, mcaulifn commented on modules/ssm/ssm.tf
> +  key_id = var.kms_key_arn
It could be templated. `arn:${Partition}:ssm:${Region}:${Account}:parameter/${ParameterNameWithoutLeadingSlash}`

2021-07-29 08:52 UTC, npalm commented on modules/ssm/ssm.tf
> +  key_id = var.kms_key_arn
After a bit of reading (https://www.terraform.io/docs/language/modules/develop/composition.html#dependency-inversion). I think we should not use data sources of resources not contolled by the module. Let the user inject the required fiels. So think we have 2 options
- template the ARN as you suggest
- or let the user inject the arn and key

2021-07-29 12:23 UTC, mcaulifn commented on modules/ssm/ssm.tf
> +  key_id = var.kms_key_arn
To simplify this, I think the best way is to support either the key ID or ARN but not both. Both would require two variables with conditional checks. It would be cleaner to only support one for now. For simplicity, I'm leaning towards ARN and will update the module to use that.

2021-07-29 13:15 UTC, mcaulifn commented
@npalm Deployed using CMK then migrated to default key.

2021-07-30 07:05 UTC, npalm commented
LGTM, will test asap. So summarising: users using the module should update their config with the cmk arn instead of the id.

2021-08-04 06:41 UTC, npalm commented
Will do a bit more testing before merging. But expect no required changes

2021-08-04 07:26 UTC, npalm approved these changes
@mcaulifn thanks for all the refactoring work!

2021-08-04 11:30 UTC, merged

2021-08-13 17:24 UTC, dimisjim commented
Hey there,

so basically after these changes, there is no longer the option to have the secrets **not** encrypted?

2021-08-16 20:14 UTC, mcaulifn commented
@dimisjim Yes, that is correct.